// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp
// NOTE: source: C:\Users\vodan\4ed\code\game\ad_file_formats.kh








// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum Weight_Key{Weight_None,
Weight_Blink,
Weight_Count,};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:579:
function Type_Info
get_type_info_Weight_Key();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:583:
function Type_Info
get_type_info_Weight_Key(){
Type_Info result = {};
result.name = strlit("Weight_Key");
result.size = sizeof(Weight_Key);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(3);
result.enum_members[0] = {.name=strlit("Weight_None"), .value=Weight_None};
result.enum_members[1] = {.name=strlit("Weight_Blink"), .value=Weight_Blink};
result.enum_members[2] = {.name=strlit("Weight_Count"), .value=Weight_Count};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Weight_Key;

function Type_Info *type_info_from_pointer(Weight_Key*pointer){
return &Type_Info_Weight_Key;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:607:
function void
read_binary_Weight_Key(Binary_Reader *r, Weight_Key *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:612:
function void
read_binary_Weight_Key(Binary_Reader *r, Weight_Key *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Weight_Key*)(&integer);
}
static_assert( sizeof(Weight_Key) <= sizeof(i32) );

#endif
;
struct Dual_Bezier{
Bezier P;
Bezier Q;
Weight_Key key;
v3 dP[4];
v3 dQ[4];
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Dual_Bezier(){
Type_Info result = {};
result.name = strlit("Dual_Bezier");
result.size = sizeof(Dual_Bezier);
result.kind = I_Type_Kind_Struct;
result.members.set_count(5);
{
Type_Info *member_type = & Type_Info_Bezier;
result.members[0] = {.type=member_type, .name=strlit("P"), .offset=offsetof(Dual_Bezier, P)};
}
{
Type_Info *member_type = & Type_Info_Bezier;
result.members[1] = {.type=member_type, .name=strlit("Q"), .offset=offsetof(Dual_Bezier, Q)};
}
{
Type_Info *member_type = & Type_Info_Weight_Key;
result.members[2] = {.type=member_type, .name=strlit("key"), .offset=offsetof(Dual_Bezier, key)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("v3[4]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 4 * Type_Info_v3.size;
member_type->array_item_type = & Type_Info_v3;
member_type->count = 4;
result.members[3] = {.type=member_type, .name=strlit("dP"), .offset=offsetof(Dual_Bezier, dP)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("v3[4]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 4 * Type_Info_v3.size;
member_type->array_item_type = & Type_Info_v3;
member_type->count = 4;
result.members[4] = {.type=member_type, .name=strlit("dQ"), .offset=offsetof(Dual_Bezier, dQ)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Dual_Bezier;

function Type_Info *type_info_from_pointer(Dual_Bezier*pointer){
return &Type_Info_Dual_Bezier;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Dual_Bezier(Binary_Reader *r, Dual_Bezier *dst){
Bezier m_P = {};
{
read_binary_Bezier(r, &m_P);
}
dst->P = m_P;

Bezier m_Q = {};
{
read_binary_Bezier(r, &m_Q);
}
dst->Q = m_Q;

Weight_Key m_key = {};
{
read_binary_Weight_Key(r, &m_key);
}
dst->key = m_key;

v3 m_dP[4] = {};
{
for_i32(i,0,4){
read_binary_v3(r, &m_dP[i]);
}
}
copy_array_dst(dst->dP, m_dP);

v3 m_dQ[4] = {};
{
for_i32(i,0,4){
read_binary_v3(r, &m_dQ[i]);
}
}
copy_array_dst(dst->dQ, m_dQ);


}
#endif
;
struct Recorded_Poly3{
tvert points[3];
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Poly3(){
Type_Info result = {};
result.name = strlit("Recorded_Poly3");
result.size = sizeof(Recorded_Poly3);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("tvert[3]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 3 * Type_Info_tvert.size;
member_type->array_item_type = & Type_Info_tvert;
member_type->count = 3;
result.members[0] = {.type=member_type, .name=strlit("points"), .offset=offsetof(Recorded_Poly3, points)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Poly3;

function Type_Info *type_info_from_pointer(Recorded_Poly3*pointer){
return &Type_Info_Recorded_Poly3;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Poly3(Binary_Reader *r, Recorded_Poly3 *dst){
tvert m_points[3] = {};
{
for_i32(i,0,3){
read_binary_tvert(r, &m_points[i]);
}
}
copy_array_dst(dst->points, m_points);


}
#endif
;
struct Disk{
tvert center;
v1 radius;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Disk(){
Type_Info result = {};
result.name = strlit("Disk");
result.size = sizeof(Disk);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_tvert;
result.members[0] = {.type=member_type, .name=strlit("center"), .offset=offsetof(Disk, center)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[1] = {.type=member_type, .name=strlit("radius"), .offset=offsetof(Disk, radius)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Disk;

function Type_Info *type_info_from_pointer(Disk*pointer){
return &Type_Info_Disk;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Disk(Binary_Reader *r, Disk *dst){
tvert m_center = {};
{
read_binary_tvert(r, &m_center);
}
dst->center = m_center;

v1 m_radius = {};
{
read_binary_v1(r, &m_radius);
}
dst->radius = m_radius;


}
#endif
;
struct Recorded_Image{
String filename;
v3 o;
v3 x;
v3 y;
v3 color;
v1 alpha;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Image(){
Type_Info result = {};
result.name = strlit("Recorded_Image");
result.size = sizeof(Recorded_Image);
result.kind = I_Type_Kind_Struct;
result.members.set_count(6);
{
Type_Info *member_type = & Type_Info_String;
result.members[0] = {.type=member_type, .name=strlit("filename"), .offset=offsetof(Recorded_Image, filename)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[1] = {.type=member_type, .name=strlit("o"), .offset=offsetof(Recorded_Image, o)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[2] = {.type=member_type, .name=strlit("x"), .offset=offsetof(Recorded_Image, x)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[3] = {.type=member_type, .name=strlit("y"), .offset=offsetof(Recorded_Image, y)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[4] = {.type=member_type, .name=strlit("color"), .offset=offsetof(Recorded_Image, color)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[5] = {.type=member_type, .name=strlit("alpha"), .offset=offsetof(Recorded_Image, alpha)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Image;

function Type_Info *type_info_from_pointer(Recorded_Image*pointer){
return &Type_Info_Recorded_Image;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Image(Binary_Reader *r, Recorded_Image *dst){
String m_filename = {};
{
read_binary_String(r, &m_filename);
}
dst->filename = m_filename;

v3 m_o = {};
{
read_binary_v3(r, &m_o);
}
dst->o = m_o;

v3 m_x = {};
{
read_binary_v3(r, &m_x);
}
dst->x = m_x;

v3 m_y = {};
{
read_binary_v3(r, &m_y);
}
dst->y = m_y;

v3 m_color = {};
{
read_binary_v3(r, &m_color);
}
dst->color = m_color;

v1 m_alpha = {};
{
read_binary_v1(r, &m_alpha);
}
dst->alpha = m_alpha;


}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum Primitive_Type{Primitive_Type_None,
Primitive_Type_Curve,
Primitive_Type_Poly3,
Primitive_Type_Dual_Bezier,
Primitive_Type_Patch,
Primitive_Type_Disk,
Primitive_Type_Image,
Primitive_Type_Curve_Patch,};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:579:
function Type_Info
get_type_info_Primitive_Type();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:583:
function Type_Info
get_type_info_Primitive_Type(){
Type_Info result = {};
result.name = strlit("Primitive_Type");
result.size = sizeof(Primitive_Type);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(8);
result.enum_members[0] = {.name=strlit("Primitive_Type_None"), .value=Primitive_Type_None};
result.enum_members[1] = {.name=strlit("Primitive_Type_Curve"), .value=Primitive_Type_Curve};
result.enum_members[2] = {.name=strlit("Primitive_Type_Poly3"), .value=Primitive_Type_Poly3};
result.enum_members[3] = {.name=strlit("Primitive_Type_Dual_Bezier"), .value=Primitive_Type_Dual_Bezier};
result.enum_members[4] = {.name=strlit("Primitive_Type_Patch"), .value=Primitive_Type_Patch};
result.enum_members[5] = {.name=strlit("Primitive_Type_Disk"), .value=Primitive_Type_Disk};
result.enum_members[6] = {.name=strlit("Primitive_Type_Image"), .value=Primitive_Type_Image};
result.enum_members[7] = {.name=strlit("Primitive_Type_Curve_Patch"), .value=Primitive_Type_Curve_Patch};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Primitive_Type;

function Type_Info *type_info_from_pointer(Primitive_Type*pointer){
return &Type_Info_Primitive_Type;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:607:
function void
read_binary_Primitive_Type(Binary_Reader *r, Primitive_Type *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:612:
function void
read_binary_Primitive_Type(Binary_Reader *r, Primitive_Type *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Primitive_Type*)(&integer);
}
static_assert( sizeof(Primitive_Type) <= sizeof(i32) );

#endif
;
struct Recorded_Curve_Patch{
i32 curve_count;
i32 curve_index[4];
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Curve_Patch(){
Type_Info result = {};
result.name = strlit("Recorded_Curve_Patch");
result.size = sizeof(Recorded_Curve_Patch);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_i32;
result.members[0] = {.type=member_type, .name=strlit("curve_count"), .offset=offsetof(Recorded_Curve_Patch, curve_count)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("i32[4]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 4 * Type_Info_i32.size;
member_type->array_item_type = & Type_Info_i32;
member_type->count = 4;
result.members[1] = {.type=member_type, .name=strlit("curve_index"), .offset=offsetof(Recorded_Curve_Patch, curve_index)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Curve_Patch;

function Type_Info *type_info_from_pointer(Recorded_Curve_Patch*pointer){
return &Type_Info_Recorded_Curve_Patch;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Curve_Patch(Binary_Reader *r, Recorded_Curve_Patch *dst){
i32 m_curve_count = {};
{
read_binary_i32(r, &m_curve_count);
}
dst->curve_count = m_curve_count;

i32 m_curve_index[4] = {};
{
for_i32(i,0,4){
read_binary_i32(r, &m_curve_index[i]);
}
}
copy_array_dst(dst->curve_index, m_curve_index);


}
#endif
;
struct Recorded_Curve{
Bezier bezier;
v4 radii;
v4 lightness_additions;
b32 straight;
Weight_Key key;
v3 dbezier[4];
v4 dradii;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Curve(){
Type_Info result = {};
result.name = strlit("Recorded_Curve");
result.size = sizeof(Recorded_Curve);
result.kind = I_Type_Kind_Struct;
result.members.set_count(7);
{
Type_Info *member_type = & Type_Info_Bezier;
result.members[0] = {.type=member_type, .name=strlit("bezier"), .offset=offsetof(Recorded_Curve, bezier)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[1] = {.type=member_type, .name=strlit("radii"), .offset=offsetof(Recorded_Curve, radii)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[2] = {.type=member_type, .name=strlit("lightness_additions"), .offset=offsetof(Recorded_Curve, lightness_additions)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[3] = {.type=member_type, .name=strlit("straight"), .offset=offsetof(Recorded_Curve, straight)};
}
{
Type_Info *member_type = & Type_Info_Weight_Key;
result.members[4] = {.type=member_type, .name=strlit("key"), .offset=offsetof(Recorded_Curve, key)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("v3[4]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 4 * Type_Info_v3.size;
member_type->array_item_type = & Type_Info_v3;
member_type->count = 4;
result.members[5] = {.type=member_type, .name=strlit("dbezier"), .offset=offsetof(Recorded_Curve, dbezier)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[6] = {.type=member_type, .name=strlit("dradii"), .offset=offsetof(Recorded_Curve, dradii)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Curve;

function Type_Info *type_info_from_pointer(Recorded_Curve*pointer){
return &Type_Info_Recorded_Curve;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Curve(Binary_Reader *r, Recorded_Curve *dst){
Bezier m_bezier = {};
{
read_binary_Bezier(r, &m_bezier);
}
dst->bezier = m_bezier;

v4 m_radii = {};
{
read_binary_v4(r, &m_radii);
}
dst->radii = m_radii;

v4 m_lightness_additions = {};
{
read_binary_v4(r, &m_lightness_additions);
}
dst->lightness_additions = m_lightness_additions;

b32 m_straight = {};
{
read_binary_b32(r, &m_straight);
}
dst->straight = m_straight;

Weight_Key m_key = {};
{
read_binary_Weight_Key(r, &m_key);
}
dst->key = m_key;

v3 m_dbezier[4] = {};
{
for_i32(i,0,4){
read_binary_v3(r, &m_dbezier[i]);
}
}
copy_array_dst(dst->dbezier, m_dbezier);

v4 m_dradii = {};
{
read_binary_v4(r, &m_dradii);
}
dst->dradii = m_dradii;


}
#endif
;
struct Recorded_Vertex{
v3 p;
Bone_ID bone;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Vertex(){
Type_Info result = {};
result.name = strlit("Recorded_Vertex");
result.size = sizeof(Recorded_Vertex);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_v3;
result.members[0] = {.type=member_type, .name=strlit("p"), .offset=offsetof(Recorded_Vertex, p)};
}
{
Type_Info *member_type = & Type_Info_Bone_ID;
result.members[1] = {.type=member_type, .name=strlit("bone"), .offset=offsetof(Recorded_Vertex, bone)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Vertex;

function Type_Info *type_info_from_pointer(Recorded_Vertex*pointer){
return &Type_Info_Recorded_Vertex;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Vertex(Binary_Reader *r, Recorded_Vertex *dst){
v3 m_p = {};
{
read_binary_v3(r, &m_p);
}
dst->p = m_p;

Bone_ID m_bone = {};
{
read_binary_Bone_ID(r, &m_bone);
}
dst->bone = m_bone;


}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:501:
union Recorded_Primitive_Union{
Recorded_Curve curve;
Recorded_Poly3 poly3;
Dual_Bezier dual_bezier;
Patch patch;
Disk disk;
Recorded_Image image;
Recorded_Curve_Patch curve_patch;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:518:
function Type_Info
get_type_info_Recorded_Primitive_Union(){
Type_Info result = {};
result.name = strlit("Recorded_Primitive_Union");
result.size = sizeof(Recorded_Primitive_Union);
result.kind = I_Type_Kind_Union;
result.discriminator_type = &Type_Info_Primitive_Type;
result.union_members.set_count(7);
result.union_members[0] = {.type=&Type_Info_Recorded_Curve, .name=strlit("curve"), .variant=Primitive_Type_Curve};
result.union_members[1] = {.type=&Type_Info_Recorded_Poly3, .name=strlit("poly3"), .variant=Primitive_Type_Poly3};
result.union_members[2] = {.type=&Type_Info_Dual_Bezier, .name=strlit("dual_bezier"), .variant=Primitive_Type_Dual_Bezier};
result.union_members[3] = {.type=&Type_Info_Patch, .name=strlit("patch"), .variant=Primitive_Type_Patch};
result.union_members[4] = {.type=&Type_Info_Disk, .name=strlit("disk"), .variant=Primitive_Type_Disk};
result.union_members[5] = {.type=&Type_Info_Recorded_Image, .name=strlit("image"), .variant=Primitive_Type_Image};
result.union_members[6] = {.type=&Type_Info_Recorded_Curve_Patch, .name=strlit("curve_patch"), .variant=Primitive_Type_Curve_Patch};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Primitive_Union;

function Type_Info *type_info_from_pointer(Recorded_Primitive_Union*pointer){
return &Type_Info_Recorded_Primitive_Union;
}
#endif
#endif
struct Recorded_Primitive{
Primitive_Type type;
Location location;
i32 group_index;
i32 vertex_index[recorded_vertex_cap];
union { Recorded_Curve curve; Recorded_Poly3 poly3; Dual_Bezier dual_bezier; Patch patch; Disk disk; Recorded_Image image; Recorded_Curve_Patch curve_patch; };
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Primitive(){
Type_Info result = {};
result.name = strlit("Recorded_Primitive");
result.size = sizeof(Recorded_Primitive);
result.kind = I_Type_Kind_Struct;
result.members.set_count(5);
{
Type_Info *member_type = & Type_Info_Primitive_Type;
result.members[0] = {.type=member_type, .name=strlit("type"), .offset=offsetof(Recorded_Primitive, type)};
}
{
Type_Info *member_type = & Type_Info_Location;
result.members[1] = {.type=member_type, .name=strlit("location"), .offset=offsetof(Recorded_Primitive, location), .unserialized=true};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[2] = {.type=member_type, .name=strlit("group_index"), .offset=offsetof(Recorded_Primitive, group_index)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("i32[recorded_vertex_cap]");
member_type->kind = I_Type_Kind_Array;
member_type->size = recorded_vertex_cap * Type_Info_i32.size;
member_type->array_item_type = & Type_Info_i32;
member_type->count = recorded_vertex_cap;
result.members[3] = {.type=member_type, .name=strlit("vertex_index"), .offset=offsetof(Recorded_Primitive, vertex_index)};
}
{
Type_Info *member_type = & Type_Info_Recorded_Primitive_Union;
result.members[4] = {.type=member_type, .name=strlit("data"), .offset=offsetof(Recorded_Primitive, curve), .discriminator_offset=offsetof(Recorded_Primitive, type)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Primitive;

function Type_Info *type_info_from_pointer(Recorded_Primitive*pointer){
return &Type_Info_Recorded_Primitive;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Primitive(Binary_Reader *r, Recorded_Primitive *dst){
Primitive_Type m_type = {};
{
read_binary_Primitive_Type(r, &m_type);
}
dst->type = m_type;

i32 m_group_index = {};
{
read_binary_i32(r, &m_group_index);
}
dst->group_index = m_group_index;

i32 m_vertex_index[recorded_vertex_cap] = {};
{
for_i32(i,0,recorded_vertex_cap){
read_binary_i32(r, &m_vertex_index[i]);
}
}
copy_array_dst(dst->vertex_index, m_vertex_index);


}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum Group_Vis{Vis_None,
Vis_Skeleton,
Vis_Level1,
Vis_Eyeball,
Vis_Loomis_Ball,
Vis_Hair,
Vis_Ref_Arm_Medial_Right,
Vis_Ref_Arm_Back_Bone,
Vis_Ref_Arm_Profile_Left,
Vis_Ref_Front_0,
Vis_Ref_Front_1,
Vis_Ref_Front_2,
Vis_Ref_Front_3,
Vis_Ref_Front_4,
Vis_Nose,
Vis_Mouth,
Vis_Ear,
Vis_Head_Outline,
Vis_Chin,
Vis_Cheek,
Vis_Neck_Junction,
Group_Vis_Count,
Vis_Ref_Front_Last = Vis_Ref_Front_4,
Vis_Region_First = Vis_Nose,};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:579:
function Type_Info
get_type_info_Group_Vis();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:583:
function Type_Info
get_type_info_Group_Vis(){
Type_Info result = {};
result.name = strlit("Group_Vis");
result.size = sizeof(Group_Vis);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(24);
result.enum_members[0] = {.name=strlit("Vis_None"), .value=Vis_None};
result.enum_members[1] = {.name=strlit("Vis_Skeleton"), .value=Vis_Skeleton};
result.enum_members[2] = {.name=strlit("Vis_Level1"), .value=Vis_Level1};
result.enum_members[3] = {.name=strlit("Vis_Eyeball"), .value=Vis_Eyeball};
result.enum_members[4] = {.name=strlit("Vis_Loomis_Ball"), .value=Vis_Loomis_Ball};
result.enum_members[5] = {.name=strlit("Vis_Hair"), .value=Vis_Hair};
result.enum_members[6] = {.name=strlit("Vis_Ref_Arm_Medial_Right"), .value=Vis_Ref_Arm_Medial_Right};
result.enum_members[7] = {.name=strlit("Vis_Ref_Arm_Back_Bone"), .value=Vis_Ref_Arm_Back_Bone};
result.enum_members[8] = {.name=strlit("Vis_Ref_Arm_Profile_Left"), .value=Vis_Ref_Arm_Profile_Left};
result.enum_members[9] = {.name=strlit("Vis_Ref_Front_0"), .value=Vis_Ref_Front_0};
result.enum_members[10] = {.name=strlit("Vis_Ref_Front_1"), .value=Vis_Ref_Front_1};
result.enum_members[11] = {.name=strlit("Vis_Ref_Front_2"), .value=Vis_Ref_Front_2};
result.enum_members[12] = {.name=strlit("Vis_Ref_Front_3"), .value=Vis_Ref_Front_3};
result.enum_members[13] = {.name=strlit("Vis_Ref_Front_4"), .value=Vis_Ref_Front_4};
result.enum_members[14] = {.name=strlit("Vis_Nose"), .value=Vis_Nose};
result.enum_members[15] = {.name=strlit("Vis_Mouth"), .value=Vis_Mouth};
result.enum_members[16] = {.name=strlit("Vis_Ear"), .value=Vis_Ear};
result.enum_members[17] = {.name=strlit("Vis_Head_Outline"), .value=Vis_Head_Outline};
result.enum_members[18] = {.name=strlit("Vis_Chin"), .value=Vis_Chin};
result.enum_members[19] = {.name=strlit("Vis_Cheek"), .value=Vis_Cheek};
result.enum_members[20] = {.name=strlit("Vis_Neck_Junction"), .value=Vis_Neck_Junction};
result.enum_members[21] = {.name=strlit("Group_Vis_Count"), .value=Group_Vis_Count};
result.enum_members[22] = {.name=strlit("Vis_Ref_Front_Last"), .value=Vis_Ref_Front_Last};
result.enum_members[23] = {.name=strlit("Vis_Region_First"), .value=Vis_Region_First};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Group_Vis;

function Type_Info *type_info_from_pointer(Group_Vis*pointer){
return &Type_Info_Group_Vis;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:607:
function void
read_binary_Group_Vis(Binary_Reader *r, Group_Vis *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:612:
function void
read_binary_Group_Vis(Binary_Reader *r, Group_Vis *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Group_Vis*)(&integer);
}
static_assert( sizeof(Group_Vis) <= sizeof(i32) );

#endif
;
struct Group_Cam_Vis{
b32 active;
v3 normal;
v1 min_alignment;
b32 symmetric;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Group_Cam_Vis(){
Type_Info result = {};
result.name = strlit("Group_Cam_Vis");
result.size = sizeof(Group_Cam_Vis);
result.kind = I_Type_Kind_Struct;
result.members.set_count(4);
{
Type_Info *member_type = & Type_Info_b32;
result.members[0] = {.type=member_type, .name=strlit("active"), .offset=offsetof(Group_Cam_Vis, active)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[1] = {.type=member_type, .name=strlit("normal"), .offset=offsetof(Group_Cam_Vis, normal)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[2] = {.type=member_type, .name=strlit("min_alignment"), .offset=offsetof(Group_Cam_Vis, min_alignment)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[3] = {.type=member_type, .name=strlit("symmetric"), .offset=offsetof(Group_Cam_Vis, symmetric)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Group_Cam_Vis;

function Type_Info *type_info_from_pointer(Group_Cam_Vis*pointer){
return &Type_Info_Group_Cam_Vis;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Group_Cam_Vis(Binary_Reader *r, Group_Cam_Vis *dst){
b32 m_active = {};
{
read_binary_b32(r, &m_active);
}
dst->active = m_active;

v3 m_normal = {};
{
read_binary_v3(r, &m_normal);
}
dst->normal = m_normal;

v1 m_min_alignment = {};
{
read_binary_v1(r, &m_min_alignment);
}
dst->min_alignment = m_min_alignment;

b32 m_symmetric = {};
{
read_binary_b32(r, &m_symmetric);
}
dst->symmetric = m_symmetric;


}
#endif
;
struct Recorded_Group{
i32 parent_index;
Location location;
Paint_Params params;
u32 changed_mask;
Group_Vis vis_tag;
Group_Cam_Vis cam_vis;
b32 one_sided;
Bone_ID bone_id;
v3 view_center;
Bone_ID view_bone;
b32 params_frozen;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Recorded_Group(){
Type_Info result = {};
result.name = strlit("Recorded_Group");
result.size = sizeof(Recorded_Group);
result.kind = I_Type_Kind_Struct;
result.members.set_count(11);
{
Type_Info *member_type = & Type_Info_i32;
result.members[0] = {.type=member_type, .name=strlit("parent_index"), .offset=offsetof(Recorded_Group, parent_index)};
}
{
Type_Info *member_type = & Type_Info_Location;
result.members[1] = {.type=member_type, .name=strlit("location"), .offset=offsetof(Recorded_Group, location), .unserialized=true};
}
{
Type_Info *member_type = & Type_Info_Paint_Params;
result.members[2] = {.type=member_type, .name=strlit("params"), .offset=offsetof(Recorded_Group, params)};
}
{
Type_Info *member_type = & Type_Info_u32;
result.members[3] = {.type=member_type, .name=strlit("changed_mask"), .offset=offsetof(Recorded_Group, changed_mask)};
}
{
Type_Info *member_type = & Type_Info_Group_Vis;
result.members[4] = {.type=member_type, .name=strlit("vis_tag"), .offset=offsetof(Recorded_Group, vis_tag)};
}
{
Type_Info *member_type = & Type_Info_Group_Cam_Vis;
result.members[5] = {.type=member_type, .name=strlit("cam_vis"), .offset=offsetof(Recorded_Group, cam_vis)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[6] = {.type=member_type, .name=strlit("one_sided"), .offset=offsetof(Recorded_Group, one_sided)};
}
{
Type_Info *member_type = & Type_Info_Bone_ID;
result.members[7] = {.type=member_type, .name=strlit("bone_id"), .offset=offsetof(Recorded_Group, bone_id)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[8] = {.type=member_type, .name=strlit("view_center"), .offset=offsetof(Recorded_Group, view_center)};
}
{
Type_Info *member_type = & Type_Info_Bone_ID;
result.members[9] = {.type=member_type, .name=strlit("view_bone"), .offset=offsetof(Recorded_Group, view_bone)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[10] = {.type=member_type, .name=strlit("params_frozen"), .offset=offsetof(Recorded_Group, params_frozen), .unserialized=true};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Recorded_Group;

function Type_Info *type_info_from_pointer(Recorded_Group*pointer){
return &Type_Info_Recorded_Group;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Recorded_Group(Binary_Reader *r, Recorded_Group *dst){
i32 m_parent_index = {};
{
read_binary_i32(r, &m_parent_index);
}
dst->parent_index = m_parent_index;

Paint_Params m_params = {};
{
read_binary_Paint_Params(r, &m_params);
}
dst->params = m_params;

u32 m_changed_mask = {};
{
read_binary_u32(r, &m_changed_mask);
}
dst->changed_mask = m_changed_mask;

Group_Vis m_vis_tag = {};
{
read_binary_Group_Vis(r, &m_vis_tag);
}
dst->vis_tag = m_vis_tag;

Group_Cam_Vis m_cam_vis = {};
{
read_binary_Group_Cam_Vis(r, &m_cam_vis);
}
dst->cam_vis = m_cam_vis;

b32 m_one_sided = {};
{
read_binary_b32(r, &m_one_sided);
}
dst->one_sided = m_one_sided;

Bone_ID m_bone_id = {};
{
read_binary_Bone_ID(r, &m_bone_id);
}
dst->bone_id = m_bone_id;

v3 m_view_center = {};
{
read_binary_v3(r, &m_view_center);
}
dst->view_center = m_view_center;

Bone_ID m_view_bone = {};
{
read_binary_Bone_ID(r, &m_view_bone);
}
dst->view_bone = m_view_bone;


}
#endif
;
struct Document_File{
darray(Recorded_Vertex) vertices;
darray(Recorded_Group) groups;
darray(Recorded_Primitive) primitives;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Document_File(){
Type_Info result = {};
result.name = strlit("Document_File");
result.size = sizeof(Document_File);
result.kind = I_Type_Kind_Struct;
result.members.set_count(3);
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("darray(Recorded_Vertex)");
member_type->kind = I_Type_Kind_Darray;
member_type->size = sizeof(darray(Recorded_Vertex));
member_type->array_item_type = & Type_Info_Recorded_Vertex;
result.members[0] = {.type=member_type, .name=strlit("vertices"), .offset=offsetof(Document_File, vertices)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("darray(Recorded_Group)");
member_type->kind = I_Type_Kind_Darray;
member_type->size = sizeof(darray(Recorded_Group));
member_type->array_item_type = & Type_Info_Recorded_Group;
result.members[1] = {.type=member_type, .name=strlit("groups"), .offset=offsetof(Document_File, groups)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("darray(Recorded_Primitive)");
member_type->kind = I_Type_Kind_Darray;
member_type->size = sizeof(darray(Recorded_Primitive));
member_type->array_item_type = & Type_Info_Recorded_Primitive;
result.members[2] = {.type=member_type, .name=strlit("primitives"), .offset=offsetof(Document_File, primitives)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Document_File;

function Type_Info *type_info_from_pointer(Document_File*pointer){
return &Type_Info_Document_File;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Document_File(Binary_Reader *r, Document_File *dst){

}
#endif
;

