//NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp:1432:
// NOTE Source template: C:\Users\vodan\4ed\code\game\basic_types.kh

 function void
  read_binary_String(Binary_Reader *r, String *dst)
 {
  read_binary_size(r, sizeof(u32), &dst->count);
  
  dst->str = r->pos;
  
  if(r->end_pos - r->pos < isize(dst->count)){
   r->ok = false;
  }
  if(r->ok){
   r->pos += dst->count;
  }
 }
 
   myinline void
   read_binary_v1(Binary_Reader *r, v1 *dst)
  {
   read_binary_size(r, sizeof(v1), dst);
  }
  
  myinline v1
   read_binary_v1(Binary_Reader *r)
  {
   v1 dst;
   read_binary_size(r, sizeof(v1), &dst);
   return dst;
  }
   myinline void
   read_binary_v2(Binary_Reader *r, v2 *dst)
  {
   read_binary_size(r, sizeof(v2), dst);
  }
  
  myinline v2
   read_binary_v2(Binary_Reader *r)
  {
   v2 dst;
   read_binary_size(r, sizeof(v2), &dst);
   return dst;
  }
   myinline void
   read_binary_v3(Binary_Reader *r, v3 *dst)
  {
   read_binary_size(r, sizeof(v3), dst);
  }
  
  myinline v3
   read_binary_v3(Binary_Reader *r)
  {
   v3 dst;
   read_binary_size(r, sizeof(v3), &dst);
   return dst;
  }
   myinline void
   read_binary_v4(Binary_Reader *r, v4 *dst)
  {
   read_binary_size(r, sizeof(v4), dst);
  }
  
  myinline v4
   read_binary_v4(Binary_Reader *r)
  {
   v4 dst;
   read_binary_size(r, sizeof(v4), &dst);
   return dst;
  }
   myinline void
   read_binary_i1(Binary_Reader *r, i1 *dst)
  {
   read_binary_size(r, sizeof(i1), dst);
  }
  
  myinline i1
   read_binary_i1(Binary_Reader *r)
  {
   i1 dst;
   read_binary_size(r, sizeof(i1), &dst);
   return dst;
  }
   myinline void
   read_binary_i2(Binary_Reader *r, i2 *dst)
  {
   read_binary_size(r, sizeof(i2), dst);
  }
  
  myinline i2
   read_binary_i2(Binary_Reader *r)
  {
   i2 dst;
   read_binary_size(r, sizeof(i2), &dst);
   return dst;
  }
   myinline void
   read_binary_i3(Binary_Reader *r, i3 *dst)
  {
   read_binary_size(r, sizeof(i3), dst);
  }
  
  myinline i3
   read_binary_i3(Binary_Reader *r)
  {
   i3 dst;
   read_binary_size(r, sizeof(i3), &dst);
   return dst;
  }
   myinline void
   read_binary_i4(Binary_Reader *r, i4 *dst)
  {
   read_binary_size(r, sizeof(i4), dst);
  }
  
  myinline i4
   read_binary_i4(Binary_Reader *r)
  {
   i4 dst;
   read_binary_size(r, sizeof(i4), &dst);
   return dst;
  }
   myinline void
   read_binary_u32(Binary_Reader *r, u32 *dst)
  {
   read_binary_size(r, sizeof(u32), dst);
  }
  
  myinline u32
   read_binary_u32(Binary_Reader *r)
  {
   u32 dst;
   read_binary_size(r, sizeof(u32), &dst);
   return dst;
  }
   myinline void
   read_binary_u64(Binary_Reader *r, u64 *dst)
  {
   read_binary_size(r, sizeof(u64), dst);
  }
  
  myinline u64
   read_binary_u64(Binary_Reader *r)
  {
   u64 dst;
   read_binary_size(r, sizeof(u64), &dst);
   return dst;
  }
 
