//NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp:1810:
// NOTE: source: C:\Users\vodan\4ed\code\game\basic_types.kh






 enum Basic_Type
 {
  Basic_Type_None = 0,
     Basic_Type_v1,
     Basic_Type_v2,
     Basic_Type_v3,
     Basic_Type_v4,
     Basic_Type_i1,
     Basic_Type_i2,
     Basic_Type_i3,
     Basic_Type_i4,
     Basic_Type_String,
     Basic_Type_u32,
     Basic_Type_u64,
  
  Basic_Type_Count,
 };
 
   function Basic_Type
   basic_type_from_pointer(v1 *pointer)
  {
   return Basic_Type_v1;
  }
   function Basic_Type
   basic_type_from_pointer(v2 *pointer)
  {
   return Basic_Type_v2;
  }
   function Basic_Type
   basic_type_from_pointer(v3 *pointer)
  {
   return Basic_Type_v3;
  }
   function Basic_Type
   basic_type_from_pointer(v4 *pointer)
  {
   return Basic_Type_v4;
  }
   function Basic_Type
   basic_type_from_pointer(i1 *pointer)
  {
   return Basic_Type_i1;
  }
   function Basic_Type
   basic_type_from_pointer(i2 *pointer)
  {
   return Basic_Type_i2;
  }
   function Basic_Type
   basic_type_from_pointer(i3 *pointer)
  {
   return Basic_Type_i3;
  }
   function Basic_Type
   basic_type_from_pointer(i4 *pointer)
  {
   return Basic_Type_i4;
  }
   function Basic_Type
   basic_type_from_pointer(String *pointer)
  {
   return Basic_Type_String;
  }
   function Basic_Type
   basic_type_from_pointer(u32 *pointer)
  {
   return Basic_Type_u32;
  }
   function Basic_Type
   basic_type_from_pointer(u64 *pointer)
  {
   return Basic_Type_u64;
  }
 





