//NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp:1810:
// NOTE: source: C:\Users\vodan\4ed\code\game\driver_animate.kc

function void
movie_shot_blinking(Movie_Shot *shot){
aset(teye_phi2, 3);
arest(8);
aset(teye_phi2, -2);
arest(1);
aset(teye_phi2, -3);
arest(4);
aset(tblink, 1);
arest(1);
aset(tblink, 6);
arest(1);
aset(tblink, 6);
arest(1);
aset(tblink, 1);
aset(teye_phi2, 0);
arest(1);
aset(tblink, 0);
arest(12);
}
function void
movie_shot_arm(Movie_Shot *shot){
asetf(tarm_abduct, 0.0211f);
if(ReadSlider(i1, 0)){
aset(tarm_bend, 11);
}
arest(6);
}
function void
blink_2_frames(Movie_Shot *shot){
aset(tblink, 1);
arest(1);
aset(tblink, 6);
arest(1);
}
function void
open_eyes(Movie_Shot *shot){
aset(tblink, 0);
}
function void
movie_shot_head_tilt(Movie_Shot *shot){
{
aset(thead_phi2, 0);
arest(2);
blink_2_frames(shot);
aset(thead_phi2, 1);
arest(1);
aset(thead_phi2, -6);
open_eyes(shot);
arest(6);
}
{
aset(thead_theta2, -1);
arest(1);
aset(thead_theta2, -2);
arest(6);
blink_2_frames(shot);
}
{
aset(thead_phi2, -8);
aset(thead_theta2, -3);
arest(1);
aset(thead_phi2, -7);
aset(thead_theta2, 0);
arest(1);
aset(thead_phi2, 4);
open_eyes(shot);
arest(1);
}
aset(thead_phi2, 6);
arest(8);
}
