// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp
// NOTE: source: C:\Users\vodan\4ed\code\game\framework_driver_shared.kh

typedef u32 argb;
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:636:
function Type_Info
get_type_info_argb();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:640:
function Type_Info
get_type_info_argb(){
Type_Info result = Type_Info_u32;
result.name = strlit("argb");
return result;

}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_argb;

#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:653:
function void
read_binary_argb(Binary_Reader *r, argb *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:658:
function void
read_binary_argb(Binary_Reader *r, argb *dst){
read_binary_u32(r, dst);
}
#endif
;
typedef i1 b32;
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:636:
function Type_Info
get_type_info_b32();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:640:
function Type_Info
get_type_info_b32(){
Type_Info result = Type_Info_i1;
result.name = strlit("b32");
return result;

}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_b32;

#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:653:
function void
read_binary_b32(Binary_Reader *r, b32 *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:658:
function void
read_binary_b32(Binary_Reader *r, b32 *dst){
read_binary_i1(r, dst);
}
#endif
;

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum Bone_Type{Bone_Invalid = -1,
Bone_None = 0,
Bone_Head = 1,
Bone_Arm = 2,
Bone_Forearm = 3,
Bone_Bottom_Phalanx = 4,
Bone_Mid_Phalanx = 5,
Bone_Top_Phalanx = 6,
Bone_Torso = 7,
Bone_References = 8,
Bone_Hand = 9,
Bone_Thumb = 10,
Bone_Pelvis = 11,
Bone_Eyeball = 12,
Bone_Test = 13,
Bone_Camera = 14,};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:579:
function Type_Info
get_type_info_Bone_Type();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:583:
function Type_Info
get_type_info_Bone_Type(){
Type_Info result = {};
result.name = strlit("Bone_Type");
result.size = sizeof(Bone_Type);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(16);
result.enum_members[0] = {.name=strlit("Bone_Invalid"), .value=Bone_Invalid};
result.enum_members[1] = {.name=strlit("Bone_None"), .value=Bone_None};
result.enum_members[2] = {.name=strlit("Bone_Head"), .value=Bone_Head};
result.enum_members[3] = {.name=strlit("Bone_Arm"), .value=Bone_Arm};
result.enum_members[4] = {.name=strlit("Bone_Forearm"), .value=Bone_Forearm};
result.enum_members[5] = {.name=strlit("Bone_Bottom_Phalanx"), .value=Bone_Bottom_Phalanx};
result.enum_members[6] = {.name=strlit("Bone_Mid_Phalanx"), .value=Bone_Mid_Phalanx};
result.enum_members[7] = {.name=strlit("Bone_Top_Phalanx"), .value=Bone_Top_Phalanx};
result.enum_members[8] = {.name=strlit("Bone_Torso"), .value=Bone_Torso};
result.enum_members[9] = {.name=strlit("Bone_References"), .value=Bone_References};
result.enum_members[10] = {.name=strlit("Bone_Hand"), .value=Bone_Hand};
result.enum_members[11] = {.name=strlit("Bone_Thumb"), .value=Bone_Thumb};
result.enum_members[12] = {.name=strlit("Bone_Pelvis"), .value=Bone_Pelvis};
result.enum_members[13] = {.name=strlit("Bone_Eyeball"), .value=Bone_Eyeball};
result.enum_members[14] = {.name=strlit("Bone_Test"), .value=Bone_Test};
result.enum_members[15] = {.name=strlit("Bone_Camera"), .value=Bone_Camera};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Bone_Type;

function Type_Info *type_info_from_pointer(Bone_Type*pointer){
return &Type_Info_Bone_Type;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:607:
function void
read_binary_Bone_Type(Binary_Reader *r, Bone_Type *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:612:
function void
read_binary_Bone_Type(Binary_Reader *r, Bone_Type *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Bone_Type*)(&integer);
}
static_assert( sizeof(Bone_Type) <= sizeof(i32) );

#endif
;

struct Bone_ID{
Bone_Type type;
i32 id;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Bone_ID(){
Type_Info result = {};
result.name = strlit("Bone_ID");
result.size = sizeof(Bone_ID);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_Bone_Type;
result.members[0] = {.type=member_type, .name=strlit("type"), .offset=offsetof(Bone_ID, type)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[1] = {.type=member_type, .name=strlit("id"), .offset=offsetof(Bone_ID, id)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Bone_ID;

function Type_Info *type_info_from_pointer(Bone_ID*pointer){
return &Type_Info_Bone_ID;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Bone_ID(Binary_Reader *r, Bone_ID *dst){
Bone_Type m_type = {};
{
read_binary_Bone_Type(r, &m_type);
}
dst->type = m_type;

i32 m_id = {};
{
read_binary_i32(r, &m_id);
}
dst->id = m_id;


}
#endif
;


// C:\Users\vodan\4ed\code\meta\meta_print.cpp:698:
struct tdim
{
v1 v;
myinline operator v1(){ return v; }
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:727:
function Type_Info
get_type_info_tdim(){
Type_Info result = {};
result.name = strlit("tdim");
result.size = sizeof(tdim);
result.kind = I_Type_Kind_Wrapper;
result.constructor = strcode(mkdim);
result.wrapped_type = type_info_of(v1);
result.members.set_count(1);
{
Type_Info *member_type = & Type_Info_v1;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(tdim, v)};
}
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_tdim;

function Type_Info *type_info_from_pointer(tdim*pointer){
return &Type_Info_tdim;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:749:
function void
read_binary_tdim(Binary_Reader *r, tdim *dst){
read_binary_size(r, sizeof(tdim), dst);
}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:698:
struct tvert
{
union{
v3 v;
struct{v1 x,y,z;};
};
Bone_ID bone_id;
myinline operator v3(){ return v; }
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:727:
function Type_Info
get_type_info_tvert(){
Type_Info result = {};
result.name = strlit("tvert");
result.size = sizeof(tvert);
result.kind = I_Type_Kind_Wrapper;
result.constructor = strcode(mkvert);
result.wrapped_type = type_info_of(v3);
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_v3;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(tvert, v)};
}
{
Type_Info *member_type = & Type_Info_Bone_ID;
result.members[1] = {.type=member_type, .name=strlit("bone_id"), .offset=offsetof(tvert, bone_id)};
}
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_tvert;

function Type_Info *type_info_from_pointer(tvert*pointer){
return &Type_Info_tvert;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:749:
function void
read_binary_tvert(Binary_Reader *r, tvert *dst){
read_binary_size(r, sizeof(tvert), dst);
}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:698:
struct tnormal
{
union{
v3 v;
struct{v1 x,y,z;};
};
myinline operator v3(){ return v; }
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:727:
function Type_Info
get_type_info_tnormal(){
Type_Info result = {};
result.name = strlit("tnormal");
result.size = sizeof(tnormal);
result.kind = I_Type_Kind_Wrapper;
result.constructor = strcode(mk_normal);
result.wrapped_type = type_info_of(v3);
result.members.set_count(1);
{
Type_Info *member_type = & Type_Info_v3;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(tnormal, v)};
}
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_tnormal;

function Type_Info *type_info_from_pointer(tnormal*pointer){
return &Type_Info_tnormal;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:749:
function void
read_binary_tnormal(Binary_Reader *r, tnormal *dst){
read_binary_size(r, sizeof(tnormal), dst);
}
#endif
;




typedef u32 Line_Flags;
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:636:
function Type_Info
get_type_info_Line_Flags();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:640:
function Type_Info
get_type_info_Line_Flags(){
Type_Info result = Type_Info_u32;
result.name = strlit("Line_Flags");
return result;

}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Line_Flags;

#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:653:
function void
read_binary_Line_Flags(Binary_Reader *r, Line_Flags *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:658:
function void
read_binary_Line_Flags(Binary_Reader *r, Line_Flags *dst){
read_binary_u32(r, dst);
}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum {Line_Overlay = 0x1,
Line_Straight = 0x2,
Line_No_SymX = 0x4,
Line_Invisible = 0x8,};
;

typedef u32 FLP_Flags;
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:636:
function Type_Info
get_type_info_FLP_Flags();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:640:
function Type_Info
get_type_info_FLP_Flags(){
Type_Info result = Type_Info_u32;
result.name = strlit("FLP_Flags");
return result;

}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_FLP_Flags;

#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:653:
function void
read_binary_FLP_Flags(Binary_Reader *r, FLP_Flags *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:658:
function void
read_binary_FLP_Flags(Binary_Reader *r, FLP_Flags *dst){
read_binary_u32(r, dst);
}
#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum {};
;






struct Camera_Data{
v1 distance;
v1 theta;
v1 phi;
v1 roll;
v3 pivot;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Camera_Data(){
Type_Info result = {};
result.name = strlit("Camera_Data");
result.size = sizeof(Camera_Data);
result.kind = I_Type_Kind_Struct;
result.members.set_count(5);
{
Type_Info *member_type = & Type_Info_v1;
result.members[0] = {.type=member_type, .name=strlit("distance"), .offset=offsetof(Camera_Data, distance)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[1] = {.type=member_type, .name=strlit("theta"), .offset=offsetof(Camera_Data, theta)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[2] = {.type=member_type, .name=strlit("phi"), .offset=offsetof(Camera_Data, phi)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[3] = {.type=member_type, .name=strlit("roll"), .offset=offsetof(Camera_Data, roll)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[4] = {.type=member_type, .name=strlit("pivot"), .offset=offsetof(Camera_Data, pivot)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Camera_Data;

function Type_Info *type_info_from_pointer(Camera_Data*pointer){
return &Type_Info_Camera_Data;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Camera_Data(Binary_Reader *r, Camera_Data *dst){
v1 m_distance = {};
{
read_binary_v1(r, &m_distance);
}
dst->distance = m_distance;

v1 m_theta = {};
{
read_binary_v1(r, &m_theta);
}
dst->theta = m_theta;

v1 m_phi = {};
{
read_binary_v1(r, &m_phi);
}
dst->phi = m_phi;

v1 m_roll = {};
{
read_binary_v1(r, &m_roll);
}
dst->roll = m_roll;

v3 m_pivot = {};
{
read_binary_v3(r, &m_pivot);
}
dst->pivot = m_pivot;


}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:670:
#define Camera_Data_Embed \
 struct\
{\
v1 distance;\
v1 theta;\
v1 phi;\
v1 roll;\
v3 pivot;\
\
};\
;

struct Fill_Flags{
u32 v;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Fill_Flags(){
Type_Info result = {};
result.name = strlit("Fill_Flags");
result.size = sizeof(Fill_Flags);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
Type_Info *member_type = & Type_Info_u32;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(Fill_Flags, v)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Fill_Flags;

function Type_Info *type_info_from_pointer(Fill_Flags*pointer){
return &Type_Info_Fill_Flags;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Fill_Flags(Binary_Reader *r, Fill_Flags *dst){
u32 m_v = {};
{
read_binary_u32(r, &m_v);
}
dst->v = m_v;


}
#endif
;
struct Fill_Params{
argb color;
Fill_Flags flags;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Fill_Params(){
Type_Info result = {};
result.name = strlit("Fill_Params");
result.size = sizeof(Fill_Params);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_argb;
result.members[0] = {.type=member_type, .name=strlit("color"), .offset=offsetof(Fill_Params, color)};
}
{
Type_Info *member_type = & Type_Info_Fill_Flags;
result.members[1] = {.type=member_type, .name=strlit("flags"), .offset=offsetof(Fill_Params, flags)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Fill_Params;

function Type_Info *type_info_from_pointer(Fill_Params*pointer){
return &Type_Info_Fill_Params;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Fill_Params(Binary_Reader *r, Fill_Params *dst){
argb m_color = {};
{
read_binary_argb(r, &m_color);
}
dst->color = m_color;

Fill_Flags m_flags = {};
{
read_binary_Fill_Flags(r, &m_flags);
}
dst->flags = m_flags;


}
#endif
;
struct Line_Params{
v4 radii;
v4 lightness_additions;
Line_Flags flags;
v1 alignment_min;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Line_Params(){
Type_Info result = {};
result.name = strlit("Line_Params");
result.size = sizeof(Line_Params);
result.kind = I_Type_Kind_Struct;
result.members.set_count(4);
{
Type_Info *member_type = & Type_Info_v4;
result.members[0] = {.type=member_type, .name=strlit("radii"), .offset=offsetof(Line_Params, radii)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[1] = {.type=member_type, .name=strlit("lightness_additions"), .offset=offsetof(Line_Params, lightness_additions)};
}
{
Type_Info *member_type = & Type_Info_Line_Flags;
result.members[2] = {.type=member_type, .name=strlit("flags"), .offset=offsetof(Line_Params, flags)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[3] = {.type=member_type, .name=strlit("alignment_min"), .offset=offsetof(Line_Params, alignment_min)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Line_Params;

function Type_Info *type_info_from_pointer(Line_Params*pointer){
return &Type_Info_Line_Params;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Line_Params(Binary_Reader *r, Line_Params *dst){
v4 m_radii = {};
{
read_binary_v4(r, &m_radii);
}
dst->radii = m_radii;

v4 m_lightness_additions = {};
{
read_binary_v4(r, &m_lightness_additions);
}
dst->lightness_additions = m_lightness_additions;

Line_Flags m_flags = {};
{
read_binary_Line_Flags(r, &m_flags);
}
dst->flags = m_flags;

v1 m_alignment_min = {};
{
read_binary_v1(r, &m_alignment_min);
}
dst->alignment_min = m_alignment_min;


}
#endif
;
struct Paint_Params{
b32 painting;
Line_Params line;
Fill_Params fill;
v1 radius_mult;
v1 nslice_per_meter;
argb line_color;
v1 line_depth_offset;
v1 fill_depth_offset;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Paint_Params(){
Type_Info result = {};
result.name = strlit("Paint_Params");
result.size = sizeof(Paint_Params);
result.kind = I_Type_Kind_Struct;
result.members.set_count(8);
{
Type_Info *member_type = & Type_Info_b32;
result.members[0] = {.type=member_type, .name=strlit("painting"), .offset=offsetof(Paint_Params, painting)};
}
{
Type_Info *member_type = & Type_Info_Line_Params;
result.members[1] = {.type=member_type, .name=strlit("line"), .offset=offsetof(Paint_Params, line)};
}
{
Type_Info *member_type = & Type_Info_Fill_Params;
result.members[2] = {.type=member_type, .name=strlit("fill"), .offset=offsetof(Paint_Params, fill)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[3] = {.type=member_type, .name=strlit("radius_mult"), .offset=offsetof(Paint_Params, radius_mult)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[4] = {.type=member_type, .name=strlit("nslice_per_meter"), .offset=offsetof(Paint_Params, nslice_per_meter)};
}
{
Type_Info *member_type = & Type_Info_argb;
result.members[5] = {.type=member_type, .name=strlit("line_color"), .offset=offsetof(Paint_Params, line_color)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[6] = {.type=member_type, .name=strlit("line_depth_offset"), .offset=offsetof(Paint_Params, line_depth_offset)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[7] = {.type=member_type, .name=strlit("fill_depth_offset"), .offset=offsetof(Paint_Params, fill_depth_offset)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Paint_Params;

function Type_Info *type_info_from_pointer(Paint_Params*pointer){
return &Type_Info_Paint_Params;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Paint_Params(Binary_Reader *r, Paint_Params *dst){
b32 m_painting = {};
{
read_binary_b32(r, &m_painting);
}
dst->painting = m_painting;

Line_Params m_line = {};
{
read_binary_Line_Params(r, &m_line);
}
dst->line = m_line;

Fill_Params m_fill = {};
{
read_binary_Fill_Params(r, &m_fill);
}
dst->fill = m_fill;

v1 m_radius_mult = {};
{
read_binary_v1(r, &m_radius_mult);
}
dst->radius_mult = m_radius_mult;

v1 m_nslice_per_meter = {};
{
read_binary_v1(r, &m_nslice_per_meter);
}
dst->nslice_per_meter = m_nslice_per_meter;

argb m_line_color = {};
{
read_binary_argb(r, &m_line_color);
}
dst->line_color = m_line_color;

v1 m_line_depth_offset = {};
{
read_binary_v1(r, &m_line_depth_offset);
}
dst->line_depth_offset = m_line_depth_offset;

v1 m_fill_depth_offset = {};
{
read_binary_v1(r, &m_fill_depth_offset);
}
dst->fill_depth_offset = m_fill_depth_offset;


}
#endif
;

struct Bezier{
tvert e[4];
myinline operator tvert *(){ return e; };
  myinline tvert &operator[](i32 index){ return e[index]; }
 
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Bezier(){
Type_Info result = {};
result.name = strlit("Bezier");
result.size = sizeof(Bezier);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("tvert[4]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 4 * Type_Info_tvert.size;
member_type->array_item_type = & Type_Info_tvert;
member_type->count = 4;
result.members[0] = {.type=member_type, .name=strlit("e"), .offset=offsetof(Bezier, e)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Bezier;

function Type_Info *type_info_from_pointer(Bezier*pointer){
return &Type_Info_Bezier;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Bezier(Binary_Reader *r, Bezier *dst){
tvert m_e[4] = {};
{
for_i32(i,0,4){
read_binary_tvert(r, &m_e[i]);
}
}
copy_array_dst(dst->e, m_e);


}
#endif
;
struct Patch{
tvert e[4][4];
typedef tvert Array4x4[4][4];  // #stroustrup
  operator Array4x4&() { return e; }
 
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Patch(){
Type_Info result = {};
result.name = strlit("Patch");
result.size = sizeof(Patch);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
local_persist Type_Info inner_type_value;
inner_type_value = {};
inner_type_value.name = strlit("tvert[4]");
inner_type_value.kind = I_Type_Kind_Array;
inner_type_value.size = 4 * Type_Info_tvert.size;
inner_type_value.array_item_type = & Type_Info_tvert;
inner_type_value.count = 4;
member_type->name = strlit("tvert[4][4]");
member_type->kind = I_Type_Kind_Array;
member_type->size = 4 * inner_type_value.size;
member_type->array_item_type = & inner_type_value;
member_type->count = 4;
result.members[0] = {.type=member_type, .name=strlit("e"), .offset=offsetof(Patch, e)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Patch;

function Type_Info *type_info_from_pointer(Patch*pointer){
return &Type_Info_Patch;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Patch(Binary_Reader *r, Patch *dst){
tvert m_e[4][4] = {};
{
for_i32(i,0,4){
for_i32(j,0,4){
read_binary_tvert(r, &m_e[i][j]);
}}
}
copy_array_dst(dst->e, m_e);


}
#endif
;

struct Range_i16{
i16 min;
i16 max;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Range_i16(){
Type_Info result = {};
result.name = strlit("Range_i16");
result.size = sizeof(Range_i16);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_i16;
result.members[0] = {.type=member_type, .name=strlit("min"), .offset=offsetof(Range_i16, min)};
}
{
Type_Info *member_type = & Type_Info_i16;
result.members[1] = {.type=member_type, .name=strlit("max"), .offset=offsetof(Range_i16, max)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Range_i16;

function Type_Info *type_info_from_pointer(Range_i16*pointer){
return &Type_Info_Range_i16;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Range_i16(Binary_Reader *r, Range_i16 *dst){
i16 m_min = {};
{
read_binary_i16(r, &m_min);
}
dst->min = m_min;

i16 m_max = {};
{
read_binary_i16(r, &m_max);
}
dst->max = m_max;


}
#endif
;
struct FUI_File{
i16 is_driver;
i16 index;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_FUI_File(){
Type_Info result = {};
result.name = strlit("FUI_File");
result.size = sizeof(FUI_File);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_i16;
result.members[0] = {.type=member_type, .name=strlit("is_driver"), .offset=offsetof(FUI_File, is_driver)};
}
{
Type_Info *member_type = & Type_Info_i16;
result.members[1] = {.type=member_type, .name=strlit("index"), .offset=offsetof(FUI_File, index)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_FUI_File;

function Type_Info *type_info_from_pointer(FUI_File*pointer){
return &Type_Info_FUI_File;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_FUI_File(Binary_Reader *r, FUI_File *dst){
i16 m_is_driver = {};
{
read_binary_i16(r, &m_is_driver);
}
dst->is_driver = m_is_driver;

i16 m_index = {};
{
read_binary_i16(r, &m_index);
}
dst->index = m_index;


}
#endif
;
struct Location{
FUI_File file;
Range_i16 range;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Location(){
Type_Info result = {};
result.name = strlit("Location");
result.size = sizeof(Location);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_FUI_File;
result.members[0] = {.type=member_type, .name=strlit("file"), .offset=offsetof(Location, file)};
}
{
Type_Info *member_type = & Type_Info_Range_i16;
result.members[1] = {.type=member_type, .name=strlit("range"), .offset=offsetof(Location, range)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Location;

function Type_Info *type_info_from_pointer(Location*pointer){
return &Type_Info_Location;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Location(Binary_Reader *r, Location *dst){
FUI_File m_file = {};
{
read_binary_FUI_File(r, &m_file);
}
dst->file = m_file;

Range_i16 m_range = {};
{
read_binary_Range_i16(r, &m_range);
}
dst->range = m_range;


}
#endif
;

struct FUI_Line_Params{
FLP_Flags fui_flags;
v4 radii;
v4 lightness_additions;
Line_Flags line_flags;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_FUI_Line_Params(){
Type_Info result = {};
result.name = strlit("FUI_Line_Params");
result.size = sizeof(FUI_Line_Params);
result.kind = I_Type_Kind_Struct;
result.members.set_count(4);
{
Type_Info *member_type = & Type_Info_FLP_Flags;
result.members[0] = {.type=member_type, .name=strlit("fui_flags"), .offset=offsetof(FUI_Line_Params, fui_flags)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[1] = {.type=member_type, .name=strlit("radii"), .offset=offsetof(FUI_Line_Params, radii)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[2] = {.type=member_type, .name=strlit("lightness_additions"), .offset=offsetof(FUI_Line_Params, lightness_additions)};
}
{
Type_Info *member_type = & Type_Info_Line_Flags;
result.members[3] = {.type=member_type, .name=strlit("line_flags"), .offset=offsetof(FUI_Line_Params, line_flags)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_FUI_Line_Params;

function Type_Info *type_info_from_pointer(FUI_Line_Params*pointer){
return &Type_Info_FUI_Line_Params;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_FUI_Line_Params(Binary_Reader *r, FUI_Line_Params *dst){
FLP_Flags m_fui_flags = {};
{
read_binary_FLP_Flags(r, &m_fui_flags);
}
dst->fui_flags = m_fui_flags;

v4 m_radii = {};
{
read_binary_v4(r, &m_radii);
}
dst->radii = m_radii;

v4 m_lightness_additions = {};
{
read_binary_v4(r, &m_lightness_additions);
}
dst->lightness_additions = m_lightness_additions;

Line_Flags m_line_flags = {};
{
read_binary_Line_Flags(r, &m_line_flags);
}
dst->line_flags = m_line_flags;


}
#endif
;

struct Reference_Placement{
v3 center;
v3 x_axis;
v1 alpha;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Reference_Placement(){
Type_Info result = {};
result.name = strlit("Reference_Placement");
result.size = sizeof(Reference_Placement);
result.kind = I_Type_Kind_Struct;
result.members.set_count(3);
{
Type_Info *member_type = & Type_Info_v3;
result.members[0] = {.type=member_type, .name=strlit("center"), .offset=offsetof(Reference_Placement, center)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[1] = {.type=member_type, .name=strlit("x_axis"), .offset=offsetof(Reference_Placement, x_axis)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[2] = {.type=member_type, .name=strlit("alpha"), .offset=offsetof(Reference_Placement, alpha)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Reference_Placement;

function Type_Info *type_info_from_pointer(Reference_Placement*pointer){
return &Type_Info_Reference_Placement;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Reference_Placement(Binary_Reader *r, Reference_Placement *dst){
v3 m_center = {};
{
read_binary_v3(r, &m_center);
}
dst->center = m_center;

v3 m_x_axis = {};
{
read_binary_v3(r, &m_x_axis);
}
dst->x_axis = m_x_axis;

v1 m_alpha = {};
{
read_binary_v1(r, &m_alpha);
}
dst->alpha = m_alpha;


}
#endif
;

struct Reference_Mesh_Placement{
v3 center;
v1 scale;
v3 rotation;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Reference_Mesh_Placement(){
Type_Info result = {};
result.name = strlit("Reference_Mesh_Placement");
result.size = sizeof(Reference_Mesh_Placement);
result.kind = I_Type_Kind_Struct;
result.members.set_count(3);
{
Type_Info *member_type = & Type_Info_v3;
result.members[0] = {.type=member_type, .name=strlit("center"), .offset=offsetof(Reference_Mesh_Placement, center)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[1] = {.type=member_type, .name=strlit("scale"), .offset=offsetof(Reference_Mesh_Placement, scale)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[2] = {.type=member_type, .name=strlit("rotation"), .offset=offsetof(Reference_Mesh_Placement, rotation)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Reference_Mesh_Placement;

function Type_Info *type_info_from_pointer(Reference_Mesh_Placement*pointer){
return &Type_Info_Reference_Mesh_Placement;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Reference_Mesh_Placement(Binary_Reader *r, Reference_Mesh_Placement *dst){
v3 m_center = {};
{
read_binary_v3(r, &m_center);
}
dst->center = m_center;

v1 m_scale = {};
{
read_binary_v1(r, &m_scale);
}
dst->scale = m_scale;

v3 m_rotation = {};
{
read_binary_v3(r, &m_rotation);
}
dst->rotation = m_rotation;


}
#endif
;

struct Curve{
v3 d0;
v3 d3;
v4 radii;
v4 lightness_additions;
Line_Flags line_flags;
FLP_Flags fui_flags;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Curve(){
Type_Info result = {};
result.name = strlit("Curve");
result.size = sizeof(Curve);
result.kind = I_Type_Kind_Struct;
result.members.set_count(6);
{
Type_Info *member_type = & Type_Info_v3;
result.members[0] = {.type=member_type, .name=strlit("d0"), .offset=offsetof(Curve, d0)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[1] = {.type=member_type, .name=strlit("d3"), .offset=offsetof(Curve, d3)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[2] = {.type=member_type, .name=strlit("radii"), .offset=offsetof(Curve, radii)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[3] = {.type=member_type, .name=strlit("lightness_additions"), .offset=offsetof(Curve, lightness_additions)};
}
{
Type_Info *member_type = & Type_Info_Line_Flags;
result.members[4] = {.type=member_type, .name=strlit("line_flags"), .offset=offsetof(Curve, line_flags)};
}
{
Type_Info *member_type = & Type_Info_FLP_Flags;
result.members[5] = {.type=member_type, .name=strlit("fui_flags"), .offset=offsetof(Curve, fui_flags)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Curve;

function Type_Info *type_info_from_pointer(Curve*pointer){
return &Type_Info_Curve;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Curve(Binary_Reader *r, Curve *dst){
v3 m_d0 = {};
{
read_binary_v3(r, &m_d0);
}
dst->d0 = m_d0;

v3 m_d3 = {};
{
read_binary_v3(r, &m_d3);
}
dst->d3 = m_d3;

v4 m_radii = {};
{
read_binary_v4(r, &m_radii);
}
dst->radii = m_radii;

v4 m_lightness_additions = {};
{
read_binary_v4(r, &m_lightness_additions);
}
dst->lightness_additions = m_lightness_additions;

Line_Flags m_line_flags = {};
{
read_binary_Line_Flags(r, &m_line_flags);
}
dst->line_flags = m_line_flags;

FLP_Flags m_fui_flags = {};
{
read_binary_FLP_Flags(r, &m_fui_flags);
}
dst->fui_flags = m_fui_flags;


}
#endif
;

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum Reference_Scene{Scene_None = 0,
Scene_Back = 1,
Scene_Arm_Profile = 2,
Scene_Eco_Skeleton = 3,
Scene_Head_Profile = 4,};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:579:
function Type_Info
get_type_info_Reference_Scene();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:583:
function Type_Info
get_type_info_Reference_Scene(){
Type_Info result = {};
result.name = strlit("Reference_Scene");
result.size = sizeof(Reference_Scene);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(5);
result.enum_members[0] = {.name=strlit("Scene_None"), .value=Scene_None};
result.enum_members[1] = {.name=strlit("Scene_Back"), .value=Scene_Back};
result.enum_members[2] = {.name=strlit("Scene_Arm_Profile"), .value=Scene_Arm_Profile};
result.enum_members[3] = {.name=strlit("Scene_Eco_Skeleton"), .value=Scene_Eco_Skeleton};
result.enum_members[4] = {.name=strlit("Scene_Head_Profile"), .value=Scene_Head_Profile};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Reference_Scene;

function Type_Info *type_info_from_pointer(Reference_Scene*pointer){
return &Type_Info_Reference_Scene;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:607:
function void
read_binary_Reference_Scene(Binary_Reader *r, Reference_Scene *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:612:
function void
read_binary_Reference_Scene(Binary_Reader *r, Reference_Scene *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Reference_Scene*)(&integer);
}
static_assert( sizeof(Reference_Scene) <= sizeof(i32) );

#endif
;
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:559:
enum Reference_Mode{Reference_Off = 0,
Reference_On = 1,};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:579:
function Type_Info
get_type_info_Reference_Mode();// C:\Users\vodan\4ed\code\meta\meta_print.cpp:583:
function Type_Info
get_type_info_Reference_Mode(){
Type_Info result = {};
result.name = strlit("Reference_Mode");
result.size = sizeof(Reference_Mode);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(2);
result.enum_members[0] = {.name=strlit("Reference_Off"), .value=Reference_Off};
result.enum_members[1] = {.name=strlit("Reference_On"), .value=Reference_On};
return result;
}
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Reference_Mode;

function Type_Info *type_info_from_pointer(Reference_Mode*pointer){
return &Type_Info_Reference_Mode;
}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:607:
function void
read_binary_Reference_Mode(Binary_Reader *r, Reference_Mode *dst);
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:612:
function void
read_binary_Reference_Mode(Binary_Reader *r, Reference_Mode *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Reference_Mode*)(&integer);
}
static_assert( sizeof(Reference_Mode) <= sizeof(i32) );

#endif
;


 #define poly3_inner__return void
#define poly3_inner__params Poly3 points, argb c0, argb c1, argb c2, Poly_Flags flags
  
 #define draw_bezier_inner__return void
#define draw_bezier_inner__params tvert P[4], Line_Params &params, argb base_color
  
 
 
#define framework_api_xlist_1(X) \
  X(poly3_inner) \
   X(draw_bezier_inner) \
 
 
#define framework_api_xlist_2(X) \
  X(push_object_transform_to_target) \
   X(DEBUG_send_entry) \
   X(push_image) \
   X(draw_shaded_mesh) \
 
 
#define framework_api_xlist(X) \
framework_api_xlist_1(X) \
framework_api_xlist_2(X) \
memory_functions_xlist(X)


struct Reference_Image{
Stringz filename;
Reference_Placement placement;
};
;
struct Reference_Scene_Data{
v1 camera_phi2;
v1 camera_theta2;
Reference_Image image;
Pose pose;
};
;


 #define driver_render__return void
#define driver_render__params Arena *arena, Painter *painter
  
 #define driver_update__return void
#define driver_update__params Model *model, v1 anim_time
  
 #define driver_shutdown__return void
#define driver_shutdown__params void
  
 #define driver_update_tweaks__return void
#define driver_update_tweaks__params 
  
 #define driver_get_scene_data__return Reference_Scene_Data
#define driver_get_scene_data__params Reference_Scene scene
  
 
 
#define driver_api_xlist(X) \
  X(driver_render) \
   X(driver_update) \
   X(driver_shutdown) \
   X(driver_update_tweaks) \
   X(driver_get_scene_data) \
 


struct Preset_Settings{
char name[PRESET_NAME_CAP];
i32 viz_level;
i32 reference_image;
Reference_Scene scene;
b32 show_eyeball;
b32 show_loomis_ball;
b32 show_grid;
b32 hide_hair;
b32 ignore_radii;
b32 ignore_alignment_min;
b32 show_arm_medial_right;
b32 show_arm_back_bone;
b32 show_arm_profile_left;
b32 fill_only_picking;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Preset_Settings(){
Type_Info result = {};
result.name = strlit("Preset_Settings");
result.size = sizeof(Preset_Settings);
result.kind = I_Type_Kind_Struct;
result.members.set_count(14);
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("char[PRESET_NAME_CAP]");
member_type->kind = I_Type_Kind_Array;
member_type->size = PRESET_NAME_CAP * Type_Info_char.size;
member_type->array_item_type = & Type_Info_char;
member_type->count = PRESET_NAME_CAP;
result.members[0] = {.type=member_type, .name=strlit("name"), .offset=offsetof(Preset_Settings, name)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[1] = {.type=member_type, .name=strlit("viz_level"), .offset=offsetof(Preset_Settings, viz_level)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[2] = {.type=member_type, .name=strlit("reference_image"), .offset=offsetof(Preset_Settings, reference_image)};
}
{
Type_Info *member_type = & Type_Info_Reference_Scene;
result.members[3] = {.type=member_type, .name=strlit("scene"), .offset=offsetof(Preset_Settings, scene)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[4] = {.type=member_type, .name=strlit("show_eyeball"), .offset=offsetof(Preset_Settings, show_eyeball)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[5] = {.type=member_type, .name=strlit("show_loomis_ball"), .offset=offsetof(Preset_Settings, show_loomis_ball)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[6] = {.type=member_type, .name=strlit("show_grid"), .offset=offsetof(Preset_Settings, show_grid)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[7] = {.type=member_type, .name=strlit("hide_hair"), .offset=offsetof(Preset_Settings, hide_hair)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[8] = {.type=member_type, .name=strlit("ignore_radii"), .offset=offsetof(Preset_Settings, ignore_radii)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[9] = {.type=member_type, .name=strlit("ignore_alignment_min"), .offset=offsetof(Preset_Settings, ignore_alignment_min)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[10] = {.type=member_type, .name=strlit("show_arm_medial_right"), .offset=offsetof(Preset_Settings, show_arm_medial_right)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[11] = {.type=member_type, .name=strlit("show_arm_back_bone"), .offset=offsetof(Preset_Settings, show_arm_back_bone)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[12] = {.type=member_type, .name=strlit("show_arm_profile_left"), .offset=offsetof(Preset_Settings, show_arm_profile_left)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[13] = {.type=member_type, .name=strlit("fill_only_picking"), .offset=offsetof(Preset_Settings, fill_only_picking)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Preset_Settings;

function Type_Info *type_info_from_pointer(Preset_Settings*pointer){
return &Type_Info_Preset_Settings;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Preset_Settings(Binary_Reader *r, Preset_Settings *dst){
char m_name[PRESET_NAME_CAP] = {};
{
for_i32(i,0,PRESET_NAME_CAP){
read_binary_char(r, &m_name[i]);
}
}
copy_array_dst(dst->name, m_name);

i32 m_viz_level = {};
{
read_binary_i32(r, &m_viz_level);
}
dst->viz_level = m_viz_level;

i32 m_reference_image = {};
{
read_binary_i32(r, &m_reference_image);
}
dst->reference_image = m_reference_image;

Reference_Scene m_scene = {};
{
read_binary_Reference_Scene(r, &m_scene);
}
dst->scene = m_scene;

b32 m_show_eyeball = {};
{
read_binary_b32(r, &m_show_eyeball);
}
dst->show_eyeball = m_show_eyeball;

b32 m_show_loomis_ball = {};
{
read_binary_b32(r, &m_show_loomis_ball);
}
dst->show_loomis_ball = m_show_loomis_ball;

b32 m_show_grid = {};
{
read_binary_b32(r, &m_show_grid);
}
dst->show_grid = m_show_grid;

b32 m_hide_hair = {};
{
read_binary_b32(r, &m_hide_hair);
}
dst->hide_hair = m_hide_hair;

b32 m_ignore_radii = {};
{
read_binary_b32(r, &m_ignore_radii);
}
dst->ignore_radii = m_ignore_radii;

b32 m_ignore_alignment_min = {};
{
read_binary_b32(r, &m_ignore_alignment_min);
}
dst->ignore_alignment_min = m_ignore_alignment_min;

b32 m_show_arm_medial_right = {};
{
read_binary_b32(r, &m_show_arm_medial_right);
}
dst->show_arm_medial_right = m_show_arm_medial_right;

b32 m_show_arm_back_bone = {};
{
read_binary_b32(r, &m_show_arm_back_bone);
}
dst->show_arm_back_bone = m_show_arm_back_bone;

b32 m_show_arm_profile_left = {};
{
read_binary_b32(r, &m_show_arm_profile_left);
}
dst->show_arm_profile_left = m_show_arm_profile_left;

b32 m_fill_only_picking = {};
{
read_binary_b32(r, &m_fill_only_picking);
}
dst->fill_only_picking = m_fill_only_picking;


}
#endif
;

struct Saved_Viewport{
Camera_Data target_camera;
i32 preset;
i32 last_preset;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Saved_Viewport(){
Type_Info result = {};
result.name = strlit("Saved_Viewport");
result.size = sizeof(Saved_Viewport);
result.kind = I_Type_Kind_Struct;
result.members.set_count(3);
{
Type_Info *member_type = & Type_Info_Camera_Data;
result.members[0] = {.type=member_type, .name=strlit("target_camera"), .offset=offsetof(Saved_Viewport, target_camera)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[1] = {.type=member_type, .name=strlit("preset"), .offset=offsetof(Saved_Viewport, preset)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[2] = {.type=member_type, .name=strlit("last_preset"), .offset=offsetof(Saved_Viewport, last_preset)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Saved_Viewport;

function Type_Info *type_info_from_pointer(Saved_Viewport*pointer){
return &Type_Info_Saved_Viewport;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Saved_Viewport(Binary_Reader *r, Saved_Viewport *dst){
Camera_Data m_target_camera = {};
{
read_binary_Camera_Data(r, &m_target_camera);
}
dst->target_camera = m_target_camera;

i32 m_preset = {};
{
read_binary_i32(r, &m_preset);
}
dst->preset = m_preset;

i32 m_last_preset = {};
{
read_binary_i32(r, &m_last_preset);
}
dst->last_preset = m_last_preset;


}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:670:
#define Saved_Viewport_Embed \
 struct\
{\
Camera_Data target_camera;\
i32 preset;\
i32 last_preset;\
\
};\
;
