// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp
// NOTE: source: C:\Users\vodan\4ed\code\game\framework.kh

struct Entity_Type_Info{
b32 is_curve;
};
;

struct Keyboard_Cursor{
b32 on;
v3 pos;
v1 vel;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Keyboard_Cursor(){
Type_Info result = {};
result.name = strlit("Keyboard_Cursor");
result.size = sizeof(Keyboard_Cursor);
result.kind = I_Type_Kind_Struct;
result.members.set_count(3);
{
Type_Info *member_type = & Type_Info_b32;
result.members[0] = {.type=member_type, .name=strlit("on"), .offset=offsetof(Keyboard_Cursor, on)};
}
{
Type_Info *member_type = & Type_Info_v3;
result.members[1] = {.type=member_type, .name=strlit("pos"), .offset=offsetof(Keyboard_Cursor, pos)};
}
{
Type_Info *member_type = & Type_Info_v1;
result.members[2] = {.type=member_type, .name=strlit("vel"), .offset=offsetof(Keyboard_Cursor, vel)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Keyboard_Cursor;

function Type_Info *type_info_from_pointer(Keyboard_Cursor*pointer){
return &Type_Info_Keyboard_Cursor;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Keyboard_Cursor(Binary_Reader *r, Keyboard_Cursor *dst){
b32 m_on = {};
{
read_binary_b32(r, &m_on);
}
dst->on = m_on;

v3 m_pos = {};
{
read_binary_v3(r, &m_pos);
}
dst->pos = m_pos;

v1 m_vel = {};
{
read_binary_v1(r, &m_vel);
}
dst->vel = m_vel;


}
#endif
;




struct Serialized_State{
Keyboard_Cursor kb_cursor;
Reference_Mode reference_mode;
b32 orthographic;
Saved_Viewport saved_viewports[GAME_VIEWPORT_COUNT];
Preset_Settings presets[PRESET_CAP];
i32 presets_count;
};
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:327:
function Type_Info
get_type_info_Serialized_State(){
Type_Info result = {};
result.name = strlit("Serialized_State");
result.size = sizeof(Serialized_State);
result.kind = I_Type_Kind_Struct;
result.members.set_count(6);
{
Type_Info *member_type = & Type_Info_Keyboard_Cursor;
result.members[0] = {.type=member_type, .name=strlit("kb_cursor"), .offset=offsetof(Serialized_State, kb_cursor)};
}
{
Type_Info *member_type = & Type_Info_Reference_Mode;
result.members[1] = {.type=member_type, .name=strlit("reference_mode"), .offset=offsetof(Serialized_State, reference_mode)};
}
{
Type_Info *member_type = & Type_Info_b32;
result.members[2] = {.type=member_type, .name=strlit("orthographic"), .offset=offsetof(Serialized_State, orthographic)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("Saved_Viewport[GAME_VIEWPORT_COUNT]");
member_type->kind = I_Type_Kind_Array;
member_type->size = GAME_VIEWPORT_COUNT * Type_Info_Saved_Viewport.size;
member_type->array_item_type = & Type_Info_Saved_Viewport;
member_type->count = GAME_VIEWPORT_COUNT;
result.members[3] = {.type=member_type, .name=strlit("saved_viewports"), .offset=offsetof(Serialized_State, saved_viewports)};
}
{
local_persist Type_Info member_type_value;
Type_Info *member_type = &member_type_value;
*member_type = {};
member_type->name = strlit("Preset_Settings[PRESET_CAP]");
member_type->kind = I_Type_Kind_Array;
member_type->size = PRESET_CAP * Type_Info_Preset_Settings.size;
member_type->array_item_type = & Type_Info_Preset_Settings;
member_type->count = PRESET_CAP;
result.members[4] = {.type=member_type, .name=strlit("presets"), .offset=offsetof(Serialized_State, presets)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[5] = {.type=member_type, .name=strlit("presets_count"), .offset=offsetof(Serialized_State, presets_count)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:117:
global Type_Info Type_Info_Serialized_State;

function Type_Info *type_info_from_pointer(Serialized_State*pointer){
return &Type_Info_Serialized_State;
}
#endif
#if WANT_TYPE_INFO
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:349:
function void
read_binary_Serialized_State(Binary_Reader *r, Serialized_State *dst){
Keyboard_Cursor m_kb_cursor = {};
{
read_binary_Keyboard_Cursor(r, &m_kb_cursor);
}
dst->kb_cursor = m_kb_cursor;

Reference_Mode m_reference_mode = {};
{
read_binary_Reference_Mode(r, &m_reference_mode);
}
dst->reference_mode = m_reference_mode;

b32 m_orthographic = {};
{
read_binary_b32(r, &m_orthographic);
}
dst->orthographic = m_orthographic;

Saved_Viewport m_saved_viewports[GAME_VIEWPORT_COUNT] = {};
{
for_i32(i,0,GAME_VIEWPORT_COUNT){
read_binary_Saved_Viewport(r, &m_saved_viewports[i]);
}
}
copy_array_dst(dst->saved_viewports, m_saved_viewports);

Preset_Settings m_presets[PRESET_CAP] = {};
{
for_i32(i,0,PRESET_CAP){
read_binary_Preset_Settings(r, &m_presets[i]);
}
}
copy_array_dst(dst->presets, m_presets);

i32 m_presets_count = {};
{
read_binary_i32(r, &m_presets_count);
}
dst->presets_count = m_presets_count;


}
#endif
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:670:
#define Serialized_State_Embed \
 struct\
{\
Keyboard_Cursor kb_cursor;\
Reference_Mode reference_mode;\
b32 orthographic;\
Saved_Viewport saved_viewports[GAME_VIEWPORT_COUNT];\
Preset_Settings presets[PRESET_CAP];\
i32 presets_count;\
\
};\
;

