//NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp:1489:
// NOTE: source: C:\Users\vodan\4ed\code\game\framework_driver_shared.kh

typedef u32 argb;
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:480:
function Type_Info
get_type_info_argb();//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:484:
function Type_Info
get_type_info_argb(){
Type_Info result = Type_Info_u32;
result.name = strlit("argb");
return result;

}
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_argb;

#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:497:
function void
read_binary_argb(Binary_Reader *r, argb *dst);
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:502:
function void
read_binary_argb(Binary_Reader *r, argb *dst){
read_binary_u32(r, dst);
}
#endif
;
typedef i1 b32;
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:480:
function Type_Info
get_type_info_b32();//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:484:
function Type_Info
get_type_info_b32(){
Type_Info result = Type_Info_i1;
result.name = strlit("b32");
return result;

}
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_b32;

#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:497:
function void
read_binary_b32(Binary_Reader *r, b32 *dst);
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:502:
function void
read_binary_b32(Binary_Reader *r, b32 *dst){
read_binary_i1(r, dst);
}
#endif
;
struct Vertex_Index { i32 v; };
inline b32 operator==(Vertex_Index a, Vertex_Index b){ return a.v==b.v; }
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:191:
function Type_Info
get_type_info_Vertex_Index(){
Type_Info result = {};
result.name = strlit("Vertex_Index");
result.size = sizeof(Vertex_Index);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
Type_Info *member_type = & Type_Info_i32;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(Vertex_Index, v)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Vertex_Index;

function Type_Info *type_info_from_pointer(Vertex_Index*pointer){
return &Type_Info_Vertex_Index;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:264:
function void
read_binary_Vertex_Index(Binary_Reader *r, Vertex_Index *dst){
i32 m_v = {};
{
read_binary_i32(r, &m_v);
}
dst->v = m_v;


}
#endif
;
struct Curve_Index { i32 v; };
inline b32 operator==(Curve_Index a, Curve_Index b){ return a.v==b.v; }
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:191:
function Type_Info
get_type_info_Curve_Index(){
Type_Info result = {};
result.name = strlit("Curve_Index");
result.size = sizeof(Curve_Index);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
Type_Info *member_type = & Type_Info_i32;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(Curve_Index, v)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Curve_Index;

function Type_Info *type_info_from_pointer(Curve_Index*pointer){
return &Type_Info_Curve_Index;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:264:
function void
read_binary_Curve_Index(Binary_Reader *r, Curve_Index *dst){
i32 m_v = {};
{
read_binary_i32(r, &m_v);
}
dst->v = m_v;


}
#endif
;
struct Fill_Index { i32 v; };
inline b32 operator==(Fill_Index a, Fill_Index b){ return a.v==b.v; }
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:191:
function Type_Info
get_type_info_Fill_Index(){
Type_Info result = {};
result.name = strlit("Fill_Index");
result.size = sizeof(Fill_Index);
result.kind = I_Type_Kind_Struct;
result.members.set_count(1);
{
Type_Info *member_type = & Type_Info_i32;
result.members[0] = {.type=member_type, .name=strlit("v"), .offset=offsetof(Fill_Index, v)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Fill_Index;

function Type_Info *type_info_from_pointer(Fill_Index*pointer){
return &Type_Info_Fill_Index;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:264:
function void
read_binary_Fill_Index(Binary_Reader *r, Fill_Index *dst){
i32 m_v = {};
{
read_binary_i32(r, &m_v);
}
dst->v = m_v;


}
#endif
;
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:405:
enum Bone_Type{Bone_None = 0,
Bone_Head = 1,
Bone_Arm = 2,
Bone_Forearm = 3,
Bone_Bottom_Phalanx = 4,
Bone_Mid_Phalanx = 5,
Bone_Top_Phalanx = 6,
Bone_Torso = 7,
Bone_References = 8,
Bone_Hand = 9,
Bone_Thumb = 10,
Bone_Pelvis = 11,
Bone_Eyeball = 12,
Bone_Test = 13,
Bone_Camera = 14,};
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:423:
function Type_Info
get_type_info_Bone_Type();//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:427:
function Type_Info
get_type_info_Bone_Type(){
Type_Info result = {};
result.name = strlit("Bone_Type");
result.size = sizeof(Bone_Type);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(15);
result.enum_members[0] = {.name=strlit("Bone_None"), .value=Bone_None};
result.enum_members[1] = {.name=strlit("Bone_Head"), .value=Bone_Head};
result.enum_members[2] = {.name=strlit("Bone_Arm"), .value=Bone_Arm};
result.enum_members[3] = {.name=strlit("Bone_Forearm"), .value=Bone_Forearm};
result.enum_members[4] = {.name=strlit("Bone_Bottom_Phalanx"), .value=Bone_Bottom_Phalanx};
result.enum_members[5] = {.name=strlit("Bone_Mid_Phalanx"), .value=Bone_Mid_Phalanx};
result.enum_members[6] = {.name=strlit("Bone_Top_Phalanx"), .value=Bone_Top_Phalanx};
result.enum_members[7] = {.name=strlit("Bone_Torso"), .value=Bone_Torso};
result.enum_members[8] = {.name=strlit("Bone_References"), .value=Bone_References};
result.enum_members[9] = {.name=strlit("Bone_Hand"), .value=Bone_Hand};
result.enum_members[10] = {.name=strlit("Bone_Thumb"), .value=Bone_Thumb};
result.enum_members[11] = {.name=strlit("Bone_Pelvis"), .value=Bone_Pelvis};
result.enum_members[12] = {.name=strlit("Bone_Eyeball"), .value=Bone_Eyeball};
result.enum_members[13] = {.name=strlit("Bone_Test"), .value=Bone_Test};
result.enum_members[14] = {.name=strlit("Bone_Camera"), .value=Bone_Camera};
return result;
}
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Bone_Type;

function Type_Info *type_info_from_pointer(Bone_Type*pointer){
return &Type_Info_Bone_Type;
}
#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:451:
function void
read_binary_Bone_Type(Binary_Reader *r, Bone_Type *dst);
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:456:
function void
read_binary_Bone_Type(Binary_Reader *r, Bone_Type *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Bone_Type*)(&integer);
}
static_assert( sizeof(Bone_Type) <= sizeof(i32) );

#endif
;

struct Bone_ID{
Bone_Type type;
i1 id;
};
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:191:
function Type_Info
get_type_info_Bone_ID(){
Type_Info result = {};
result.name = strlit("Bone_ID");
result.size = sizeof(Bone_ID);
result.kind = I_Type_Kind_Struct;
result.members.set_count(2);
{
Type_Info *member_type = & Type_Info_Bone_Type;
result.members[0] = {.type=member_type, .name=strlit("type"), .offset=offsetof(Bone_ID, type)};
}
{
Type_Info *member_type = & Type_Info_i1;
result.members[1] = {.type=member_type, .name=strlit("id"), .offset=offsetof(Bone_ID, id)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Bone_ID;

function Type_Info *type_info_from_pointer(Bone_ID*pointer){
return &Type_Info_Bone_ID;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:264:
function void
read_binary_Bone_ID(Binary_Reader *r, Bone_ID *dst){
Bone_Type m_type = {};
{
read_binary_Bone_Type(r, &m_type);
}
dst->type = m_type;

i1 m_id = {};
{
read_binary_i1(r, &m_id);
}
dst->id = m_id;


}
#endif
;

typedef u32 Line_Flags;
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:480:
function Type_Info
get_type_info_Line_Flags();//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:484:
function Type_Info
get_type_info_Line_Flags(){
Type_Info result = Type_Info_u32;
result.name = strlit("Line_Flags");
return result;

}
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Line_Flags;

#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:497:
function void
read_binary_Line_Flags(Binary_Reader *r, Line_Flags *dst);
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:502:
function void
read_binary_Line_Flags(Binary_Reader *r, Line_Flags *dst){
read_binary_u32(r, dst);
}
#endif
;
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:405:
enum {Line_Overlay = 1,
Line_Straight = 2,
Line_No_SymX = 4,
Line_Invisible = 8,};
;
typedef u32 FLP_Flags;
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:480:
function Type_Info
get_type_info_FLP_Flags();//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:484:
function Type_Info
get_type_info_FLP_Flags(){
Type_Info result = Type_Info_u32;
result.name = strlit("FLP_Flags");
return result;

}
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_FLP_Flags;

#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:497:
function void
read_binary_FLP_Flags(Binary_Reader *r, FLP_Flags *dst);
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:502:
function void
read_binary_FLP_Flags(Binary_Reader *r, FLP_Flags *dst){
read_binary_u32(r, dst);
}
#endif
;
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:405:
enum {};
;
struct FUI_Line_Params{
FLP_Flags fui_flags;
v4 radii;
v4 lightness_additions;
Line_Flags line_flags;
};
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:191:
function Type_Info
get_type_info_FUI_Line_Params(){
Type_Info result = {};
result.name = strlit("FUI_Line_Params");
result.size = sizeof(FUI_Line_Params);
result.kind = I_Type_Kind_Struct;
result.members.set_count(4);
{
Type_Info *member_type = & Type_Info_FLP_Flags;
result.members[0] = {.type=member_type, .name=strlit("fui_flags"), .offset=offsetof(FUI_Line_Params, fui_flags)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[1] = {.type=member_type, .name=strlit("radii"), .offset=offsetof(FUI_Line_Params, radii)};
}
{
Type_Info *member_type = & Type_Info_v4;
result.members[2] = {.type=member_type, .name=strlit("lightness_additions"), .offset=offsetof(FUI_Line_Params, lightness_additions)};
}
{
Type_Info *member_type = & Type_Info_Line_Flags;
result.members[3] = {.type=member_type, .name=strlit("line_flags"), .offset=offsetof(FUI_Line_Params, line_flags)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_FUI_Line_Params;

function Type_Info *type_info_from_pointer(FUI_Line_Params*pointer){
return &Type_Info_FUI_Line_Params;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:264:
function void
read_binary_FUI_Line_Params(Binary_Reader *r, FUI_Line_Params *dst){
FLP_Flags m_fui_flags = {};
{
read_binary_FLP_Flags(r, &m_fui_flags);
}
dst->fui_flags = m_fui_flags;

v4 m_radii = {};
{
read_binary_v4(r, &m_radii);
}
dst->radii = m_radii;

v4 m_lightness_additions = {};
{
read_binary_v4(r, &m_lightness_additions);
}
dst->lightness_additions = m_lightness_additions;

Line_Flags m_line_flags = {};
{
read_binary_Line_Flags(r, &m_line_flags);
}
dst->line_flags = m_line_flags;


}
#endif
;

//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:405:
enum Reference_Preset{Preset_None = 0,
Preset_Back = 1,};
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:423:
function Type_Info
get_type_info_Reference_Preset();//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:427:
function Type_Info
get_type_info_Reference_Preset(){
Type_Info result = {};
result.name = strlit("Reference_Preset");
result.size = sizeof(Reference_Preset);
result.kind = I_Type_Kind_Enum;
result.enum_members.set_count(2);
result.enum_members[0] = {.name=strlit("Preset_None"), .value=Preset_None};
result.enum_members[1] = {.name=strlit("Preset_Back"), .value=Preset_Back};
return result;
}
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Reference_Preset;

function Type_Info *type_info_from_pointer(Reference_Preset*pointer){
return &Type_Info_Reference_Preset;
}
#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:451:
function void
read_binary_Reference_Preset(Binary_Reader *r, Reference_Preset *dst);
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:456:
function void
read_binary_Reference_Preset(Binary_Reader *r, Reference_Preset *dst){
i32 integer;
read_binary_i1(r, &integer);
*dst = *(Reference_Preset*)(&integer);
}
static_assert( sizeof(Reference_Preset) <= sizeof(i32) );

#endif
;


 #define poly3_inner__return void
#define poly3_inner__params Poly3 points, argb c0, argb c1, argb c2, Poly_Flags flags
  
 #define draw_bezier_inner__return void
#define draw_bezier_inner__params v3 P[4], Line_Params &params, argb base_color
  
 
 
#define framework_api_xlist_1(X) \
  X(poly3_inner) \
   X(draw_bezier_inner) \
 
 
#define framework_api_xlist_2(X) \
  X(push_object_transform_to_target) \
   X(DEBUG_send_entry) \
   X(push_image) \
 
 
#define framework_api_xlist(X) \
framework_api_xlist_1(X) \
framework_api_xlist_2(X) \
memory_functions_xlist(X)


struct Reference_Image{
Stringz filename;
tvert center;
v1 width;
v1 alpha;
b32 reflected;
};
;
struct Reference_Preset_Data{
v1 camera_phi;
v1 camera_theta;
Reference_Image image;
Pose pose;
};
;


 #define driver_render__return void
#define driver_render__params Arena *arena, Painter *painter
  
 #define driver_update__return void
#define driver_update__params Model *model, v1 anim_time
  
 #define driver_shutdown__return void
#define driver_shutdown__params void
  
 #define driver_update_tweaks__return void
#define driver_update_tweaks__params 
  
 #define driver_get_reference_preset_data__return Reference_Preset_Data
#define driver_get_reference_preset_data__params Reference_Preset preset
  
 
 
#define driver_api_xlist(X) \
  X(driver_render) \
   X(driver_update) \
   X(driver_shutdown) \
   X(driver_update_tweaks) \
   X(driver_get_reference_preset_data) \
 


struct Saved_Viewport{
Camera_Data target_camera;
i32 preset;
i32 last_preset;
Reference_Preset reference_preset;
};
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:191:
function Type_Info
get_type_info_Saved_Viewport(){
Type_Info result = {};
result.name = strlit("Saved_Viewport");
result.size = sizeof(Saved_Viewport);
result.kind = I_Type_Kind_Struct;
result.members.set_count(4);
{
Type_Info *member_type = & Type_Info_Camera_Data;
result.members[0] = {.type=member_type, .name=strlit("target_camera"), .offset=offsetof(Saved_Viewport, target_camera)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[1] = {.type=member_type, .name=strlit("preset"), .offset=offsetof(Saved_Viewport, preset)};
}
{
Type_Info *member_type = & Type_Info_i32;
result.members[2] = {.type=member_type, .name=strlit("last_preset"), .offset=offsetof(Saved_Viewport, last_preset)};
}
{
Type_Info *member_type = & Type_Info_Reference_Preset;
result.members[3] = {.type=member_type, .name=strlit("reference_preset"), .offset=offsetof(Saved_Viewport, reference_preset)};
}
return result;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:103:
global Type_Info Type_Info_Saved_Viewport;

function Type_Info *type_info_from_pointer(Saved_Viewport*pointer){
return &Type_Info_Saved_Viewport;
}
#endif
#if WANT_TYPE_INFO
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:264:
function void
read_binary_Saved_Viewport(Binary_Reader *r, Saved_Viewport *dst){
Camera_Data m_target_camera = {};
{
read_binary_Camera_Data(r, &m_target_camera);
}
dst->target_camera = m_target_camera;

i32 m_preset = {};
{
read_binary_i32(r, &m_preset);
}
dst->preset = m_preset;

i32 m_last_preset = {};
{
read_binary_i32(r, &m_last_preset);
}
dst->last_preset = m_last_preset;

Reference_Preset m_reference_preset = {};
if ( in_range_exclusive(r->read_version, Version_AddReferencePreset, Version_Inf) ){
read_binary_Reference_Preset(r, &m_reference_preset);
}
dst->reference_preset = m_reference_preset;


}
#endif
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:514:
#define Saved_Viewport_Embed \
 struct\
{\
Camera_Data target_camera;\
i32 preset;\
i32 last_preset;\
Reference_Preset reference_preset;\
\
};\
;
