// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1180:
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1066:
global Text_Object text_objects_[1] ={
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1232:
function void
 update_driver_data()
{
{
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1119:
{
}
//-
}
}
