// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1179:
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1010:
global i32 marked_positions_file_1[44] ={
//-NOTE: notebook.kc 
233,241,557,565,1068,1076,2068,2076,2271,2282,2294,2301,2572,2580,3195,3203,
3610,3618,3807,3818,4183,4191,4276,4287,4481,4489,4571,4582,4921,4927,5300,5308,
5443,5454,5744,5752,5855,5863,6011,6019,6205,6216,6468,6476,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1033:
global Vertex_Info vertices_info_[1] ={};
//-

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:940:
global Slider global_sliders[22];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:945:
struct Slider_Values{
i1 v_0;
i1 v_1;
i1 v_2;
i1 v_3;
v1 v_4;
v1 v_5;
i1 v_6;
i1 v_7;
i1 v_8;
v1 v_9;
i1 v_10;
v1 v_11;
i1 v_12;
v1 v_13;
i1 v_14;
i1 v_15;
v1 v_16;
i1 v_17;
i1 v_18;
i1 v_19;
v1 v_20;
i1 v_21;
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:957:
global Slider_Values slider_values ={
0,
0,
0,
0,
0.0863f,
1.f,
0,
0,
0,
0.0428f,
0,
0.6362f,
0,
5.9991f,
12,
0,
0.7817f,
0,
0,
0,
2.4578f,
1,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:978:
function void
 init_sliders(Type_Info_Pointers &types)
{
Slider *sliders = global_sliders;
sliders[0] = { .type=types.i1, .location={{0, 1}, {0, 1}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(0) };
sliders[1] = { .type=types.i1, .location={{0, 1}, {2, 3}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(1) };
sliders[2] = { .type=types.i1, .location={{0, 1}, {4, 5}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(2) };
sliders[3] = { .type=types.i1, .location={{0, 1}, {6, 7}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(3) };
sliders[4] = { .type=types.v1, .location={{0, 1}, {8, 9}}, .options={}, .value=&ReadSlider(4) };
sliders[5] = { .type=types.v1, .location={{0, 1}, {10, 11}}, .options={}, .value=&ReadSlider(5) };
sliders[6] = { .type=types.i1, .location={{0, 1}, {12, 13}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(6) };
sliders[7] = { .type=types.i1, .location={{0, 1}, {14, 15}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(7) };
sliders[8] = { .type=types.i1, .location={{0, 1}, {16, 17}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(8) };
sliders[9] = { .type=types.v1, .location={{0, 1}, {18, 19}}, .options={}, .value=&ReadSlider(9) };
sliders[10] = { .type=types.i1, .location={{0, 1}, {20, 21}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(10) };
sliders[11] = { .type=types.v1, .location={{0, 1}, {22, 23}}, .options={}, .value=&ReadSlider(11) };
sliders[12] = { .type=types.i1, .location={{0, 1}, {24, 25}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(12) };
sliders[13] = { .type=types.v1, .location={{0, 1}, {26, 27}}, .options={}, .value=&ReadSlider(13) };
sliders[14] = { .type=types.i1, .location={{0, 1}, {28, 29}}, .options={}, .value=&ReadSlider(14) };
sliders[15] = { .type=types.i1, .location={{0, 1}, {30, 31}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(15) };
sliders[16] = { .type=types.v1, .location={{0, 1}, {32, 33}}, .options={}, .value=&ReadSlider(16) };
sliders[17] = { .type=types.i1, .location={{0, 1}, {34, 35}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(17) };
sliders[18] = { .type=types.i1, .location={{0, 1}, {36, 37}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(18) };
sliders[19] = { .type=types.i1, .location={{0, 1}, {38, 39}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(19) };
sliders[20] = { .type=types.v1, .location={{0, 1}, {40, 41}}, .options={}, .value=&ReadSlider(20) };
sliders[21] = { .type=types.i1, .location={{0, 1}, {42, 43}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(21) };
}
//-
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1189:
global_decl Text_Object text_objects_[1];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1194:
global FUI_File_Data fui_files_[2] ={
{},
{
 .index = 1,
 .name = strlit("notebook.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_1)},
 .text_objects = make_slice(text_objects_, {0,0}),
 .sliders = make_slice(global_sliders, {0,22}),
 .vertices_info = make_slice(vertices_info_, {0,0}),
 },
};
