// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1179:
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1010:
global i32 marked_positions_file_1[2] ={
//-NOTE: i_hate_you_cpp.kc 
35,43,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1033:
global Vertex_Info vertices_info_[1] ={};
//-

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:940:
global Slider global_sliders[1];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:945:
struct Slider_Values{
i1 v_0;
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:957:
global Slider_Values slider_values ={
0,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:978:
function void
 init_sliders(Type_Info_Pointers &types)
{
Slider *sliders = global_sliders;
sliders[0] = { .type=types.i1, .location={{0, 1}, {0, 1}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(0) };
}
//-
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1189:
global_decl Text_Object text_objects_[1];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1194:
global FUI_File_Data fui_files_[2] ={
{},
{
 .index = 1,
 .name = strlit("i_hate_you_cpp.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_1)},
 .text_objects = make_slice(text_objects_, {0,0}),
 .sliders = make_slice(global_sliders, {0,1}),
 .vertices_info = make_slice(vertices_info_, {0,0}),
 },
};
