// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1178:
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1009:
global i32 marked_positions_file_1[2] ={
//-NOTE: i_hate_you_cpp.kc 
35,46,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1032:
global Vertex_Info vertices_info_[1] ={};
//-

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:945:
global Slider global_sliders[1];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:950:
struct Slider_Values{
i1 v_0;
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:962:
global Slider_Values slider_values ={
{},
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:976:
function void
 init_sliders(Type_Info_Pointers &types)
{
Slider *sliders = global_sliders;
sliders[0] = { .type=types.i1, .location={{0, 1}, {0, 1}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_0"), .value=&ReadSlider(0) };
}
//-
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1188:
global_decl Text_Object text_objects_[1];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1193:
global FUI_File_Data fui_files_[2] ={
{},
{
 .index = 1,
 .name = strlit("i_hate_you_cpp.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_1)},
 .text_objects = make_slice(text_objects_, {0,0}),
 .sliders = make_slice(global_sliders, {0,1}),
 .vertices_info = make_slice(vertices_info_, {0,0}),
 },
};
