// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1191:
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1077:
global Text_Object text_objects_[1] ={
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1243:
function void
 update_driver_data()
{
{
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1130:
{
}
//-
}
}
