//NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1133:
function void
make_all_type_info()
{
Type_Info_argb = get_type_info_argb();
Type_Info_b32 = get_type_info_b32();
Type_Info_tdim = get_type_info_tdim();
Type_Info_tvert = get_type_info_tvert();
Type_Info_tnormal = get_type_info_tnormal();
Type_Info_Line_Flags = get_type_info_Line_Flags();
Type_Info_FLP_Flags = get_type_info_FLP_Flags();
Type_Info_FUI_Line_Params = get_type_info_FUI_Line_Params();
Type_Info_Reference_Preset = get_type_info_Reference_Preset();
Type_Info_Saved_Viewport = get_type_info_Saved_Viewport();
Type_Info_Keyboard_Cursor = get_type_info_Keyboard_Cursor();
Type_Info_Serialized_State = get_type_info_Serialized_State();
Type_Info_Camera_Data = get_type_info_Camera_Data();
}