// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp:1731:
// NOTE: source: C:\Users\vodan\4ed\code\game\notebook.kc

function void
notebook_update(Notebook_State *state){
DEBUG_TEXT("Notebook is running!");
arena_clear(&notebook_frame_arena);
if(ReadSlider(0)){
mat2  A = {1, 3, 3, 5};
v2  b = {5, 8};
v2  x;
v2  A0 = get_column(A, 0);
v2  A1 = get_column(A, 1);
v1  det = cross2d(A0, A1);
x[0] = cross2d(b, A1) / det;
x[1] = cross2d(A0, b) / det;
v2  test = A * x;
DEBUG_VALUE(x);
DEBUG_VALUE(test);
DEBUG_VALUE(b);
}
if(ReadSlider(1)){
GraphBlock;
v1  t = .3f;
v1  s = .6f;
v2  b0 = {0, 0};
v2  b1 = {5, 9};
v2  b2 = {8, 0};
v2  b0t = lerp(b0, t, b1);
v2  b0s = lerp(b0, s, b1);
v2  b1t = lerp(b1, t, b2);
v2  b1s = lerp(b1, s, b2);
v2  bst = lerp(b0s, t, b1s);
v2  bts = lerp(b0t, s, b1t);
graph_point(b0);
graph_point(b1);
graph_point(b2);
graph_point(b0t);
graph_point(b0s);
graph_point(b1t);
graph_point(b1s);
graph_point(bst);
graph_point(bts);
}
if(ReadSlider(2)){
v1  alpha = -0.9f;
v1  beta = 1.9f;
v1  r = 4.f;
v1  s = 3.f;
v4  b = {2.f, 1.f, 5.f, 3.f};
v1  value0 = bezier_iterative(b, alpha * r + beta * s);
DEBUG_VALUE(value0);
v1  value = 0.f;
const i32  n = 3;
for_i32(i,0,n+1)
  {
v4  b_tmp = b;
for_i32(j,0,i)  {
blossom(b_tmp.e, n, r);
}
for_i32(j,0,n-i){
blossom(b_tmp.e, n, s);
}
value += binomial(n, i) * integer_power(alpha, i) * integer_power(beta, n - i) * b_tmp[0];
}
DEBUG_VALUE(value);
}
if(0){
{
v4  b = {2.f, 1.f, 5.f, 3.f};
const i32  n = 3;
v1  t = .3f;
v1  sum = 0.f;
for_i32(i, 0, n+1)
   {
sum += v1(i) / n * bernstein(n, i, t);
}
DEBUG_VALUE(sum);
DEBUG_VALUE(t);
}
{
i32  i = 3;
i32  n = 5;
DEBUG_VALUE(i * binomial(n, i));
DEBUG_VALUE(n * binomial(n - 1, i - 1));
}
}
if(ReadSlider(3)){
GraphBlock;
const i32  n = 3;
{
v2  b[n + 1] = {{1.f, 2.f}, {2.f, 1.f}, {3.f, 3.f}, {5.f, 0.f}};
for_i32(i, 0, n+1) {
graph_point(b[i]);
}
v1  t = ReadSlider(4);
v1  v = ReadSlider(5);
v2  dcb_vector = dcb(b, n, v, 1);
ImGuiCol  color = ImGui::GetColorU32(ImGuiCol_Text);
graph_point(dcb_vector, color);
DEBUG_VALUE(dcb_vector);
}
if(ReadSlider(6)){
v4  b = {2.f, 1.f, 5.f, 3.f};
v3  v = {.3f, .2f, .9f};
{
v4  b_ = b;
blossom_vector(b_.e, n, v[0]);
blossom_vector(b_.e, n, v[1]);
blossom_vector(b_.e, n, v[2]);
DEBUG_VALUE(b_[0]);
}
{
v4  b_ = b;
blossom_vector(b_.e, n, v[1]);
blossom_vector(b_.e, n, v[2]);
blossom_vector(b_.e, n, v[0]);
DEBUG_VALUE(b_[0]);
}
{
v4  b_ = b;
blossom_vector(b_.e, n, v[2]);
blossom_vector(b_.e, n, v[0]);
blossom_vector(b_.e, n, v[1]);
DEBUG_VALUE(b_[0]);
}
}
}
if(ReadSlider(7)){
const i32  n = 3;
v4  b = {2.f, 1.f, 5.f, 3.f};
v1  t = 0.3f;
v1  v = 0.6f;
{
v1  lhs = dcb(b, t + v);
DEBUG_VALUE(lhs);
}
{
v1  rhs = 0.f;
for_i32(i, 0, n+1)
   {
v4  b_ = b;
for_repeat(n-i){
blossom(b_.e, n, t);
}
for_repeat(i)  {
blossom_vector(b_.e, n, v);
}
rhs += binomial(n, i) * b_[0];
}
DEBUG_VALUE(rhs);
}
}
if(ReadSlider(8)){
GraphBlock;
const i32  n = 3;
v2  b[n + 1] = {{1.f, 2.f}, {2.f, 1.f}, {3.f, 3.f}, {5.f, 0.f}};
for_i32(i, 0, n+1) {
graph_point(b[i]);
}
v1  t = ReadSlider(9);
v2  derivative = {};
{
v2  b_tmp[n + 1];
block_copy(b_tmp, b, sizeof(b));
dcb_rounds(b_tmp, n, n - 1, t);
derivative = n * (b_tmp[1] - b_tmp[0]);
}
ImGuiCol  color = ImGui::GetColorU32(ImGuiCol_Text);
v2  sample = dcb(b, n, t);
graph_point(sample, color);
graph_line(sample, sample + derivative, color);
DEBUG_VALUE(derivative);
}
if(ReadSlider(10)){
v4  b = {2.f, 1.f, 5.f, 3.f};
const i32  n = 3;
v1  t = ReadSlider(11);
v1  lhs = dcb(b, t);
v1  rhs = 0.f;
for_i32(i, 0, n+1)
  {
rhs += binomial(n, i) * forward_difference(b.e, i) * integer_power(t, i);
}
DEBUG_VALUE(lhs);
DEBUG_VALUE(rhs);
}
if(ReadSlider(12)){
v4  b = {2.f, 1.f, 5.f, 3.f};
const i32  n = 3;
v1  t = ReadSlider(13);
v1  a = 2.f;
v1  b2 = 6.f;
auto u_from_t = [&](v1 t1) -> v1  {
return (t1 - a) / (b2 - a);
};

v1  u = u_from_t(t);
auto x_from_u = [&](v1 u1) -> v1  {
return dcb(b, u1);
};

auto x_from_t = [&](v1 t1) -> v1  {
return x_from_u(u_from_t(t1));
};

v1  x = x_from_t(t);
DEBUG_VALUE(t);
DEBUG_VALUE(u);
DEBUG_VALUE(x);
v1  epsilon = integer_power(0.5f, ReadSlider(14));
DEBUG_VALUE(epsilon);
v1  dx_dt = (x_from_t(t + epsilon) - x_from_t(t)) / epsilon;
v1  dx_du = (x_from_u(u + epsilon) - x_from_u(u)) / epsilon;
DEBUG_VALUE(dx_dt);
v1  du_dt = 1.f / (b2 - a);
DEBUG_VALUE(dx_du * du_dt);
{
v4  b_tmp = b;
dcb_rounds(b_tmp.e, n, n - 1, u);
v1  rhs = v1(n) / (b2 - a) * (b_tmp[1] - b_tmp[0]);
DEBUG_VALUE(rhs);
}
}
if(ReadSlider(15)){
GraphBlock;
const i32  n = 3;
v2  b[n + 1] = {{1.f, 2.f}, {2.f, 1.f}, {3.f, 3.f}, {2.f, 4.f}};
v1  t1 = ReadSlider(16);
graph_bezier(b, n);
v2  p1[n + 1];
block_copy_count(p1, b, n + 1);
dcb_rounds(p1, n, 1, t1);
graph_bezier(p1, n - 1, sargb_bright_yellow);
const i32  nslices = 16;
v1  interval = 1.f / nslices;
for_i32(islice, 0, nslices+1)
  {
v1  t = interval * islice;
if(ReadSlider(17)){
graph_line(dcb(b, n, t), dcb(p1, n - 1, t), ImGui::GetColorU32(ImGuiCol_Text));
}
}
}
if(0){
auto g = [&](v1 y) -> v1  {
return y * y * y;
};

auto f = [&](v1 x) -> v1  {
return x * x;
};

v1  x0 = ReadSlider(18);
v1  h = 0.0001f;
v1  approx = (g(f(x0 + h)) - g(f(x0))) / h;
DEBUG_VALUE(approx);
v1  y0 = f(x0);
v1  dz_over_dy_at_y0 = 3.f * y0 * y0;
v1  dy_over_dx_at_x0 = 2.f * x0;
v1  rhs = dz_over_dy_at_y0 * dy_over_dx_at_x0;
DEBUG_VALUE(rhs);
}
if(0){
nb_internet_main();
}
{
if(0){
v1  a_val = 3.f;
{
LLM_Value  *a = mk_value(a_val, strlit("a"));
LLM_Value  *o = mk_value_tanh(a);
backprop(o);
DEBUG_VALUE(o->value);
DEBUG_VALUE(a->grad);
}
{
LLM_Value  *a = mk_value(a_val, strlit("a"));
LLM_Value  *o = mk_value_tanh_graph(a);
backprop(o);
DEBUG_VALUE(o->value);
DEBUG_VALUE(a->grad);
}
}
if(1){
Scratch_Block  tmp;
auto  xs = {v1{2.f, 3.f, -1.f}, v1{3.f, -1.f, 0.5f}, v1{0.5f, 1.f, 1.f}, v1{1.f, 1.f, -1.f}};
i32  neuron_counts[] = {4, 4, 1};
MLP  mlp = mk_mlp(3, to_sarray(neuron_counts));
v1  o = mlp_apply(tmp, mlp, xs[0]);
DEBUG_VALUE(o);
v1  ys[] = {1.f, -1.f, -1.f, 1.f};
}
}
}
