//NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1157:
//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:1058:
global Text_Object text_objects[64] = {
{.location={1, {0, 1}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/arm back bone.PNG")}},
{.location={1, {2, 3}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/arm left.PNG")}},
{.location={1, {4, 5}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/brachio radialis profile bone.JPG")}},
{.location={1, {6, 9}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/skeletal meat outline.JPG")}},
{.location={1, {10, 11}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/brachio front.JPG")}},
{.location={1, {12, 13}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/left arm back.PNG")}},
{.location={1, {14, 15}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/tricep brachii tendon.JPG")}},
{.location={1, {16, 17}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/triceps long head.JPG")}},
{.location={1, {18, 19}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/AM full body muscle front.JPG")}},
{.location={1, {20, 21}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/upper body front muscle.JPG")}},
{.location={1, {22, 23}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/brachialis vs skeleton.JPG")}},
{.location={1, {24, 25}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/clavicle vs arm.JPG")}},
{.location={1, {26, 27}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/clavicle.JPG")}},
{.location={1, {28, 29}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/arm muscle connection.JPG")}},
{.location={1, {30, 31}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/scapula profile.JPG")}},
{.location={1, {32, 33}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/socket and ball.JPG")}},
{.location={1, {34, 35}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/deltoid insertions.JPG")}},
{.location={1, {36, 37}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/eco skeleton.JPG")}},
{.location={1, {52, 53}}, .kind=Text_Object_Preset, .preset=Preset_None},
{.location={1, {72, 73}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/AM arm profile 2.JPG")}},
{.location={1, {78, 79}}, .kind=Text_Object_Preset, .preset=Preset_Eco_Skeleton},
{.location={1, {80, 81}}, .kind=Text_Object_Image, .image={.filename=image_eco_skeleton}},
{.location={1, {106, 107}}, .kind=Text_Object_Preset, .preset=Preset_Arm_Profile},
{.location={1, {108, 111}}, .kind=Text_Object_Image, .image={.filename=image_scapula_profile}},
{.location={1, {268, 269}}, .kind=Text_Object_Image, .image={.filename=image_skeletal_meat_outline}},
{.location={1, {308, 309}}, .kind=Text_Object_Preset, .preset=Preset_Arm_Profile},
{.location={1, {326, 327}}, .kind=Text_Object_Image, .image={.filename=image_socket_and_ball}},
{.location={1, {412, 415}}, .kind=Text_Object_Image, .image={.filename=image_mm_full_body_muslce_front}},
{.location={1, {420, 421}}, .kind=Text_Object_Image, .image={.filename=image_tricep_brachii_tendon}},
{.location={1, {422, 425}}, .kind=Text_Object_Image, .image={.filename=image_left_arm_back}},
{.location={1, {430, 433}}, .kind=Text_Object_Image, .image={.filename=image_left_arm_back}},
{.location={1, {446, 449}}, .kind=Text_Object_Image, .image={.filename=image_brachio_front}},
{.location={1, {456, 457}}, .kind=Text_Object_Image, .image={.filename=image_left_arm_back}},
{.location={1, {472, 479}}, .kind=Text_Object_Image, .image={.filename=image_left_arm_back}},
{.location={1, {480, 481}}, .kind=Text_Object_Image, .image={.filename=image_triceps_long_head}},
{.location={1, {482, 483}}, .kind=Text_Object_Image, .image={.filename=image_arm_muscle_connection}},
{.location={1, {486, 487}}, .kind=Text_Object_Preset, .preset=Preset_Back},
{.location={1, {498, 505}}, .kind=Text_Object_Image, .image={.filename=image_upper_body_front_muscle}},
{.location={1, {538, 539}}, .kind=Text_Object_Image, .image={.filename=image_arm_profile_full}},
{.location={1, {540, 543}}, .kind=Text_Object_Image, .image={.filename=image_brachio_profile_bone}},
{.location={1, {572, 575}}, .kind=Text_Object_Image, .image={.filename=image_brachialis_vs_skeleton}},
{.location={1, {584, 585}}, .kind=Text_Object_Image, .image={.filename=image_skeletal_meat_outline}},
{.location={1, {636, 643}}, .kind=Text_Object_Image, .image={.filename=image_brachialis_vs_skeleton}},
{.location={1, {710, 713}}, .kind=Text_Object_Image, .image={.filename=file_arm_back_bone}},
{.location={1, {724, 731}}, .kind=Text_Object_Image, .image={.filename=image_brachio_front}},
{.location={1, {738, 745}}, .kind=Text_Object_Image, .image={.filename=image_brachio_front}},
{.location={1, {754, 759}}, .kind=Text_Object_Image, .image={.filename=image_arm_profile_full}},
{.location={1, {808, 811}}, .kind=Text_Object_Image, .image={.filename=image_clavicle_vs_arm}},
{.location={1, {812, 815}}, .kind=Text_Object_Image, .image={.filename=image_clavicle}},
{.location={1, {852, 855}}, .kind=Text_Object_Image, .image={.filename=image_deltoid_insertions}},
{.location={1, {856, 859}}, .kind=Text_Object_Image, .image={.filename=image_skeletal_meat_outline}},
{.location={1, {892, 893}}, .kind=Text_Object_Preset, .preset=Preset_Arm_Profile},
{.location={1, {894, 897}}, .kind=Text_Object_Image, .image={.filename=image_scapula_profile}},
{.location={1, {920, 921}}, .kind=Text_Object_Image, .image={.filename=image_scapula_profile}},
{.location={1, {922, 923}}, .kind=Text_Object_Image, .image={.filename=image_socket_and_ball}},
{.location={1, {924, 925}}, .kind=Text_Object_Image, .image={.filename=image_skeletal_meat_outline}},
{.location={1, {926, 927}}, .kind=Text_Object_Preset, .preset=Preset_Arm_Profile},
{.location={1, {1436, 1437}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/arm medial.jpg")}},
{.location={1, {1440, 1441}}, .kind=Text_Object_Image, .image={.filename=image_skeletal_meat_outline}},
{.location={1, {1444, 1445}}, .kind=Text_Object_Image, .image={.filename=image_mm_full_body_muslce_front}},
{.location={1, {1448, 1449}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/AM arm front.JPG")}},
{.location={1, {1452, 1453}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/loomis 6 heads.JPG")}},
{.location={1, {1456, 1457}}, .kind=Text_Object_Image, .image={.filename=strlit("G:/My Drive/Art/hpc.JPG")}},
{.location={1, {1472, 1473}}, .kind=Text_Object_Image, .image={.filename=image_arm_profile_full}},
};

//  C:\Users\vodan\4ed\code\meta\meta_print.cpp:1100:
function void
update_text_objects()
{
text_objects[23].image.marker = mk_image_marker(ReadSlider(v2, 25));
text_objects[27].image.marker = mk_image_marker(ReadSlider(v2, 72));
text_objects[29].image.marker = mk_image_marker(ReadSlider(v2, 74));
text_objects[30].image.marker = mk_image_marker(ReadSlider(v2, 76));
text_objects[31].image.marker = mk_image_marker(ReadSlider(v2, 80));
text_objects[33].image.marker = mk_image_marker(bez_v2_offset(ReadSlider(v2, 82), ReadSlider(v2, 83), ReadSlider(v2, 84)));
text_objects[37].image.marker = mk_image_marker(bez_v2_offset(ReadSlider(v2, 88), ReadSlider(v2, 89), ReadSlider(v2, 90)));
text_objects[38].image.marker = mk_image_marker(brachio_humerus_profile_uv);
text_objects[39].image.marker = mk_image_marker(ReadSlider(v2, 92));
text_objects[40].image.marker = mk_image_marker(ReadSlider(v2, 102));
text_objects[42].image.marker = mk_image_marker(bez_v2_offset(ReadSlider(v2, 118), ReadSlider(v2, 119), ReadSlider(v2, 120)));
text_objects[43].image.marker = mk_image_marker(ReadSlider(v2, 131));
text_objects[44].image.marker = mk_image_marker(bez_v2_offset(ReadSlider(v2, 133), ReadSlider(v2, 134), ReadSlider(v2, 135)));
text_objects[45].image.marker = mk_image_marker(bez_v2_offset(ReadSlider(v2, 138), ReadSlider(v2, 139), ReadSlider(v2, 140)));
text_objects[46].image.marker = mk_image_marker(bez_v2_offset(brachio_humerus_profile_uv, ReadSlider(v2, 144), ReadSlider(v2, 145)));
text_objects[47].image.marker = mk_image_marker(ReadSlider(v2, 150));
text_objects[48].image.marker = mk_image_marker(ReadSlider(v2, 151));
text_objects[49].image.marker = mk_image_marker(ReadSlider(v2, 155));
text_objects[50].image.marker = mk_image_marker(ReadSlider(v2, 156));
text_objects[52].image.marker = mk_image_marker(ReadSlider(v2, 160));
}
//-
