// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_klang.cpp:1744:
// NOTE: source: C:\Users\vodan\4ed\code\game\test.kc

function void
test_link(){
ReadSlider(0) + ReadSlider(1);
line_params_from_fui(ReadSlider(2));
}
