// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_main.cpp:248:
//NOTE source: C:\Users\vodan\4ed\code\custom_command_list.h
#  define command_one_past_last_id 200
function void F4_Index_Reset(App_Cmd *app);
function void delete_char(App_Cmd *app);
function void backspace_char(App_Cmd *app);
function void click_set_cursor_and_mark(App_Cmd *app);
function void click_set_cursor(App_Cmd *app);
function void click_set_cursor_if_lbutton(App_Cmd *app);
function void click_set_mark(App_Cmd *app);
function void mouse_wheel_scroll(App_Cmd *app);
function void move_up(App_Cmd *app);
function void move_down(App_Cmd *app);
function void move_up_10(App_Cmd *app);
function void move_down_10(App_Cmd *app);
function void move_down_textual(App_Cmd *app);
function void page_up(App_Cmd *app);
function void page_down(App_Cmd *app);
function void move_up_to_blank_line(App_Cmd *app);
function void move_down_to_blank_line(App_Cmd *app);
function void move_up_to_blank_line_skip_whitespace(App_Cmd *app);
function void move_down_to_blank_line_skip_whitespace(App_Cmd *app);
function void move_up_to_blank_line_end(App_Cmd *app);
function void move_down_to_blank_line_end(App_Cmd *app);
function void select_all(App_Cmd *app);
function void clean_all_lines(App_Cmd *app);
function void clean_trailing_whitespace(App_Cmd *app);
function void show_scrollbar(App_Cmd *app);
function void hide_scrollbar(App_Cmd *app);
function void show_filebar(App_Cmd *app);
function void hide_filebar(App_Cmd *app);
function void toggle_filebar(App_Cmd *app);
function void toggle_fps_meter(App_Cmd *app);
function void set_face_size(App_Cmd *app);
function void increase_face_size(App_Cmd *app);
function void decrease_face_size(App_Cmd *app);
function void set_face_size_this_buffer(App_Cmd *app);
function void mouse_wheel_change_face_size(App_Cmd *app);
function void toggle_show_whitespace(App_Cmd *app);
function void toggle_line_numbers(App_Cmd *app);
function void exit_4coder(App_Cmd *app);
function void goto_line(App_Cmd *app);
function void goto_pos(App_Cmd *app);
function void search(App_Cmd *app);
function void reverse_search(App_Cmd *app);
function void search_identifier(App_Cmd *app);
function void reverse_search_identifier(App_Cmd *app);
function void replace_in_range(App_Cmd *app);
function void toggle_undo_global_mode(App_Cmd *app);
function void replace_in_buffer(App_Cmd *app);
function void reopen(App_Cmd *app);
function void save_current_buffer(App_Cmd *app);
function void kill_buffer(App_Cmd *app);
function void quick_swap_buffer(App_Cmd *app);
function void swap_panels(App_Cmd *app);
function void open_matching_file_cpp_other_panel(App_Cmd *app);
function void open_matching_file_cpp(App_Cmd *app);
function void open_file_in_quotes(App_Cmd *app);
function void delete_line(App_Cmd *app);
function void duplicate_line(App_Cmd *app);
function void move_line_down(App_Cmd *app);
function void move_line_up(App_Cmd *app);
function void make_directory_query(App_Cmd *app);
function void rename_file_query(App_Cmd *app);
function void save_to_query(App_Cmd *app);
function void delete_file_query(App_Cmd *app);
function void jump_to_last_point(App_Cmd *app);
function void query_replace_selection(App_Cmd *app);
function void query_replace_identifier(App_Cmd *app);
function void query_replace(App_Cmd *app);
function void replace_in_all_buffers(App_Cmd *app);
function void are_we_in_debug_build(App_Cmd *app);
function void messages(App_Cmd *app);
function void dir(App_Cmd *app);
function void scratch(App_Cmd *app);
function void set_current_dir_as_hot(App_Cmd *app);
function void init(App_Cmd *app);
function void kv_miscellaneous_debug_command(App_Cmd *app);
function void file(App_Cmd *app);
function void copy_filename(App_Cmd *app);
function void switch_to_game_panel(App_Cmd *app);
function void kv_open_note_file(App_Cmd *app);
function void kv_run(App_Cmd *app);
function void kv_reopen_with_confirmation(App_Cmd *app);
function void byp_reset_face_size(App_Cmd *app);
function void project_command_F16(App_Cmd *app);
function void project_command_F15(App_Cmd *app);
function void project_command_F14(App_Cmd *app);
function void project_command_F13(App_Cmd *app);
function void project_command_F12(App_Cmd *app);
function void project_command_F11(App_Cmd *app);
function void project_command_F10(App_Cmd *app);
function void project_command_F9(App_Cmd *app);
function void project_command_F8(App_Cmd *app);
function void project_command_F7(App_Cmd *app);
function void project_command_F6(App_Cmd *app);
function void project_command_F5(App_Cmd *app);
function void project_command_F4(App_Cmd *app);
function void project_command_F3(App_Cmd *app);
function void project_command_F2(App_Cmd *app);
function void project_command_F1(App_Cmd *app);
function void project_reprint(App_Cmd *app);
function void project_command_lister(App_Cmd *app);
function void project_go_to_root_directory(App_Cmd *app);
function void project_fkey_command(App_Cmd *app);
function void load_project_current_dir(App_Cmd *app);
function void open_all_code_recursive(App_Cmd *app);
function void open_all_code(App_Cmd *app);
function void close_all_code(App_Cmd *app);
function void delete_current_scope(App_Cmd *app);
function void place_in_scope(App_Cmd *app);
function void select_prev_top_most_scope(App_Cmd *app);
function void select_prev_scope_absolute(App_Cmd *app);
function void select_next_scope_after_current(App_Cmd *app);
function void select_next_scope_absolute(App_Cmd *app);
function void select_surrounding_scope_maximal(App_Cmd *app);
function void select_surrounding_scope(App_Cmd *app);
function void clear_all_themes(App_Cmd *app);
function void load_themes_hot_directory(App_Cmd *app);
function void toggle_fullscreen(App_Cmd *app);
function void set_mode_to_original(App_Cmd *app);
function void toggle_mouse(App_Cmd *app);
function void allow_mouse(App_Cmd *app);
function void suppress_mouse(App_Cmd *app);
function void debug_camera_on(App_Cmd *app);
function void game_disable(App_Cmd *app);
function void game_enable(App_Cmd *app);
function void goto_first_jump_same_panel_sticky(App_Cmd *app);
function void goto_first_jump(App_Cmd *app);
function void goto_prev_jump_no_skips(App_Cmd *app);
function void goto_next_jump_no_skips(App_Cmd *app);
function void comment_line_toggle(App_Cmd *app);
function void uncomment_line(App_Cmd *app);
function void comment_line(App_Cmd *app);
function void if0_off(App_Cmd *app);
function void open_long_braces_break(App_Cmd *app);
function void open_long_braces_semicolon(App_Cmd *app);
function void open_long_braces(App_Cmd *app);
function void seek_end_of_textual_line(App_Cmd *app);
function void seek_beginning_of_textual_line(App_Cmd *app);
function void keyboard_macro_replay(App_Cmd *app);
function void keyboard_macro_finish_recording(App_Cmd *app);
function void keyboard_macro_start_recording(App_Cmd *app);
function void word_complete_drop_down(App_Cmd *app);
function void word_complete(App_Cmd *app);
function void list_all_substring_locations_case_insensitive(App_Cmd *app);
function void list_all_locations_case_insensitive(App_Cmd *app);
function void list_all_substring_locations(App_Cmd *app);
function void list_all_locations(App_Cmd *app);
function void set_eol_mode_from_contents(App_Cmd *app);
function void set_eol_mode_to_binary(App_Cmd *app);
function void set_eol_mode_to_lf(App_Cmd *app);
function void set_eol_mode_to_crlf(App_Cmd *app);
function void multi_paste_interactive_quick(App_Cmd *app);
function void multi_paste_interactive(App_Cmd *app);
function void multi_paste(App_Cmd *app);
function void paste_next(App_Cmd *app);
function void paste(App_Cmd *app);
function void cut(App_Cmd *app);
function void copy(App_Cmd *app);
function void clipboard_record_clip(App_Cmd *app);
function void kv_profile_disable_and_inspect(App_Cmd *app);
function void profile_clear(App_Cmd *app);
function void profile_enable(App_Cmd *app);
function void execute_any_cli(App_Cmd *app);
function void execute_previous_cli(App_Cmd *app);
function void go_to_user_directory(App_Cmd *app);
function void load_theme_current_buffer(App_Cmd *app);
function void DEBUG_draw_hud_toggle(App_Cmd *app);
function void view_jump_list_with_lister(App_Cmd *app);
function void no_op(App_Cmd *app);
function void default_view_input_handler(App_Cmd *app);
function void default_try_exit(App_Cmd *app);
function void write_text_and_auto_indent(App_Cmd *app);
function void goto_end_of_file(App_Cmd *app);
function void goto_beginning_of_file(App_Cmd *app);
function void load_themes_default_folder(App_Cmd *app);
function void save_all_dirty_buffers(App_Cmd *app);
function void open_panel_hsplit(App_Cmd *app);
function void open_panel_vsplit(App_Cmd *app);
function void set_mark(App_Cmd *app);
function void center_view(App_Cmd *app);
function void left_adjust_view(App_Cmd *app);
function void move_left(App_Cmd *app);
function void move_right(App_Cmd *app);
function void vim_try_exit(App_Cmd *app);
function void cmd_goto_random_position(App_Cmd *app);
function void cmd_switch_dot_arrow(App_Cmd *app);
function void turn_game_on(App_Cmd *app);
function void turn_game_off(App_Cmd *app);
function void profile_inspect(App_Cmd *app);
function void vim_interactive_open_or_new(App_Cmd *app);
function void vim_theme_lister(App_Cmd *app);
function void vim_proj_cmd_lister(App_Cmd *app);
function void vim_jump_lister(App_Cmd *app);
function void interactive_switch_buffer(App_Cmd *app);
function void interactive_kill_buffer(App_Cmd *app);
function void interactive_open_or_new(App_Cmd *app);
function void interactive_new(App_Cmd *app);
function void interactive_open(App_Cmd *app);
function void command_lister(App_Cmd *app);
function void theme_lister(App_Cmd *app);
function void show_the_log_graph(App_Cmd *app);

   struct Command_Metadata{
   Custom_Command_Function *proc;
   b32 is_ui;
   String name;
   };
   static Command_Metadata fcoder_metacmd_table[200] = {
{ .proc=F4_Index_Reset, .is_ui=0, .name=strlit("F4_Index_Reset") },
{ .proc=delete_char, .is_ui=0, .name=strlit("delete_char") },
{ .proc=backspace_char, .is_ui=0, .name=strlit("backspace_char") },
{ .proc=click_set_cursor_and_mark, .is_ui=0, .name=strlit("click_set_cursor_and_mark") },
{ .proc=click_set_cursor, .is_ui=0, .name=strlit("click_set_cursor") },
{ .proc=click_set_cursor_if_lbutton, .is_ui=0, .name=strlit("click_set_cursor_if_lbutton") },
{ .proc=click_set_mark, .is_ui=0, .name=strlit("click_set_mark") },
{ .proc=mouse_wheel_scroll, .is_ui=0, .name=strlit("mouse_wheel_scroll") },
{ .proc=move_up, .is_ui=0, .name=strlit("move_up") },
{ .proc=move_down, .is_ui=0, .name=strlit("move_down") },
{ .proc=move_up_10, .is_ui=0, .name=strlit("move_up_10") },
{ .proc=move_down_10, .is_ui=0, .name=strlit("move_down_10") },
{ .proc=move_down_textual, .is_ui=0, .name=strlit("move_down_textual") },
{ .proc=page_up, .is_ui=0, .name=strlit("page_up") },
{ .proc=page_down, .is_ui=0, .name=strlit("page_down") },
{ .proc=move_up_to_blank_line, .is_ui=0, .name=strlit("move_up_to_blank_line") },
{ .proc=move_down_to_blank_line, .is_ui=0, .name=strlit("move_down_to_blank_line") },
{ .proc=move_up_to_blank_line_skip_whitespace, .is_ui=0, .name=strlit("move_up_to_blank_line_skip_whitespace") },
{ .proc=move_down_to_blank_line_skip_whitespace, .is_ui=0, .name=strlit("move_down_to_blank_line_skip_whitespace") },
{ .proc=move_up_to_blank_line_end, .is_ui=0, .name=strlit("move_up_to_blank_line_end") },
{ .proc=move_down_to_blank_line_end, .is_ui=0, .name=strlit("move_down_to_blank_line_end") },
{ .proc=select_all, .is_ui=0, .name=strlit("select_all") },
{ .proc=clean_all_lines, .is_ui=0, .name=strlit("clean_all_lines") },
{ .proc=clean_trailing_whitespace, .is_ui=0, .name=strlit("clean_trailing_whitespace") },
{ .proc=show_scrollbar, .is_ui=0, .name=strlit("show_scrollbar") },
{ .proc=hide_scrollbar, .is_ui=0, .name=strlit("hide_scrollbar") },
{ .proc=show_filebar, .is_ui=0, .name=strlit("show_filebar") },
{ .proc=hide_filebar, .is_ui=0, .name=strlit("hide_filebar") },
{ .proc=toggle_filebar, .is_ui=0, .name=strlit("toggle_filebar") },
{ .proc=toggle_fps_meter, .is_ui=0, .name=strlit("toggle_fps_meter") },
{ .proc=set_face_size, .is_ui=0, .name=strlit("set_face_size") },
{ .proc=increase_face_size, .is_ui=0, .name=strlit("increase_face_size") },
{ .proc=decrease_face_size, .is_ui=0, .name=strlit("decrease_face_size") },
{ .proc=set_face_size_this_buffer, .is_ui=0, .name=strlit("set_face_size_this_buffer") },
{ .proc=mouse_wheel_change_face_size, .is_ui=0, .name=strlit("mouse_wheel_change_face_size") },
{ .proc=toggle_show_whitespace, .is_ui=0, .name=strlit("toggle_show_whitespace") },
{ .proc=toggle_line_numbers, .is_ui=0, .name=strlit("toggle_line_numbers") },
{ .proc=exit_4coder, .is_ui=0, .name=strlit("exit_4coder") },
{ .proc=goto_line, .is_ui=0, .name=strlit("goto_line") },
{ .proc=goto_pos, .is_ui=0, .name=strlit("goto_pos") },
{ .proc=search, .is_ui=0, .name=strlit("search") },
{ .proc=reverse_search, .is_ui=0, .name=strlit("reverse_search") },
{ .proc=search_identifier, .is_ui=0, .name=strlit("search_identifier") },
{ .proc=reverse_search_identifier, .is_ui=0, .name=strlit("reverse_search_identifier") },
{ .proc=replace_in_range, .is_ui=0, .name=strlit("replace_in_range") },
{ .proc=toggle_undo_global_mode, .is_ui=0, .name=strlit("toggle_undo_global_mode") },
{ .proc=replace_in_buffer, .is_ui=0, .name=strlit("replace_in_buffer") },
{ .proc=reopen, .is_ui=0, .name=strlit("reopen") },
{ .proc=save_current_buffer, .is_ui=0, .name=strlit("save_current_buffer") },
{ .proc=kill_buffer, .is_ui=0, .name=strlit("kill_buffer") },
{ .proc=quick_swap_buffer, .is_ui=0, .name=strlit("quick_swap_buffer") },
{ .proc=swap_panels, .is_ui=0, .name=strlit("swap_panels") },
{ .proc=open_matching_file_cpp_other_panel, .is_ui=0, .name=strlit("open_matching_file_cpp_other_panel") },
{ .proc=open_matching_file_cpp, .is_ui=0, .name=strlit("open_matching_file_cpp") },
{ .proc=open_file_in_quotes, .is_ui=0, .name=strlit("open_file_in_quotes") },
{ .proc=delete_line, .is_ui=0, .name=strlit("delete_line") },
{ .proc=duplicate_line, .is_ui=0, .name=strlit("duplicate_line") },
{ .proc=move_line_down, .is_ui=0, .name=strlit("move_line_down") },
{ .proc=move_line_up, .is_ui=0, .name=strlit("move_line_up") },
{ .proc=make_directory_query, .is_ui=0, .name=strlit("make_directory_query") },
{ .proc=rename_file_query, .is_ui=0, .name=strlit("rename_file_query") },
{ .proc=save_to_query, .is_ui=0, .name=strlit("save_to_query") },
{ .proc=delete_file_query, .is_ui=0, .name=strlit("delete_file_query") },
{ .proc=jump_to_last_point, .is_ui=0, .name=strlit("jump_to_last_point") },
{ .proc=query_replace_selection, .is_ui=0, .name=strlit("query_replace_selection") },
{ .proc=query_replace_identifier, .is_ui=0, .name=strlit("query_replace_identifier") },
{ .proc=query_replace, .is_ui=0, .name=strlit("query_replace") },
{ .proc=replace_in_all_buffers, .is_ui=0, .name=strlit("replace_in_all_buffers") },
{ .proc=are_we_in_debug_build, .is_ui=0, .name=strlit("are_we_in_debug_build") },
{ .proc=messages, .is_ui=0, .name=strlit("messages") },
{ .proc=dir, .is_ui=0, .name=strlit("dir") },
{ .proc=scratch, .is_ui=0, .name=strlit("scratch") },
{ .proc=set_current_dir_as_hot, .is_ui=0, .name=strlit("set_current_dir_as_hot") },
{ .proc=init, .is_ui=0, .name=strlit("init") },
{ .proc=kv_miscellaneous_debug_command, .is_ui=0, .name=strlit("kv_miscellaneous_debug_command") },
{ .proc=file, .is_ui=0, .name=strlit("file") },
{ .proc=copy_filename, .is_ui=0, .name=strlit("copy_filename") },
{ .proc=switch_to_game_panel, .is_ui=0, .name=strlit("switch_to_game_panel") },
{ .proc=kv_open_note_file, .is_ui=0, .name=strlit("kv_open_note_file") },
{ .proc=kv_run, .is_ui=0, .name=strlit("kv_run") },
{ .proc=kv_reopen_with_confirmation, .is_ui=0, .name=strlit("kv_reopen_with_confirmation") },
{ .proc=byp_reset_face_size, .is_ui=0, .name=strlit("byp_reset_face_size") },
{ .proc=project_command_F16, .is_ui=0, .name=strlit("project_command_F16") },
{ .proc=project_command_F15, .is_ui=0, .name=strlit("project_command_F15") },
{ .proc=project_command_F14, .is_ui=0, .name=strlit("project_command_F14") },
{ .proc=project_command_F13, .is_ui=0, .name=strlit("project_command_F13") },
{ .proc=project_command_F12, .is_ui=0, .name=strlit("project_command_F12") },
{ .proc=project_command_F11, .is_ui=0, .name=strlit("project_command_F11") },
{ .proc=project_command_F10, .is_ui=0, .name=strlit("project_command_F10") },
{ .proc=project_command_F9, .is_ui=0, .name=strlit("project_command_F9") },
{ .proc=project_command_F8, .is_ui=0, .name=strlit("project_command_F8") },
{ .proc=project_command_F7, .is_ui=0, .name=strlit("project_command_F7") },
{ .proc=project_command_F6, .is_ui=0, .name=strlit("project_command_F6") },
{ .proc=project_command_F5, .is_ui=0, .name=strlit("project_command_F5") },
{ .proc=project_command_F4, .is_ui=0, .name=strlit("project_command_F4") },
{ .proc=project_command_F3, .is_ui=0, .name=strlit("project_command_F3") },
{ .proc=project_command_F2, .is_ui=0, .name=strlit("project_command_F2") },
{ .proc=project_command_F1, .is_ui=0, .name=strlit("project_command_F1") },
{ .proc=project_reprint, .is_ui=0, .name=strlit("project_reprint") },
{ .proc=project_command_lister, .is_ui=0, .name=strlit("project_command_lister") },
{ .proc=project_go_to_root_directory, .is_ui=0, .name=strlit("project_go_to_root_directory") },
{ .proc=project_fkey_command, .is_ui=0, .name=strlit("project_fkey_command") },
{ .proc=load_project_current_dir, .is_ui=0, .name=strlit("load_project_current_dir") },
{ .proc=open_all_code_recursive, .is_ui=0, .name=strlit("open_all_code_recursive") },
{ .proc=open_all_code, .is_ui=0, .name=strlit("open_all_code") },
{ .proc=close_all_code, .is_ui=0, .name=strlit("close_all_code") },
{ .proc=delete_current_scope, .is_ui=0, .name=strlit("delete_current_scope") },
{ .proc=place_in_scope, .is_ui=0, .name=strlit("place_in_scope") },
{ .proc=select_prev_top_most_scope, .is_ui=0, .name=strlit("select_prev_top_most_scope") },
{ .proc=select_prev_scope_absolute, .is_ui=0, .name=strlit("select_prev_scope_absolute") },
{ .proc=select_next_scope_after_current, .is_ui=0, .name=strlit("select_next_scope_after_current") },
{ .proc=select_next_scope_absolute, .is_ui=0, .name=strlit("select_next_scope_absolute") },
{ .proc=select_surrounding_scope_maximal, .is_ui=0, .name=strlit("select_surrounding_scope_maximal") },
{ .proc=select_surrounding_scope, .is_ui=0, .name=strlit("select_surrounding_scope") },
{ .proc=clear_all_themes, .is_ui=0, .name=strlit("clear_all_themes") },
{ .proc=load_themes_hot_directory, .is_ui=0, .name=strlit("load_themes_hot_directory") },
{ .proc=toggle_fullscreen, .is_ui=0, .name=strlit("toggle_fullscreen") },
{ .proc=set_mode_to_original, .is_ui=0, .name=strlit("set_mode_to_original") },
{ .proc=toggle_mouse, .is_ui=0, .name=strlit("toggle_mouse") },
{ .proc=allow_mouse, .is_ui=0, .name=strlit("allow_mouse") },
{ .proc=suppress_mouse, .is_ui=0, .name=strlit("suppress_mouse") },
{ .proc=debug_camera_on, .is_ui=0, .name=strlit("debug_camera_on") },
{ .proc=game_disable, .is_ui=0, .name=strlit("game_disable") },
{ .proc=game_enable, .is_ui=0, .name=strlit("game_enable") },
{ .proc=goto_first_jump_same_panel_sticky, .is_ui=0, .name=strlit("goto_first_jump_same_panel_sticky") },
{ .proc=goto_first_jump, .is_ui=0, .name=strlit("goto_first_jump") },
{ .proc=goto_prev_jump_no_skips, .is_ui=0, .name=strlit("goto_prev_jump_no_skips") },
{ .proc=goto_next_jump_no_skips, .is_ui=0, .name=strlit("goto_next_jump_no_skips") },
{ .proc=comment_line_toggle, .is_ui=0, .name=strlit("comment_line_toggle") },
{ .proc=uncomment_line, .is_ui=0, .name=strlit("uncomment_line") },
{ .proc=comment_line, .is_ui=0, .name=strlit("comment_line") },
{ .proc=if0_off, .is_ui=0, .name=strlit("if0_off") },
{ .proc=open_long_braces_break, .is_ui=0, .name=strlit("open_long_braces_break") },
{ .proc=open_long_braces_semicolon, .is_ui=0, .name=strlit("open_long_braces_semicolon") },
{ .proc=open_long_braces, .is_ui=0, .name=strlit("open_long_braces") },
{ .proc=seek_end_of_textual_line, .is_ui=0, .name=strlit("seek_end_of_textual_line") },
{ .proc=seek_beginning_of_textual_line, .is_ui=0, .name=strlit("seek_beginning_of_textual_line") },
{ .proc=keyboard_macro_replay, .is_ui=0, .name=strlit("keyboard_macro_replay") },
{ .proc=keyboard_macro_finish_recording, .is_ui=0, .name=strlit("keyboard_macro_finish_recording") },
{ .proc=keyboard_macro_start_recording, .is_ui=0, .name=strlit("keyboard_macro_start_recording") },
{ .proc=word_complete_drop_down, .is_ui=0, .name=strlit("word_complete_drop_down") },
{ .proc=word_complete, .is_ui=0, .name=strlit("word_complete") },
{ .proc=list_all_substring_locations_case_insensitive, .is_ui=0, .name=strlit("list_all_substring_locations_case_insensitive") },
{ .proc=list_all_locations_case_insensitive, .is_ui=0, .name=strlit("list_all_locations_case_insensitive") },
{ .proc=list_all_substring_locations, .is_ui=0, .name=strlit("list_all_substring_locations") },
{ .proc=list_all_locations, .is_ui=0, .name=strlit("list_all_locations") },
{ .proc=set_eol_mode_from_contents, .is_ui=0, .name=strlit("set_eol_mode_from_contents") },
{ .proc=set_eol_mode_to_binary, .is_ui=0, .name=strlit("set_eol_mode_to_binary") },
{ .proc=set_eol_mode_to_lf, .is_ui=0, .name=strlit("set_eol_mode_to_lf") },
{ .proc=set_eol_mode_to_crlf, .is_ui=0, .name=strlit("set_eol_mode_to_crlf") },
{ .proc=multi_paste_interactive_quick, .is_ui=0, .name=strlit("multi_paste_interactive_quick") },
{ .proc=multi_paste_interactive, .is_ui=0, .name=strlit("multi_paste_interactive") },
{ .proc=multi_paste, .is_ui=0, .name=strlit("multi_paste") },
{ .proc=paste_next, .is_ui=0, .name=strlit("paste_next") },
{ .proc=paste, .is_ui=0, .name=strlit("paste") },
{ .proc=cut, .is_ui=0, .name=strlit("cut") },
{ .proc=copy, .is_ui=0, .name=strlit("copy") },
{ .proc=clipboard_record_clip, .is_ui=0, .name=strlit("clipboard_record_clip") },
{ .proc=kv_profile_disable_and_inspect, .is_ui=0, .name=strlit("kv_profile_disable_and_inspect") },
{ .proc=profile_clear, .is_ui=0, .name=strlit("profile_clear") },
{ .proc=profile_enable, .is_ui=0, .name=strlit("profile_enable") },
{ .proc=execute_any_cli, .is_ui=0, .name=strlit("execute_any_cli") },
{ .proc=execute_previous_cli, .is_ui=0, .name=strlit("execute_previous_cli") },
{ .proc=go_to_user_directory, .is_ui=0, .name=strlit("go_to_user_directory") },
{ .proc=load_theme_current_buffer, .is_ui=0, .name=strlit("load_theme_current_buffer") },
{ .proc=DEBUG_draw_hud_toggle, .is_ui=0, .name=strlit("DEBUG_draw_hud_toggle") },
{ .proc=view_jump_list_with_lister, .is_ui=0, .name=strlit("view_jump_list_with_lister") },
{ .proc=no_op, .is_ui=0, .name=strlit("no_op") },
{ .proc=default_view_input_handler, .is_ui=0, .name=strlit("default_view_input_handler") },
{ .proc=default_try_exit, .is_ui=0, .name=strlit("default_try_exit") },
{ .proc=write_text_and_auto_indent, .is_ui=0, .name=strlit("write_text_and_auto_indent") },
{ .proc=goto_end_of_file, .is_ui=0, .name=strlit("goto_end_of_file") },
{ .proc=goto_beginning_of_file, .is_ui=0, .name=strlit("goto_beginning_of_file") },
{ .proc=load_themes_default_folder, .is_ui=0, .name=strlit("load_themes_default_folder") },
{ .proc=save_all_dirty_buffers, .is_ui=0, .name=strlit("save_all_dirty_buffers") },
{ .proc=open_panel_hsplit, .is_ui=0, .name=strlit("open_panel_hsplit") },
{ .proc=open_panel_vsplit, .is_ui=0, .name=strlit("open_panel_vsplit") },
{ .proc=set_mark, .is_ui=0, .name=strlit("set_mark") },
{ .proc=center_view, .is_ui=0, .name=strlit("center_view") },
{ .proc=left_adjust_view, .is_ui=0, .name=strlit("left_adjust_view") },
{ .proc=move_left, .is_ui=0, .name=strlit("move_left") },
{ .proc=move_right, .is_ui=0, .name=strlit("move_right") },
{ .proc=vim_try_exit, .is_ui=0, .name=strlit("vim_try_exit") },
{ .proc=cmd_goto_random_position, .is_ui=0, .name=strlit("cmd_goto_random_position") },
{ .proc=cmd_switch_dot_arrow, .is_ui=0, .name=strlit("cmd_switch_dot_arrow") },
{ .proc=turn_game_on, .is_ui=0, .name=strlit("turn_game_on") },
{ .proc=turn_game_off, .is_ui=0, .name=strlit("turn_game_off") },
{ .proc=profile_inspect, .is_ui=1, .name=strlit("profile_inspect") },
{ .proc=vim_interactive_open_or_new, .is_ui=1, .name=strlit("vim_interactive_open_or_new") },
{ .proc=vim_theme_lister, .is_ui=1, .name=strlit("vim_theme_lister") },
{ .proc=vim_proj_cmd_lister, .is_ui=1, .name=strlit("vim_proj_cmd_lister") },
{ .proc=vim_jump_lister, .is_ui=1, .name=strlit("vim_jump_lister") },
{ .proc=interactive_switch_buffer, .is_ui=1, .name=strlit("interactive_switch_buffer") },
{ .proc=interactive_kill_buffer, .is_ui=1, .name=strlit("interactive_kill_buffer") },
{ .proc=interactive_open_or_new, .is_ui=1, .name=strlit("interactive_open_or_new") },
{ .proc=interactive_new, .is_ui=1, .name=strlit("interactive_new") },
{ .proc=interactive_open, .is_ui=1, .name=strlit("interactive_open") },
{ .proc=command_lister, .is_ui=1, .name=strlit("command_lister") },
{ .proc=theme_lister, .is_ui=1, .name=strlit("theme_lister") },
{ .proc=show_the_log_graph, .is_ui=1, .name=strlit("show_the_log_graph") },
};
