// Auto-generated by command 

//source: UNKNOWN
#if defined(STATIC_LINK_API)
function void
ed_api_fill_vtable(API_VTable_ed *vtable){
vtable->get_line_range_from_pos = get_line_range_from_pos;
vtable->buffer_replace_range = buffer_replace_range;
vtable->push_buffer_base_name = push_buffer_base_name;
vtable->get_code_directory = get_code_directory;
vtable->push_buffer_filepath = push_buffer_filepath;
vtable->get_active_view = get_active_view;
vtable->view_get_buffer = view_get_buffer;
vtable->view_get_cursor_pos = view_get_cursor_pos;
vtable->buffer_viewport_id = buffer_viewport_id;
vtable->buffer_compute_cursor = buffer_compute_cursor;
vtable->view_set_cursor = view_set_cursor;
vtable->view_set_buffer = view_set_buffer;
vtable->log_string_core = log_string_core;
vtable->log_string_spam = log_string_spam;
vtable->draw_string_oriented = draw_string_oriented;
vtable->get_string_advance = get_string_advance;
vtable->draw_set_clip = draw_set_clip;
vtable->text_layout_get_visible_range = text_layout_get_visible_range;
vtable->text_layout_character_on_screen = text_layout_character_on_screen;
vtable->get_other_primary_view = get_other_primary_view;
vtable->is_view_to_the_right = is_view_to_the_right;
vtable->DEBUG_send_entry = DEBUG_send_entry;
vtable->draw_get_target = draw_get_target;
vtable->vim_set_bottom_text = vim_set_bottom_text;
vtable->change_active_primary_view = change_active_primary_view;
vtable->push_token_lexeme = push_token_lexeme;
vtable->get_next_input = get_next_input;
vtable->draw__push_vertices = draw__push_vertices;
vtable->push_object_transform_to_target = push_object_transform_to_target;
vtable->get_token_it_on_current_line = get_token_it_on_current_line;
vtable->get_token_it_at_pos = get_token_it_at_pos;
vtable->view_set_buffer_named = view_set_buffer_named;
vtable->seek_line_col = seek_line_col;
vtable->seek_pos = seek_pos;
vtable->push_image = push_image;
vtable->ed_load_image = ed_load_image;
vtable->switch_to_mouse_panel = switch_to_mouse_panel;
vtable->get_confirmation_from_user = get_confirmation_from_user;
vtable->get_current_line_number2 = get_current_line_number2;
vtable->get_current_line_number = get_current_line_number;
vtable->system_get_path = system_get_path;
vtable->system_get_file_list = system_get_file_list;
vtable->tkarr_read = tkarr_read;
vtable->tkarr_inc = tkarr_inc;
vtable->token_it_read = token_it_read;
vtable->token_it_inc_all = token_it_inc_all;
vtable->token_it_dec_all = token_it_dec_all;
vtable->token_it_inc = token_it_inc;
vtable->token_it_dec = token_it_dec;
vtable->set_y_up = set_y_up;
vtable->target_last_config = target_last_config;
vtable->draw_new_group = draw_new_group;
vtable->draw_rect_outline = draw_rect_outline;
vtable->target_set_clip = target_set_clip;
vtable->im_begin = im_begin;
vtable->im_end = im_end;
vtable->im_textv = im_textv;
vtable->get_game_buffer = get_game_buffer;
}
#undef STATIC_LINK_API
#endif
#if defined(DYNAMIC_LINK_API)
function void
ed_api_read_vtable(API_VTable_ed *vtable){
get_line_range_from_pos = vtable->get_line_range_from_pos;
buffer_replace_range = vtable->buffer_replace_range;
push_buffer_base_name = vtable->push_buffer_base_name;
get_code_directory = vtable->get_code_directory;
push_buffer_filepath = vtable->push_buffer_filepath;
get_active_view = vtable->get_active_view;
view_get_buffer = vtable->view_get_buffer;
view_get_cursor_pos = vtable->view_get_cursor_pos;
buffer_viewport_id = vtable->buffer_viewport_id;
buffer_compute_cursor = vtable->buffer_compute_cursor;
view_set_cursor = vtable->view_set_cursor;
view_set_buffer = vtable->view_set_buffer;
log_string_core = vtable->log_string_core;
log_string_spam = vtable->log_string_spam;
draw_string_oriented = vtable->draw_string_oriented;
get_string_advance = vtable->get_string_advance;
draw_set_clip = vtable->draw_set_clip;
text_layout_get_visible_range = vtable->text_layout_get_visible_range;
text_layout_character_on_screen = vtable->text_layout_character_on_screen;
get_other_primary_view = vtable->get_other_primary_view;
is_view_to_the_right = vtable->is_view_to_the_right;
DEBUG_send_entry = vtable->DEBUG_send_entry;
draw_get_target = vtable->draw_get_target;
vim_set_bottom_text = vtable->vim_set_bottom_text;
change_active_primary_view = vtable->change_active_primary_view;
push_token_lexeme = vtable->push_token_lexeme;
get_next_input = vtable->get_next_input;
draw__push_vertices = vtable->draw__push_vertices;
push_object_transform_to_target = vtable->push_object_transform_to_target;
get_token_it_on_current_line = vtable->get_token_it_on_current_line;
get_token_it_at_pos = vtable->get_token_it_at_pos;
view_set_buffer_named = vtable->view_set_buffer_named;
seek_line_col = vtable->seek_line_col;
seek_pos = vtable->seek_pos;
push_image = vtable->push_image;
ed_load_image = vtable->ed_load_image;
switch_to_mouse_panel = vtable->switch_to_mouse_panel;
get_confirmation_from_user = vtable->get_confirmation_from_user;
get_current_line_number2 = vtable->get_current_line_number2;
get_current_line_number = vtable->get_current_line_number;
system_get_path = vtable->system_get_path;
system_get_file_list = vtable->system_get_file_list;
tkarr_read = vtable->tkarr_read;
tkarr_inc = vtable->tkarr_inc;
token_it_read = vtable->token_it_read;
token_it_inc_all = vtable->token_it_inc_all;
token_it_dec_all = vtable->token_it_dec_all;
token_it_inc = vtable->token_it_inc;
token_it_dec = vtable->token_it_dec;
set_y_up = vtable->set_y_up;
target_last_config = vtable->target_last_config;
draw_new_group = vtable->draw_new_group;
draw_rect_outline = vtable->draw_rect_outline;
target_set_clip = vtable->target_set_clip;
im_begin = vtable->im_begin;
im_end = vtable->im_end;
im_textv = vtable->im_textv;
get_game_buffer = vtable->get_game_buffer;
}
#undef DYNAMIC_LINK_API
#endif
