//-
function Meta_Printer
m_open_file_to_write(Stringz path,
                     const char *call_file=__builtin_FILE(),
                     u32 call_line=__builtin_LINE())
{
 Meta_Printer p = {};
 FILE *file = open_or_create_file(path, "wb");
 if(file){
  meta_logf("Writing to file %.*s\n", strexpand(path));
  (Printer&)p = make_printer_file(file);
  p<"//NOTE Generated by "<call_file<':'<call_line<":\n";
 }else{
  p.error = true;
  meta_logf("Failed to open file %.*s\n with errno: %d\n", strexpand(path), errno);
 }
 return p;
}
function Printer_Pair
m_open_files_to_write(String base_path,
                      const char *call_file=__builtin_FILE(),
                      u32 call_line=__builtin_LINE()){
 Scratch_Block scratch;
 Stringz outname_c, outname_h;
 {
  Printer p = make_printer_buffer(scratch, base_path.len+3);
  p<base_path<".h";
  outname_h = printer_get_string(p);
 }
 {
  Printer p = make_printer_buffer(scratch, base_path.len+5);
  p<base_path<".cpp";
  outname_c = printer_get_string(p);
 }
 Printer_Pair result = {};
 result.h = m_open_file_to_write(outname_h);
 result.c = m_open_file_to_write(outname_c);
 if(FILE *hfile = result.h.FILE){
  result.h<"#pragma once\n";
 }
 return result;
}
inline void
m_close_pair(Printer_Pair &ps){
 fclose(ps.h.FILE);
 fclose(ps.c.FILE);
}
//-
function Meta_Type_Names &
m_get_type_names(String type_name){
 auto &store = meta_type_name_store;
 for_i32(index,0,store.count){
  if(store[index].type_name == type_name){
   return store[index];
  }
 }
 
 //Note(kv) not found
 auto arena = &meta_permanent_arena;
 Meta_Type_Names *new_item = store.push();
 *new_item = {
  .type_name          = push_string(arena, type_name),
  .info_function_name = push_stringf(arena, "get_type_info_%.*s", strexpand(type_name)),
  .global_info_name   = push_stringf(arena, "Type_Info_%.*s",     strexpand(type_name)),
  .read_function_name = push_stringf(arena, "read_binary_%.*s",   strexpand(type_name)),
 };
 return *new_item;
}
inline String
get_type_global_info_name(String type_name){
 return m_get_type_names(type_name).global_info_name;
}
inline String
get_type_read_function_name(String type_name){
 return m_get_type_names(type_name).read_function_name;
}
inline String
get_type_info_function_name(String type_name){
 return m_get_type_names(type_name).info_function_name;
}
//TODO(kv) We're not printing out the type info,
//  because that uses arena and we're messing with shared memory arenas.
function void
print_type_meta_shared(Printer &p, String type_name, b32 is_typedef=false)
{
 m_meta_only(p);
  String type_global_var = get_type_global_info_name(type_name);
 {//TODO(kv) Let's see if this explodes...
  m_location;
  print_format(p, "global Type_Info %.*s = get_type_info_%.*s();\n\n",
               strexpand(type_global_var), strexpand(type_name));
 }
 if(!is_typedef){
  // NOTE: Overload to automatically get the type info from a pointer of that type
  p<"function Type_Info *type_info_from_pointer("<type_name<"*pointer)";
  m_braces_newline{
   p < "return &" < type_global_var < ";";
  }
 }
}
function void
print_type_read_function_prototype(Printer &p, String type_name){
 p < "function void\n";
 p < get_type_read_function_name(type_name) <
  "(Binary_Reader *r, " < type_name < " *dst)";
}
function void
print_union_read_function_prototype(Printer &p, String type_name, String discriminator_type){
 p <"function void\n" <
  get_type_read_function_name(type_name) <
  "(Binary_Reader *r, " <
  type_name <" *dst, " <
  discriminator_type <" variant" <")";
}
function void
print_type_info_function_prototype(Printer &p, String type_name){
 String function_name = get_type_info_function_name(type_name);
 p <"function Type_Info\n" <function_name <"()";
}
function void
print_type_and_name(Printer &p, Parsed_Type &type, String name){
 //NOTE(kv) I cannot figure out how to print generic C type, Jesus man!
 switch(type.kind){
  case Parsed_Type_Pointer:{
   p < type.name < " " < repeated("*", type.pointer_count) < name;
  }break;
  case Parsed_Type_Array:{
   p < type.name < " " < name < "[" < type.array_count_str < "]";
  }break;
 }
}
function void
print_struct_member(Printer &p, M_Struct_Member &member){
 print_type_and_name(p, member.type, member.name);
}
function void
print_struct(Printer &p, String type_name, M_Struct_Members &members, b32 is_packed=false)
{
 if(is_packed) p<"PACK_BEGIN\n";
 p<"struct "<type_name;
 m_braces{
  mline(p);
  for_i32(i,0,members.count){
   auto &member = members[i];
   if(!member_was_removed(member)){
    if(i!=0){ mline(p); }
    print_struct_member(p, member);
    p<";";
   }
  }
  mline(p);
 }
 if(is_packed) {mline(p); p<"PACK_END";}
 p<";";
 mline(p);
}


function void
print_struct_meta(Printer &p, String type_name,
                  M_Struct_Members &members)
{
 Scratch_Block scratch;
 {
  m_meta_only(p);
  //-NOTE ("Function to generate the type info")
  String function_name = get_type_info_function_name(type_name);
  m_location;
  p<"function Type_Info\n"<function_name<"()";
  m_braces_newline{
   p<"Type_Info result = {};\n";
   p<"result.name = "<enclosed_in_strlit(type_name) < ";\n";
   p<"result.size = sizeof("<type_name<");\n";
   p<"result.kind = I_Type_Kind_Struct;\n";
   // NOTE(kv) Computing member count
   i32 member_count = 0;
   for_i32(raw_member_index,0,members.count){
    if(not member_was_removed(members.get(raw_member_index))){
     member_count++;
    }
   }
   
   p < "result.members.set_count(" < member_count < ");\n";
   i32 member_index = 0;
   for_i1(raw_member_index,0,members.count){
    M_Struct_Member &member = members.get(raw_member_index);
    if(not member_was_removed(member)){
     m_braces_newline{
      {//-Member type
       if(member.type.kind == Parsed_Type_Array){
        //NOTE(kv) Array type -> Must create it on the fly
        //TODO(kv) Just use malloc, because arenas might be exist yet...
        //  maybe we can make another arena type that works off a static pool?
        print(p, "local_persist Type_Info member_type_value;\n");
        print(p, "Type_Info *member_type = &member_type_value;\n");
        print(p, "*member_type = {};\n");
        String item_type_info = get_type_global_info_name(member.type.name);
        //NOTE(kv) Made-up array type name
        print_format(p, "member_type->name = strlit(\"%.*s[%d]\");\n",
                     strexpand(member.type.name), member.type.array_count);
        print_format(p, "member_type->kind = I_Type_Kind_Array;\n");
        print_format(p, "member_type->size = %d * %.*s.size;\n",
                     member.type.array_count, strexpand(item_type_info));
        print_format(p, "member_type->array_item_type = & %.*s;\n",
                     strexpand(item_type_info));
        print_format(p, "member_type->count = %d;\n", member.type.array_count);
       }else{
        //NOTE(kv) Normal type
        print_format(p, "Type_Info *member_type = & %.*s;\n",
                     strexpand(get_type_global_info_name(member.type.name)));
       }
      }
      p<"result.members["<member_index<"] = "<
       "{.type=member_type"<
       ", .name="<enclosed_in_strlit(member.name)<
       ", .offset=offsetof("<type_name<", "<member.name<")";
      if(member.discriminator.len){
       p<", .discriminator_offset=offsetof("<type_name<", "<member.discriminator<")";
      }
      if(member.unserialized){
       p<", .unserialized=true";
      }
      p<"};";
     }
     member_index++;
    }
   }
   
   p < "return result;";
  }
 }
 
 print_type_meta_shared(p, type_name);
 
 {//-;meta_read_struct
  m_meta_only(p);
  //NOTE(kv) metaprogramming is weird and janky, but deserializign at runtime
  //  has its runtime cost, and we have to expose the RTTI data which is only
  //  used for this very purpose.
  m_location;
  print_type_read_function_prototype(p,type_name);
  m_braces_newline{
   for_i1(member_index,0,members.count){
    M_Struct_Member &member = members.get(member_index);
    if(not member.unserialized){
     String version_added = member.version_added;
     b32 has_version_added = version_added.len != 0;
     if(!has_version_added){ version_added = strlit("0"); }
     String version_removed = member.version_removed;
     b32 has_version_removed = version_removed.len != 0;
     if(!has_version_removed){ version_removed = strlit("Version_Inf"); }
     String default_value = member.default_value;
     b32 has_default = default_value.len != 0;
     if(!has_default){ default_value = strlit("{}"); }
     
     b32 member_currently_exists = !has_version_removed;
     //NOTE(kv) Mangle the name so that we don't have conflict with other local vars.
     String varname = push_stringf(scratch, "m_%.*s", strexpand(member.name));
     
     {//NOTE(kv) Make a local variable to store the value, for
      //  1. convenience, and
      //  2. the struct might not have that member anymore,
      //     but we may need that value for conversion purpose.
      print_type_and_name(p, member.type, varname);
      p<" = "<default_value<";\n";
     }
     
     if(has_version_added || has_version_removed)
     {// NOTE(kv) Only read if the data has that member.
      p < "if ( in_range_exclusive(" <
       version_added < ", r.read_version, " < version_removed < ") )";
     }
     m_braces_newline{//NOTE(kv) Read data to the local var
      //NOTE(kv) cheese!
      String read_function = get_type_read_function_name(member.type.name);
      b32 has_disciminator = member.discriminator.len != 0;
      if(has_disciminator){
       p<read_function<"(r, &"<varname<", dst->"<member.discriminator<");";
      }else{
       if(member.type.kind == Parsed_Type_Array){
        //-Read array
        for_u32(i,0,member.type.array_count){
         p < read_function < "(r, &" < varname < "["<i<"]);";
        }
       }else{
        //-Read normal type
        p<read_function<"(r, &"<varname<");";
       }
      }
     }
     if(member_currently_exists){
      //NOTE(kv) Assign the local var to the dest struct member.
      if(member.type.kind == Parsed_Type_Array){
       p<"copy_array_dst(dst->"<member.name<", "<varname<");\n\n";
      }else{
       p<"dst->"<member.name<" = "<varname<";\n\n";
      }
     }
    }
   }
  }
 }
}
function void
print_union_meta(Printer &p, String type_name,
                 darray(Union_Variant) *variants,
                 String discriminator_type)
{
 m_meta_only(p);
#define brace_block  p < "\n{\n"; defer( p < "\n}\n"; );
 {//-Function to generate the type info
  {
   m_location;
   p<"union "<type_name<";\n";
   print_type_info_function_prototype(p,type_name);
   p<";\n";
  }
  {
   m_location;
   print_type_info_function_prototype(p,type_name);
   {brace_block;
    p < "Type_Info result = {};\n" <
     "result.name = "<enclosed_in_strlit(type_name)<";\n" <
     "result.size = sizeof("<type_name<");\n"<
     "result.kind = I_Type_Kind_Union;\n"<
     "result.discriminator_type = &"<get_type_global_info_name(discriminator_type)<";\n";
    {
     p<"result.union_members.set_count("<variants->count<");\n";
     for_i32(index,0,variants->count){
      auto &variant = variants->get(index);
      String variant_type = get_type_global_info_name(variant.struct_name);
      p<"result.union_members["<index<"] = {"<
       ".type=&"<variant_type<", "<
       ".name="<enclosed_in_strlit(variant.name)<", "<
       ".variant="<variant.enum_name<
       "};\n";
     }
    }
    p<"return result;";
   }
  }
 }
 
 print_type_meta_shared(p, type_name);
 
 {// NOTE: ;read union
  {
   m_location;
   print_union_read_function_prototype(p,type_name,discriminator_type);
   
   {
    brace_block;
    //NOTE(kv) When we add/remove union members, this is gonna get complicated,
    //  but right now I don't care.
    p<"switch(variant)";
    {brace_block;
     for_i1(vi,0,variants->count){
      auto &variant = variants->get(vi);
      p<"case "<variant.enum_name<":";
      {brace_block;
       p<get_type_read_function_name(variant.struct_name)<
        "(r, "<"&dst->"<variant.name_lower<");\n"<
        "break;";
      }
     }
    }
   }
  }
 }
#undef brace_block
}
function void
print_enum(Printer &p, String type_name,
           darray(String) &enum_names,
           darray(i32)    &enum_vals){
 m_location;
 p <"enum " <type_name;
 m_braces_sm{
  for_i32(ei,0,enum_names.count){
   if(ei!=0){ p <"\n"; }
   p <enum_names[ei] <" = " <enum_vals[ei] <",";
  }
 }
 print(p, "\n");
}
function void
print_enum_meta(Printer &p, String type_name,
                darray(String) &enum_names)
{
 m_meta_only(p);
 {//-NOTE: ("Function to generate the type info")
  String function_name = get_type_info_function_name(type_name);
  {//NOTE .h
   m_location;
   p <"function Type_Info\n" <function_name <"();";
  }
  {//NOTE .cpp
   m_location;
   p <"function Type_Info\n" <function_name <"()";
   m_braces_newline{
    p <"Type_Info result = {};\n";
    p <"result.name = " <enclosed_in_strlit(type_name) <";\n";
    p <"result.size = sizeof(" <type_name <");\n";
    p <"result.kind = I_Type_Kind_Enum;\n";
    p <"result.enum_members.set_count(" <enum_names.count <");\n";
    for_i1(enum_index,0,enum_names.count){
     String name = enum_names.get(enum_index);
     p <"result.enum_members[" <enum_index <"] = " <
      "{.name=" <enclosed_in_strlit(name) <", " <
      ".value=" <name <  //NOTE(kv) Let the compiler fill out the value.
      "};\n";
    }
    p <"return result;";
   }
  }
 }
 
 print_type_meta_shared(p, type_name);
 
 {// NOTE: meta_read
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   p <";\n";
  }
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   m_braces_newline{
    // NOTE(kv): @meta_introspect_enum_size
    //   If the type size is too BIG, we'll read past from wrong address.
    p < "i32 integer;" < "\n" <
     "read_binary_i1(r, &integer);" < "\n" <
     "*dst = *("  < type_name  < "*)(&integer);";
   }
  }
 }
 
 {// NOTE ;meta_introspect_enum_size
  p  < "static_assert( sizeof("  < type_name  < ") <= sizeof(i32) );\n\n";
 }
}
function void
print_typedef_meta(Printer &p, String type_name, String typedef_to)
{
 m_meta_only(p);
 {//-Function to generate type info
  String function_name = get_type_info_function_name(type_name);
#define PROTOTYPE  p < "function Type_Info\n" < function_name < "()"
  {
   m_location;
   PROTOTYPE<";";
  }
  {
   m_location;
   PROTOTYPE;
   m_braces_newline{
    p<"Type_Info result = "<get_type_global_info_name(typedef_to)<";\n";
    p<"result.name = "<enclosed_in_strlit(type_name)<";\n";
    p < "return result;\n";
   }
  }
#undef PROTOTYPE
 }
 print_type_meta_shared(p, type_name, true);
 {//-meta read
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   p<";\n";
  }
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   m_braces_newline{
    p < get_type_read_function_name(typedef_to) < "(r, dst);";
   }
  }
 }
}
function void
print_struct_embed(Printer &p, String type_name,
                   darray(M_Struct_Member) &members)
{
 m_location;
 p <"#define " <type_name <"_Embed \\\n union";
 m_macro_braces_sm{
  p <"struct";
  m_macro_braces_sm{
   for_i1(imem, 0, members.count){
    auto &member = members[imem];
    print_struct_member(p, member);
    p<";\\\n";
   }
  }
  p <type_name <" " <type_name <";";
 }
}
function void
print_i1_wrapper(Printer &p, String type_name){
 Scratch_Block scratch;
 M_Struct_Members members = parse_struct_body(scratch, "{ i1 v; }");
 {
  print_format(p, "struct %.*s { i1 v; };\n", strexpand(type_name));
  p <"inline b32 operator==(" < type_name <" a, " < type_name <" b)" <
   "{ return a.v==b.v; }\n";
 }
 print_struct_meta(p, type_name, members);
}
myinline void
print_i1_wrapper(Printer &p, char *type_name){
 print_i1_wrapper(p, SCu8(type_name));
}
//-
function b32
op_needs_space(Unary_Operator op)
{
 u32 op_u32 = op_to_u32_little_endian(op);
 switch(op_u32){
  case 'not':
  return true;
 } 
 return false;
}
function b32
op_needs_space(Binary_Operator op)
{
 u32 op_u32 = op_to_u32_little_endian(op);
 switch(op_u32){
  case '.':
  case '->':
  return false;
 }
 return true;
}
function void
print_expression2(Printer &p, Precedence outer_precedence, Meta_Expression *e){
 switch(e->kind){
  case Expression_Kind_None:
  break;
  
  default: {
   kv_assert(e->as_string.count != 0);
   print(p, e->as_string);
  }break;
  
  case Expression_Kind_Unary:{
   Expression_Unary *unary = &e->unary;
   String op_str = to_string(&unary->op);
   Precedence precedence = precedence_of(unary->op);
   b32 needs_space = op_needs_space(unary->op);
   
   if(is_prefix(unary->op)){
    print(p, op_str);
    if(needs_space) print(p, ' ');
    print_expression2(p, precedence, unary->argument);
   }else{
    //NOTE postfix
    print_expression2(p, precedence, unary->argument);
    if(needs_space) print(p, ' ');
    print(p, op_str);
   }
  }break;
  
  case Expression_Kind_Binary:{
   Expression_Binary *binary = &e->binary;
   Precedence precedence = precedence_of(binary->op);
   b32 has_parens = precedence > outer_precedence;
   b32 has_space = op_needs_space(binary->op) ;
   String op_str = to_string(&binary->op);
   
   if(has_parens){ print(p, '('); }
   print_expression2(p, precedence, binary->lhs);
   if(has_space){ print(p, ' '); }
   print(p, op_str);
   if(has_space){ print(p, ' '); }
   print_expression2(p, precedence, binary->rhs);
   if(has_parens){ print(p, ')'); }
  }break;
  
  case Expression_Kind_Call:{
   Expression_Call *call = &e->call;
   print_expression2(p, Precedence_Dot_Arrow, call->func);
   m_parens2(p){
    for_i32(arg_index, 0, call->arguments.count){
     if(arg_index){ p<", "; }
     print_expression2(p, Precedence_Max, &call->arguments[arg_index]);
    }
   }
  }break;
  
  case Expression_Kind_Array_Subscript:{
   Expression_Array_Subscript *subscript = &e->array_subscript;
   print_expression2(p, Precedence_Dot_Arrow, subscript->array);
   print(p, '[');
   print_expression2(p, Precedence_Max, subscript->index);
   print(p, ']');
  }break;
  
  case Expression_Kind_Compound:{
   print_brace_block(p){
    for_i32(i, 0, e->compound_items.count){
     
     if(i != 0){ print(p, strlit(", ")); }
     Compound_Item *item = e->compound_items.items + i;
     print_expression2(p, Precedence_Max, &item->value);
    }
   }
  }break;
 }
}
function void
print_expression(Printer &p, Meta_Expression *e)
{
 print_expression2(p, Precedence_Max, e);
}
function void
print(Meta_Printer &p, Statement_Head &statement)
{
 add_to_source_map(p.source_map, p, statement.pos);
 switch(statement.kind){
  case Statement_Kind_None: break;
  case Statement_Kind_Unknown:{
   Statement_Unknown &unknown = (Statement_Unknown &)statement;
   print(p, unknown.unknown);
  }break;
  case Statement_Kind_Return:{
   cast_to_var(Statement_Return&, return0, statement);
   print(p, "return ");
   print_expression(p, &return0.return0);
   print(p, ";");
  }break;
  case Statement_Kind_Expression:{
   cast_to_var(Statement_Expression&, expr, statement);
   print_expression(p, &expr.expression);
   p < ";";
  }break;
  case Statement_Kind_Block:{
   cast_to_var(Statement_Block &, block, statement);
   p < "{";
   for_i32(statement_index,0,block.block.count){
    p < "\n"; 
    print(p, (Statement_Head&)block.block[statement_index]);
   }
   p<"\n}";
  }break;
  case Statement_Kind_Header_And_Body:{
   cast_to_var(Statement_Header_And_Body &, header_body, statement);
   p < header_body.header;
   print(p, *header_body.body);
  }break;
  case Statement_Kind_If:{
   cast_to_var(Statement_If &, if0, statement);
   p < "if(";
   print_expression(p, &if0.condition);
   p < ")";
   print(p,*if0.body);
   if(if0.else0){
    p < "else ";
    print(p, *if0.else0);
   }
  }break;
  case Statement_Kind_Switch:{
   cast_to_var(Statement_Switch &, switch0, statement);
   p < "switch(";
   print_expression(p, &switch0.expression);
   p < ")";
   {
    p < "{";
    for_i32(case_index,0,switch0.cases.count){
     Switch_Case &case0 = switch0.cases[case_index];
     p < "\ncase ";
     print_expression(p, &case0.expression);
     p < ": ";
     print(p, case0.body.head);
     p < (case0.break_after ? " break;" : "");
    }
    p < "\n}";
   }
  }break;
  
  case Statement_Kind_Declaration:{
   cast_to_var(Statement_Declaration &, decl, statement);
   print_type_and_name(p, decl.type, decl.name);
   if(decl.rhs.kind){
    //-Assignment included
    p < " = ";
    print_expression(p, &decl.rhs);
   }
   p<";";
  }break;
  
  case Statement_Kind_Cache:{
   cast_to_var(Statement_Cache &, cache0, statement);
#define CACHE_NAME cache_storage_prefix<cache0.id
   for_i32(item_index, 0, cache0.cache_items.count){
    //-Computing cache values
    Cache_Item &cache_item = cache0.cache_items[item_index];
    print_type_and_name(p, cache_item.type, cache_item.name);
    p < " = ";
    print_expression(p, &cache_item.rhs);
    p < ";\n";
   }
   p < "if"; m_parens{
    //-Condition for a cache miss
    p<"not "<CACHE_NAME<".cache_initialized or\n";
    p<"not"; m_parens{
     for_i32(item_index, 0, cache0.cache_items.count){
      String name = cache0.cache_items[item_index].name;
      p<name<" == "<CACHE_NAME<"."<name<" &&\n";
     }
     p<"true";
    }
   }
   m_braces_newline{
    //-Do computation if cache miss
    m_braces_newline{//-Recompute the cache
     p<CACHE_NAME<".cache_initialized = true;\n";
     for_i32(item_index, 0, cache0.cache_items.count){
      if(item_index){ p<"\n"; }
      String name = cache0.cache_items[item_index].name;
      p<CACHE_NAME<"."<name<" = "<name<";";
     }
    }
    p<"\n";
    {//-Redo the computation
     print(p, *cache0.body);
    }
   }
#undef CACHE_NAME
  }break;
  case Statement_Kind_Empty:{
   p<";";
  }break;
  invalid_default_case;
 }
}
function String
print_expression(Arena *arena, Meta_Expression *expression)
{
 usize cap = 256;
 Printer printer = make_printer_buffer(arena, cap);
 print_expression(printer, expression);
 String result = printer_get_string(printer);
 kv_assert(result.count <= cap);
 arena_pop_size(arena, cap - result.count);
 return result;
}
function void
print_template(Printer &printer, String format, String *args, u32 argc)
{
 u32 current_arg = 0;
 for_u32(i, 0, format.count){
  u8 c = format.str[i];
  b32 is_percent = (c == '%');
  if(is_percent){
   u32 arg_index = current_arg++;
   kv_assert(arg_index < argc);
   String arg = args[arg_index];
   print(printer, arg);
  }else{
   print(printer, c);
  }
 }
 kv_assert(current_arg == argc);
}
#define PrintTemplate(printer, format, array) \
print_template(printer, format, ArrayAndCount(array))

function b32
klang_print_sliders(K_Slider *sliders, u32 slider_count)
{
 Scratch_Block scratch;
 b32 ok = true;
 
 //-Information at the front
 Stringz outpath = pjoin(scratch, meta_dirs.game_gen, strlit("sliders0.gen.h"));
 Meta_Printer printer = m_open_file_to_write(outpath);
 
 print_format(printer, "#define FUI_SLIDER_COUNT %u\n", slider_count);
 
 {//-The infos
  print(printer, "global Slider global_sliders[FUI_SLIDER_COUNT] = {\n");
  {
   char *create_slider_info_c = R"CODE(
 {.type = Basic_Type_%, .pos = %, .size = %, .index = %, .options = %},)CODE";
   String create_slider_info = SCu8(create_slider_info_c);
   
   Scratch_Block scratch_loop;
   for_u32(slider_index, 0, slider_count)
   {
    K_Slider *slider = sliders + slider_index;
#define S(whatever) to_string(scratch_loop, whatever)
    String options = slider->options;
    if(options.count == 0){
     options = strlit("{}");
    }
    String vars[] = {
     slider->type, S(slider->pos), S(slider->size), S(slider_index), options
    };
#undef S
    PrintTemplate(printer, create_slider_info, vars);
    arena_clear(scratch_loop);
   }
  }
  print(printer, "};\n\n");
 }
 
 {//-The meat
  print(printer, "global void *global_slider_values[FUI_SLIDER_COUNT];\n\n");
  
  print(printer, "function void\n");
  print(printer, "init_sliders(Arena *arena)\n");
  
  print(printer, "{\n");
  {
   char *create_slider_template_c =
   R"CODE(global_slider_values[%] = push_value(arena, %);
   )CODE";
   String create_slider_template = SCu8(create_slider_template_c);
   
   Scratch_Block scratch_loop;
   for_u32(slider_index_int, 0, slider_count)
   {
    K_Slider *slider = sliders + slider_index_int;
    String type = slider->type;
#define S(whatever) to_string(scratch_loop, whatever)
    String slider_index = S(slider_index_int);
    String vars[] = {
     slider_index, slider->value,
    };
#undef S
    PrintTemplate(printer, create_slider_template, vars);
    arena_clear(scratch_loop);
   }
  }
  print(printer, "}\n");
 }
 
 kv_assert(not printer.error);
 close_file(printer);
 return ok;
}
//-