//-
//-NOTE(kv) ;stupid_cpp_zero_array
// Due to C++, we can't make zero-sized array.
// So we clamp the size to 1 by default.
// As long as we don't use those arrays directly, we're good.
// and we shouldn't use those directly anyway,
// instead wrapping them in our own array type.
//-

function void
print_global_variable_jumper(Printer &printer, String name)
{
 print(printer, "#if 0\n");
 printf(printer, "jump %S;\n", name);
 print(printer, "#endif\n");
}
function Meta_Printer
m_open_file_to_write(Stringz path, String source_path={},
                     const char *call_file=__builtin_FILE(),
                     u32 call_line=__builtin_LINE())
{// NOTE(kv) Doesn't really have to return Meta_Printer,
 // but we just do it for convenience.
 Meta_Printer p = {};
 FILE *file = open_or_create_file(path, "wb");
 if(file)
 {
  meta_logf("Writing to file %.*s\n", strexpand(path));
  (Printer&)p = make_printer_file(file);
  p<"// NOTE Generated by "<call_file<':'<call_line<":\n";
  if(not_empty(source_path))
  {
   printf(p, "//NOTE source: %S\n", source_path);
  }
 }
 else
 {
  p.error = true;
  meta_logf("Failed to open file %.*s\n with errno: %d\n", strexpand(path), errno);
 }
 return p;
}
function Printer_Pair
m_open_files_to_write(String base_path,
                      const char *call_file=__builtin_FILE(),
                      u32 call_line=__builtin_LINE())
{
 Scratch_Block scratch;
 Stringz outname_c, outname_h;
 {
  Printer p = make_printer_buffer(scratch, base_path.len+3);
  p<base_path<".h";
  outname_h = printer_get_string(p);
 }
 {
  Printer p = make_printer_buffer(scratch, base_path.len+5);
  p<base_path<".cpp";
  outname_c = printer_get_string(p);
 }
 Printer_Pair result = {};
 result.h = m_open_file_to_write(outname_h);
 result.c = m_open_file_to_write(outname_c);
 if(FILE *hfile = result.h.FILE){
  result.h<"#pragma once\n";
 }
 return result;
}
myinline void
m_close_pair(Printer_Pair &ps)
{
 fclose(ps.h.FILE);
 fclose(ps.c.FILE);
}
//-
function Meta_Type_Names &
m_get_type_names(String type_name)
{
 auto &store = meta_type_name_store;
 for_i32(index,0,store.count){
  if(store[index].type_name == type_name){
   return store[index];
  }
 }
 
 //Note(kv) not found
 Arena *arena = &thread_permanent_arena;
 Meta_Type_Names *new_item = store.push();
 *new_item = {
  .type_name          = push_string(arena, type_name),
  .info_function_name = push_stringf(arena, "get_type_info_%S", type_name),
  .global_info_name   = push_stringf(arena, "Type_Info_%S",     type_name),
  .read_function_name = push_stringf(arena, "read_binary_%S",   type_name),
 };
 return *new_item;
}
myinline String
get_type_global_info_name(String type_name){
 return m_get_type_names(type_name).global_info_name;
}
myinline String
get_type_read_function_name(String type_name){
 return m_get_type_names(type_name).read_function_name;
}
myinline String
get_type_info_function_name(String type_name){
 return m_get_type_names(type_name).info_function_name;
}
//TODO(kv) We're not printing out the type info,
//  because that uses arena and we're messing with shared memory arenas.
function void
print_type_meta_shared(Printer &p, String type_name, b32 is_typedef=false)
{
 m_meta_only(p);
 String type_global_var = get_type_global_info_name(type_name);
 {
  m_location;
  printf(p, "global Type_Info %S;\n\n", type_global_var);
 }
 if(!is_typedef){
  // NOTE: Overload to automatically get the type info from a pointer of that type
  p<"function Type_Info *type_info_from_pointer("<type_name<"*pointer)";
  m_braces_newline{
   p < "return &" < type_global_var < ";";
  }
 }
}
function void
print_type_read_function_prototype(Printer &p, String type_name){
 p < "function void\n";
 p < get_type_read_function_name(type_name) <
  "(Binary_Reader *r, " < type_name < " *dst)";
}
function void
print_union_read_function_prototype(Printer &p, String type_name, String discriminator_type){
 p <"function void\n" <
  get_type_read_function_name(type_name) <
  "(Binary_Reader *r, " <
  type_name <" *dst, " <
  discriminator_type <" variant" <")";
}
function void
print_type_info_function_prototype(Printer &p, String type_name){
 String function_name = get_type_info_function_name(type_name);
 p <"function Type_Info\n" <function_name <"()";
}
function void
print_type_and_name(Printer &p, Parsed_Type const&type, String name)
{// NOTE(kv) I cannot figure out how to print generic C type, Jesus man!
 if(type.flags & Parsed_Type_IsConst)
 {
  print(p, "const ");
 }
 
 switch(type.kind)
 {
  case Parsed_Type_Pointer:
  {
   p < type.name < " " < repeated("*", type.pointer_count) < name;
  }break;
  
  case Parsed_Type_Array:
  {
   p < type.name < " " < name < "[" < type.array_count < "]";
  }break;
  
  case Parsed_Type_Reference:{
   printf(p, "%S &%S", type.name, name);
  }break;
  
  case Parsed_Type_Function:
  {
   print(p, "<TODO we don't know how to print function type>");
  }break;
 }
}
myinline void
print_type_and_name(Printer &p, Type_And_Name const&type_and_name)
{
 print_type_and_name(p, type_and_name.type, type_and_name.name);
}

function void
print_struct_member(Printer &p, M_Struct_Member &member)
{
 print_type_and_name(p, member.type, member.name);
}
function void
print_struct(Printer &p, String type_name, M_Struct_Members &members, b32 is_packed=false)
{
 if(is_packed) p<"PACK_BEGIN\n";
 p<"struct "<type_name;
 m_braces{
  mline(p);
  for_i32(i,0,members.count){
   auto &member = members[i];
   if(!member_was_removed(member)){
    if(i!=0){ mline(p); }
    print_struct_member(p, member);
    p<";";
   }
  }
  mline(p);
 }
 if(is_packed) {mline(p); p<"PACK_END";}
 p<";";
 mline(p);
}
function void
print_struct_info(Printer &p, String type_name, M_Struct_Members &members)
{
 Scratch_Block scratch;
 {
  m_meta_only(p);
  m_location;
  //-NOTE ("Function to generate the type info")
  String function_name = get_type_info_function_name(type_name);
  p<"function Type_Info\n"<function_name<"()";
  m_braces_newline
  {
   p<"Type_Info result = {};\n";
   p<"result.name = "<enclosed_in_strlit(type_name) < ";\n";
   p<"result.size = sizeof("<type_name<");\n";
   p<"result.kind = I_Type_Kind_Struct;\n";
   // NOTE(kv) Computing member count
   i32 member_count = 0;
   for_i32(raw_member_index,0,members.count)
   {
    if(not member_was_removed(members.get(raw_member_index)))
    {
     member_count++;
    }
   }
   
   p < "result.members.set_count(" < member_count < ");\n";
   i32 member_index = 0;
   for_i32(raw_member_index,0,members.count)
   {
    M_Struct_Member &member = members.get(raw_member_index);
    if(not member_was_removed(member))
    {
     m_braces_newline
     {
      {//-Member type
       if(member.type.kind == Parsed_Type_Array){
        //NOTE(kv) Array type -> Must create it on the fly
        //TODO(kv) Just use malloc, because arenas might be exist yet...
        //  maybe we can make another arena type that works off a static pool?
        print(p, "local_persist Type_Info member_type_value;\n");
        print(p, "Type_Info *member_type = &member_type_value;\n");
        print(p, "*member_type = {};\n");
        String item_type_info = get_type_global_info_name(member.type.name);
        //NOTE(kv) Made-up array type name
        String array_count = member.type.array_count;
        printf(p, "member_type->name = strlit(\"%.*s[%S]\");\n",
               strexpand(member.type.name), array_count);
        printf(p, "member_type->kind = I_Type_Kind_Array;\n");
        printf(p, "member_type->size = %S * %.*s.size;\n",
               array_count, strexpand(item_type_info));
        printf(p, "member_type->array_item_type = & %.*s;\n",
               strexpand(item_type_info));
        printf(p, "member_type->count = %S;\n", array_count);
       }else{
        //NOTE(kv) Normal type
        printf(p, "Type_Info *member_type = & %.*s;\n",
               strexpand(get_type_global_info_name(member.type.name)));
       }
      }
      p<"result.members["<member_index<"] = "<
      "{.type=member_type"<
      ", .name="<enclosed_in_strlit(member.name)<
      ", .offset=offsetof("<type_name<", "<member.name<")";
      if(member.discriminator.len){
       p<", .discriminator_offset=offsetof("<type_name<", "<member.discriminator<")";
      }
      if(member.unserialized){
       p<", .unserialized=true";
      }
      p<"};";
     }
     member_index++;
    }
   }
   
   p < "return result;";
  }
 }
 
 print_type_meta_shared(p, type_name);
 
 {//-;meta_read_struct
  m_meta_only(p);
  //NOTE(kv) metaprogramming is weird and janky, but deserializign at runtime
  //  has its runtime cost, and we have to expose the RTTI data which is only
  //  used for this very purpose.
  m_location;
  print_type_read_function_prototype(p,type_name);
  m_braces_newline
  {
   for_i32(member_index,0,members.count)
   {
    M_Struct_Member &member = members.get(member_index);
    if(not member.unserialized)
    {
     String version_added = member.version_added;
     b32 has_version_added = version_added.len != 0;
     if(!has_version_added){ version_added = strlit("0"); }
     String version_removed = member.version_removed;
     b32 has_version_removed = version_removed.len != 0;
     if(!has_version_removed){ version_removed = strlit("Version_Inf"); }
     String default_value = member.default_value;
     b32 has_default = default_value.len != 0;
     if(!has_default){ default_value = strlit("{}"); }
     
     b32 member_currently_exists = !has_version_removed;
     //NOTE(kv) Mangle the name so that we don't have conflict with other local vars.
     String varname = push_stringf(scratch, "m_%.*s", strexpand(member.name));
     
     {//NOTE(kv) Make a local variable to store the value, for
      //  1. convenience, and
      //  2. the struct might not have that member anymore,
      //     but we may need that value for conversion purpose.
      print_type_and_name(p, member.type, varname);
      p<" = "<default_value<";\n";
     }
     
     if(has_version_added || has_version_removed)
     {// NOTE(kv) Only read if the data has that member.
      p < "if ( in_range_exclusive(" <
      "r->read_version, " < version_added < ", " < version_removed < ") )";
     }
     m_braces_newline{//NOTE(kv) Read data to the local var
      //NOTE(kv) cheese!
      String read_function = get_type_read_function_name(member.type.name);
      b32 has_disciminator = member.discriminator.len != 0;
      if(has_disciminator){
       p<read_function<"(r, &"<varname<", dst->"<member.discriminator<");";
      }else{
       if(member.type.kind == Parsed_Type_Array){
        //-Read array
        printf(p, "for_i32(i,0,%S)", member.type.array_count);
        {
         PrintBraces(p);
         print(p, "\n");
         p < read_function < "(r, &" < varname < "[i]);\n";
        }
       }else{
        //-Read normal type
        p<read_function<"(r, &"<varname<");";
       }
      }
     }
     if(member_currently_exists){
      //NOTE(kv) Assign the local var to the dest struct member.
      if(member.type.kind == Parsed_Type_Array){
       p<"copy_array_dst(dst->"<member.name<", "<varname<");\n\n";
      }else{
       p<"dst->"<member.name<" = "<varname<";\n\n";
      }
     }
    }
   }
  }
 }
}
function void
print_union_meta(Printer &p, String type_name,
                 darray(Union_Variant) *variants,
                 String discriminator_type)
{
 m_meta_only(p);
#define brace_block  p < "\n{\n"; defer( p < "\n}\n"; );
 {//-Function to generate the type info
  {
   m_location;
   p<"union "<type_name<";\n";
   print_type_info_function_prototype(p,type_name);
   p<";\n";
  }
  {
   m_location;
   print_type_info_function_prototype(p,type_name);
   {brace_block;
    p < "Type_Info result = {};\n" <
     "result.name = "<enclosed_in_strlit(type_name)<";\n" <
     "result.size = sizeof("<type_name<");\n"<
     "result.kind = I_Type_Kind_Union;\n"<
     "result.discriminator_type = &"<get_type_global_info_name(discriminator_type)<";\n";
    {
     p<"result.union_members.set_count("<variants->count<");\n";
     for_i32(index,0,variants->count){
      auto &variant = variants->get(index);
      String variant_type = get_type_global_info_name(variant.struct_name);
      p<"result.union_members["<index<"] = {"<
       ".type=&"<variant_type<", "<
       ".name="<enclosed_in_strlit(variant.name)<", "<
       ".variant="<variant.enum_name<
       "};\n";
     }
    }
    p<"return result;";
   }
  }
 }
 
 print_type_meta_shared(p, type_name);
 
 {// NOTE: ;read union
  {
   m_location;
   print_union_read_function_prototype(p,type_name,discriminator_type);
   
   {
    brace_block;
    //NOTE(kv) When we add/remove union members, this is gonna get complicated,
    //  but right now I don't care.
    p<"switch(variant)";
    {brace_block;
     for_i32(vi,0,variants->count){
      auto &variant = variants->get(vi);
      p<"case "<variant.enum_name<":";
      {brace_block;
       p<get_type_read_function_name(variant.struct_name)<
        "(r, "<"&dst->"<variant.name_lower<");\n"<
        "break;";
      }
     }
    }
   }
  }
 }
#undef brace_block
}
function void
print_enum(Printer &p, String type_name,
           darray(String) &enum_names,
           darray(i32)    &enum_vals){
 m_location;
 p <"enum " <type_name;
 m_braces_sm{
  for_i32(ei,0,enum_names.count){
   if(ei!=0){ p <"\n"; }
   p <enum_names[ei] <" = " <enum_vals[ei] <",";
  }
 }
 print(p, "\n");
}
function void
print_enum_meta(Printer &p, String type_name,
                darray(String) &enum_names)
{
 m_meta_only(p);
 {//-NOTE: ("Function to generate the type info")
  String function_name = get_type_info_function_name(type_name);
  {//NOTE .h
   m_location;
   p <"function Type_Info\n" <function_name <"();";
  }
  {//NOTE .cpp
   m_location;
   p <"function Type_Info\n" <function_name <"()";
   m_braces_newline{
    p <"Type_Info result = {};\n";
    p <"result.name = " <enclosed_in_strlit(type_name) <";\n";
    p <"result.size = sizeof(" <type_name <");\n";
    p <"result.kind = I_Type_Kind_Enum;\n";
    p <"result.enum_members.set_count(" <enum_names.count <");\n";
    for_i32(enum_index,0,enum_names.count){
     String name = enum_names.get(enum_index);
     p <"result.enum_members[" <enum_index <"] = " <
      "{.name=" <enclosed_in_strlit(name) <", " <
      ".value=" <name <  //NOTE(kv) Let the compiler fill out the value.
      "};\n";
    }
    p <"return result;";
   }
  }
 }
 
 print_type_meta_shared(p, type_name);
 
 {// NOTE: meta_read
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   p <";\n";
  }
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   m_braces_newline{
    // NOTE(kv): @meta_introspect_enum_size
    //   If the type size is too BIG, we'll read past from wrong address.
    p < "i32 integer;" < "\n" <
     "read_binary_i1(r, &integer);" < "\n" <
     "*dst = *("  < type_name  < "*)(&integer);";
   }
  }
 }
 
 {// NOTE ;meta_introspect_enum_size
  p  < "static_assert( sizeof("  < type_name  < ") <= sizeof(i32) );\n\n";
 }
}
function void
print_typedef_meta(Printer &p, String type_name, String typedef_to)
{
 m_meta_only(p);
 {//-Function to generate type info
  String function_name = get_type_info_function_name(type_name);
#define PROTOTYPE  p < "function Type_Info\n" < function_name < "()"
  {
   m_location;
   PROTOTYPE<";";
  }
  {
   m_location;
   PROTOTYPE;
   m_braces_newline{
    p<"Type_Info result = "<get_type_global_info_name(typedef_to)<";\n";
    p<"result.name = "<enclosed_in_strlit(type_name)<";\n";
    p < "return result;\n";
   }
  }
#undef PROTOTYPE
 }
 print_type_meta_shared(p, type_name, true);
 {//-meta read
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   p<";\n";
  }
  {
   m_location;
   print_type_read_function_prototype(p,type_name);
   m_braces_newline{
    p < get_type_read_function_name(typedef_to) < "(r, dst);";
   }
  }
 }
}
function void
print_struct_embed(Printer &p, String type_name,
                   darray(M_Struct_Member) &members)
{
 m_location;
 p <"#define " <type_name <"_Embed \\\n struct";
 m_macro_braces_sm
 {
  for_i32(imem, 0, members.count)
  {
   auto &member = members[imem];
   if(member.version_removed.count == 0)
   {
    print_struct_member(p, member);
    p<";\\\n";
   }
  }
 }
}
function void
print_wrapper_type(Printer &p, String wrapper, String wrapped,
                   String constructor, b32 do_info)
{//@the_type_wrapper_debacle
 Scratch_Block tmp;
 Stringz struct_body = push_stringf(tmp, strcode({ %S v; }), wrapped);
 M_Struct_Members members = parse_struct_body(tmp, struct_body);
 
 // NOTE(kv) What we print to C++ is more involved...
 m_location; 
 b32 is_v3 = (wrapped == strcode(v3));
 {//-The struct
  printf(p, strcode(struct %S\n), wrapper);
  {
   PrintBraces(p);
   print(p,"\n");
   
   if(is_v3){ print(p, strlit("union{\n")); }
   printf(p, strcode(%S v;\n), wrapped);
   if(is_v3)
   {// NOTE(kv) We must go above and beyond to refer to members by name
    print(p, strcode(struct{v1 x,y,z;};\n));
    print(p, strlit("};\n"));
   }
   
   printf(p, strcode(myinline operator %S(){ return v; }\n), wrapped);
  }
  print(p, ";\n");
 }
 
 if(do_info)
 {
  m_meta_only(p);
  m_location;
  String type_name = wrapper;
  String function_name = get_type_info_function_name(type_name);
  p<"function Type_Info\n"<function_name<"()";
  m_braces_newline
  {
   p<"Type_Info result = {};\n";
   p<"result.name = "<enclosed_in_strlit(type_name) < ";\n";
   p<"result.size = sizeof("<type_name<");\n";
   printf(p, strcode(result.kind = I_Type_Kind_Wrapper;\n));
   printf(p, strcode(result.constructor = strcode(%S);\n), constructor);
   printf(p, strcode(result.wrapped_type = type_info_of(%S);\n), wrapped);
   p < "return result;";
  }
  
  print_type_meta_shared(p, type_name);
 }
}
//-
function b32
op_needs_space(Unary_Operator op)
{
 u32 op_u32 = op_to_u32_little_endian(op);
 switch(op_u32){
  case 'not':
  return true;
 } 
 return false;
}
function b32
op_needs_space(Binary_Operator op)
{
 u32 op_u32 = op_to_u32_little_endian(op);
 switch(op_u32){
  case '.':
  case '->':
  return false;
 }
 return true;
}
function void
print_expression2(Printer &p, Precedence max_precedence, Meta_Expression &e)
{
 switch(e.kind)
 {
  case Expression_Kind_None:
  break;
  
  default:
  {
   print(p, e.as_string);
  }break;
  
  case Expression_Kind_Unary:{
   Expression_Unary *unary = &e.unary;
   String op_str = to_string(&unary->op);
   Precedence precedence = precedence_of(unary->op);
   b32 needs_space = op_needs_space(unary->op);
   
   if(is_prefix(unary->op)){
    print(p, op_str);
    if(needs_space) print(p, ' ');
    print_expression2(p, precedence, *unary->argument);
   }else{
    //NOTE postfix
    print_expression2(p, precedence, *unary->argument);
    if(needs_space) print(p, ' ');
    print(p, op_str);
   }
  }break;
  
  case Expression_Kind_Binary:
  {
   Expression_Binary *binary = &e.binary;
   Precedence precedence = precedence_of(binary->op);
   b32 has_parens = precedence >= max_precedence;
   b32 has_space = op_needs_space(binary->op);
   String op_str = to_string(&binary->op);
   
   Precedence left_max_precedence  = Precedence(precedence+1);
   Precedence right_max_precedence = precedence;
   if(is_right_associative(binary->op)){
    macro_swap(left_max_precedence, right_max_precedence);
   }
   if(has_parens){ print(p, '('); }
   print_expression2(p, left_max_precedence, *binary->lhs);
   if(has_space){ print(p, ' '); }
   print(p, op_str);
   if(has_space){ print(p, ' '); }
   print_expression2(p, right_max_precedence, *binary->rhs);
   if(binary->ternary){
    print(p, " : "); 
    print_expression2(p, right_max_precedence, *binary->ternary);
   }
   if(has_parens){ print(p, ')'); }
  }break;
  
  case Expression_Kind_Call:{
   Expression_Call *call = &e.call;
   print_expression2(p, Precedence_Dot_Arrow, *call->func);
   m_parens2(p){
    for_i32(arg_index, 0, call->args.count){
     if(arg_index){ p<", "; }
     print_expression2(p, Precedence_Max, call->args[arg_index]);
    }
   }
  }break;
  
  case Expression_Kind_Array_Subscript:{
   Expression_Array_Subscript *subscript = &e.array_subscript;
   print_expression2(p, Precedence_Dot_Arrow, *subscript->array);
   print(p, '[');
   print_expression2(p, Precedence_Max, *subscript->index);
   print(p, ']');
  }break;
  
  case Expression_Kind_Compound:
  {
   print(p, e.compound_type_name);
   {
    PrintBraces(p);
    for_i32(i, 0, e.compound_items.count)
    {
     if(i != 0){ print(p, strlit(", ")); }
     Compound_Item *item = e.compound_items.items + i;
     if(item->key.count != 0)
     {
      printf(p, ".%S = ", item->key);
     }
     print_expression2(p, Precedence_Max, item->value);
    }
   }
  }break;
 }
}
function void
print_expression(Printer &p, Meta_Expression &e)
{
 print_expression2(p, Precedence_Max, e);
}
function void
print_statement_2(Printer &p, Source_Map *source_map, Meta_Statement &statement)
{
 if(source_map)
 {
  add_to_source_map(source_map, p, statement.pos);
 }
 
 switch(statement.kind)
 {
  case Statement_Kind_None: break;
  
  case Statement_Kind_Misc:
  {
   print(p, statement.misc.as_string);
  }break;
  
  case Statement_Kind_Return:
  {
   print(p, "return ");
   print_expression(p, statement.return0);
   print(p, ";");
  }break;
  
  case Statement_Kind_Expression:
  {
   print_expression(p, statement.expression);
   p < ";";
  }break;
  
  case Statement_Kind_Block:{
   p < "{";
   for_i32(statement_index,0,statement.block.count)
   {
    p < "\n"; 
    print_statement_2(p, source_map, statement.block[statement_index]);
   }
   p<"\n}";
  }break;
  
  case Statement_Kind_Header_And_Body:
  {
   p < statement.header_and_body.header;
   print_statement_2(p, source_map, *statement.header_and_body.body);
  }break;
  
  case Statement_Kind_If:
  {
   p < "if(";
   print_expression(p, statement.if0.condition);
   p < ")";
   print_statement_2(p, source_map, *statement.if0.body);
   if(statement.if0.else0)
   {
    p < "else ";
    print_statement_2(p, source_map, *statement.if0.else0);
   }
  }break;
  
  case Statement_Kind_Switch:{
   p < "switch(";
   print_expression(p, statement.switch0.expression);
   p < ")";
   {
    p < "{";
    for_i32(case_index,0,statement.switch0.cases.count)
    {
     Switch_Case &case0 = statement.switch0.cases[case_index];
     p < "\ncase ";
     print_expression(p, case0.expression);
     p < ": ";
     print_statement_2(p, source_map, case0.body);
     p < (case0.break_after ? " break;" : "");
    }
    p < "\n}";
   }
  }break;
  
  case Statement_Kind_Declaration:
  {
   Statement_Declaration &decl = statement.declaration;
   print_type_and_name(p, decl.type_and_name);
   if(decl.rhs.kind)
   {
    //-Assignment included
    p < " = ";
    print_expression(p, decl.rhs);
   }
   p<";";
  }break;
  
  case Statement_Kind_Empty: { p<";\n"; } break;
  
  case Statement_Kind_Function:
  {
   // NOTE(kv) Assume that we're in the body of a function.
   // We print inner functions as lambdas, which is different from top-level functions.
   Statement_Function &fun = statement.function0;
   printf(p, strcode(auto %S = [&](%S) ->),
          fun.name, fun.type.parameters);
   print(p, " ");
   print_type_and_name(p, *fun.type.return_type, empty_string);
   {// NOTE Body
    PrintBracesNewlineSm(p);
    for_i32(i, 0, fun.body.count)
    {
     print_statement_2(p, source_map, fun.body[i]);
     print(p, '\n');
    }
   }
  }break;
  
  InvalidDefaultCase;
 }
}
function void
print_statement(Meta_Printer &p, Meta_Statement &statement)
{
 print_statement_2(p, &p.source_map, statement);
}
function String
print_statement(Arena *arena, Meta_Statement &statement)
{
 usize cap = 256;
 Printer printer = make_printer_buffer(arena, cap);
 // NOTE(kv) Intentionally leave source_map empty
 Source_Map *source_map = 0;
 print_statement_2(printer, source_map, statement);
 String result = printer_get_string(printer);
 arena_pop_size(arena, cap - result.count);
 return result;
}
function String
print_expression(Arena *arena, Meta_Expression &expression)
{
 usize cap = 256;
 Printer printer = make_printer_buffer(arena, cap);
 print_expression(printer, expression);
 String result = printer_get_string(printer);
 arena_pop_size(arena, cap - result.count);
 return result;
}
function void
print_template(Printer &printer, String format, String *args, u32 argc)
{
 u32 current_arg = 0;
 for_u32(i, 0, format.count){
  u8 c = format.str[i];
  b32 is_percent = (c == '%');
  if(is_percent){
   u32 arg_index = current_arg++;
   kv_assert(arg_index < argc);
   String arg = args[arg_index];
   print(printer, arg);
  }else{
   print(printer, c);
  }
 }
 kv_assert(current_arg == argc);
}
#define PrintTemplate(printer, format, array) \
print_template(printer, format, ArrayAndCount(array))

function Range_i32
meta_resolve_location(sarray(i32) positions, M_Text_Range range)
{// NOTE(kv) We kinda know where the index is,
 // but it might have been moved to the right.
 // This function is here to fix that, with little effort, but lots of annoyance.
 i32 begin_index = -1;
 for_i32(test_index, range.guess_begin_index, positions.count)
 {
  if(positions[test_index] == range.range.begin)
  {
   begin_index = test_index;
   break;
  }
 }
 kv_assert(begin_index != -1);
 
 i32 end_index = -1;
 for_i32(test_index, begin_index, positions.count)
 {
  if(positions.items[test_index] == range.range.end)
  {
   end_index = test_index;
   break;
  }
 }
 kv_assert(end_index != -1);
 
 Range_i32 result = {begin_index, end_index};
 return result;
}
function Range_i32
meta_resolve_location(FUI_Collector &driver, i32 file, M_Text_Range range)
{
 kv_assert(file != 0);
 sarray(i32) positions = driver.files[file].positions;
 return meta_resolve_location(positions, range);
}
function void
print_all_sliders_header(Printer &p, FUI_Collector &c)
{
 sarray(Meta_Slider) &sliders = c.sliders;
 Scratch_Scope tmp;
 
 // NOTE(kv) Slider metadata
 m_locationp(p);
 printf(p, strcode(global Slider global_sliders[%d];\n\n),
        c.sliders.count);
 
 {// NOTE Print a struct containing all the slider values
  m_locationp(p);
  print(p, strcode(struct Slider_Values));
  {
   PrintBracesNewlineSm(p);
   for_i32(slider_index, 0, sliders.count)
   {
    Meta_Slider &slider = sliders[slider_index];
    printf(p, strcode(%S v_%d;\n),
           slider.type, slider_index);
   }
  }
  
  m_locationp(p);
  print(p, strcode(global Slider_Values slider_values = ));
  {
   PrintBracesNewlineSm(p);
   for_each(slider, sliders)
   {
    if(slider->is_runtime)
    {
     print(p, strcode({},\n));
    }
    else
    {
     printf(p, strcode(%S,\n), slider->value);
    }
   }
  }
 }
 
 // TODO(kv) Ideally we'd want a global array here.
 // but the type info isn't available in the driver,
 // so we'd need to make another enum to represent dummy types -> too annoying!
 m_locationp(p);
 printf(p, strcode(function void\n
                   init_sliders(Type_Info_Pointers &types)\n));
 {
  PrintBracesNewline(p);
  print(p, strcode(Slider *sliders = global_sliders;\n));
  for_i32(slider_index, 0, sliders.count)
  {
   Meta_Slider &slider = sliders[slider_index];
   
   String options = slider.options;
   if(options.count == 0){ options = strlit("{}"); }
   Range_i32 range = meta_resolve_location(c, slider.file, slider.range);
   String type = push_stringf(tmp, strcode(types.%S), slider.type);
   printf(p, strcode(sliders[%d] = {
                      .type=%S,
                      .location={{%d, %d}, {%d, %d}},
                      .options=%S,
                      .value=&ReadSlider(%d)
                     };\n),
          slider_index,
          type,
          c.is_driver, slider.file, range.min, range.max,
          options, slider_index);
  }
 }
 
 print(p, "//-\n");
}
function void
print_all_marked_positions(Printer &p, FUI_Collector &driver)
{
 m_locationp(p);
 for_i32(file_index, 1, driver.files.count)
 {
  FUI_Collector_File &file = driver.files[file_index];
  sarray(i32) positions = file.positions;
  printf(p, strcode(global i32 marked_positions_file_%d[%d] = ),
         file_index, positions.count);
  {
   PrintBracesNewlineSm(p);
   printf(p, "//-NOTE: %S \n", file.name);
   for_i32(index, 0, positions.count)
   {
    if((index != 0) and (index % 16 == 0)){ print(p, "\n"); }
    printf(p, "%d,", positions[index]);
   }
   print(p, "\n");
  }
 }
}
function void
print_all_vertices(Printer &p, FUI_Collector &c)
{
 sarray(Meta_Vertex) vertices = c.vertices;
 m_locationp(p);
 // @stupid_cpp_zero_array
 printf(p, cstrcode(global Vertex_Info vertices_info_[%d] = ),
        clamp_min(vertices.count, 1));
 {
  PrintBraces(p);
  for_i32(index, 0, vertices.count)
  {
   Meta_Vertex &vertex = vertices.items[index];
   Range_i32 range = meta_resolve_location(c, vertex.file, vertex.range);
   
   print(p, "\n");
   {
    PrintBraces(p);
    printf(p, cstrcode({{%d, %d}, {%d, %d}},
                       %d,),
           c.is_driver, vertex.file,
           RangeExpand(range),
           vertex.indicator_level);
    if(vertex.overlay)
    {
     printf(p, cstrcode(%d, ), vertex.overlay);
    }
   }
   print(p, ",");
  }
 }
 print(p, ";\n"
       "//-\n\n");
}
function void
print_file_text_objects(Printer &p, FUI_Collector &c)
{
 m_locationp(p);
 printf(p, strcode(global Text_Object text_objects_[%d] = ),
        clamp_min(c.text_objects.count, 1));
 {
  PrintBracesNewlineSm(p);
  for_i32(file_index, 1, c.files.count)
  {
   FUI_Collector_File &file = c.files[file_index];
   sarray(M_Text_Object) file_text = make_slice(c.text_objects,
                                                file.text_objects_slice);
   if(file_text.count > 0)
   {
    printf(p, strlit("//-NOTE %S\n"), file.name);
    
    for_i32(index_in_file, 0, file_text.count)
    {
     M_Text_Object &object = file_text[index_in_file];
     Range_i32 range = meta_resolve_location(c, file_index, object.range);
     
     {
      PrintBraces(p);
      printf(p, strcode(.location={%d, %d}), RangeExpand(range));
      
      printf(p, strcode(, .kind=Text_Object_%S),
             text_object_kind_names[object.kind]);
      
      switch(object.kind)
      {
       case Text_Object_Drawn:
       break;
       
       case Text_Object_Image:
       {
        printf(p, strcode(, .image={.filename=%S}), object.image.filename);
       }break;
       
       case Text_Object_Preset:
       {
        printf(p, strcode(, .preset=%S), object.preset);
       }break;
       
       InvalidDefaultCase;
      }
     }
     print(p, ",\n");
    }
   }
  }
 }
}
function void
print_update_text_objects(Printer &p, sarray(M_Text_Object) text_objects)
{//-Update
 m_locationp(p);
 {
  PrintBracesNewline(p);
  for_i32(object_index, 0, text_objects.count)
  {
   M_Text_Object &object = text_objects[object_index];
   switch(object.kind)
   {
    case Text_Object_Image:
    {
     if(not_empty(object.image.marker))
     {
      printf(p, strcode(text_objects_[%d].image.marker = %S;\n),
             object_index, object.image.marker);
     }
    }break;
   }
  }
 }
 print(p, "//-\n");
}
function void
print_all_type_info(sarray(String) type_info_list)
{
 Scratch_Scope tmp;
 
 {//-Creation of the type infos
  Stringz path = pjoin(tmp, meta.dirs.game, strlit("meta_all.gen.cpp"));
  Printer printer = m_open_file_to_write(path);
  
  print(printer, strcode(function void\n
                         make_all_type_info()\n));
  {
   PrintBracesNewline(printer);
   for_i32(i, 0, type_info_list.count)
   {
    String type = type_info_list.items[i];
    printf(printer, strcode(Type_Info_%S = get_type_info_%S();\n),
           type, type);
   }
  }
  
  close(printer);
 }
}
function void
print_all_fui_data(FUI_Collector &c)
{
 Scratch_Scope tmp;
 
 Stringz h_path, cpp_path;
 {
  String tu = c.is_driver ? strlit("driver") : strlit("game");
  String h_filename   = push_stringf(tmp, "%S_fui_data.gen.h", tu);
  String cpp_filename = push_stringf(tmp, "%S_fui_data.gen.cpp", tu);
  
  String dir = c.is_driver ? meta.dirs.driver : meta.dirs.game;
  h_path   = pjoin(tmp, dir, h_filename);
  cpp_path = pjoin(tmp, dir, cpp_filename);
 }
 Meta_Printer printer_h   = m_open_file_to_write(h_path);
 Meta_Printer printer_cpp = m_open_file_to_write(cpp_path);
 
 // TODO(kv) idk about duplicating the loop over files like this.
 {//-NOTE Header
  Printer &p = printer_h;
  print_all_marked_positions(p, c);
  print_all_vertices(p, c);
  print_all_sliders_header(p, c);
  
  m_locationp(p);
  printf(p, strcode(global_decl Text_Object text_objects_[%d];\n\n),
         clamp_min(c.text_objects.count, 1));
  
  {//-NOTE File info
   m_locationp(p);
   printf(p, strcode(global FUI_File_Data fui_files_[%d] = ),
          c.files.count);
   {
    PrintBracesNewlineSm(p);
    
    print(p, strcode({},\n));
    
    for_i32(file_index, 1, c.files.count)
    {
     FUI_Collector_File &file = c.files[file_index];
     printf(p, strcode({\n
                        .index = %d,\n
                        .name  = strlit("%S"),\n
                        .marked_positions = {ArrayAndCount(marked_positions_file_%d)},\n
                        .text_objects     = make_slice(text_objects_, {%d,%d}),\n
                        .sliders          = make_slice(global_sliders, {%d,%d}),\n
                        .vertices_info    = make_slice(vertices_info_, {%d,%d}),\n
                       },\n),
            
            file_index,
            c.files[file_index].name,
            file_index,
            RangeExpand(file.text_objects_slice),
            RangeExpand(file.sliders_slice),
            RangeExpand(file.vertices_slice));
    }
   }
  }
 }
 
 {//-NOTE Cpp
  Printer &p = printer_cpp;
  print_file_text_objects(p, c);
 }
 
 {//-NOTE Update
  Printer &p = printer_cpp;
  m_locationp(p);
  print(p, strcode(function void\n
                   update_driver_data()\n));
  {
   PrintBracesNewline(p);
   {//-NOTE Update one file
    PrintBracesNewline(p);
    print_update_text_objects(p, c.text_objects);
   }
  }
 }
 
 kv_assert(not printer_h.error and
           not printer_cpp.error);
 close(printer_h);
 close(printer_cpp);
}
//-