// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1155:
global i32 marked_positions_file_1[4] ={
//-NOTE: driver_animate.kc 
62,70,1870,1878,
};
global i32 marked_positions_file_2[942] ={
//-NOTE: driver.kc 
102,153,195,241,287,354,401,460,499,550,589,640,687,746,789,844,
895,958,1007,1068,1116,1176,1217,1270,1304,1350,1397,1456,1497,1550,1591,1644,
1688,1744,1782,1832,3450,3463,4332,4340,4427,4435,4483,4491,4532,4540,4578,4586,
4625,4633,4659,4670,4691,4710,4730,4741,4795,4807,4839,4851,5449,5461,5495,5504,
5581,5590,5736,5790,5824,5836,5870,5879,6071,6128,6152,6177,6544,6574,8093,8123,
8238,8265,8337,8363,8397,8409,8443,8452,8486,8495,8531,8540,9224,9236,11075,11101,
11107,11137,11146,11147,11167,11176,11198,11210,11275,11284,11401,11413,11740,11771,12036,12045,
12124,12136,12361,12396,12413,12425,12432,12444,12491,12500,13131,13143,13461,13473,13493,13505,
15515,15527,15530,15545,15704,15741,15784,15980,16007,16019,16022,16077,16229,16241,16245,16315,
16344,16356,16360,16471,16497,16509,16513,16581,16657,16669,16696,16708,16712,16872,16899,16911,
16915,17027,17031,17160,17164,17284,17290,17349,17364,17382,17389,17485,17797,17848,17999,18008,
18013,18072,18077,18206,18523,18546,19033,19165,19171,19309,19384,19504,19571,19699,19971,20049,
20056,20135,20358,20450,20457,20548,21022,21031,21210,21222,21351,21382,21517,21572,21581,21583,
21616,21628,21811,21846,21891,21903,21965,21974,21979,22003,22012,22041,22046,22191,22255,22264,
22297,22306,22321,22333,22338,22449,22454,22454,22475,22475,22586,22612,22644,22653,22659,22682,
22691,22698,22721,22730,22735,22823,22881,22936,22977,23006,23109,23121,23140,23151,23156,23176,
23190,23199,23204,23241,23246,23273,23303,23315,23336,23348,23522,23531,23568,23577,23773,23808,
23812,23832,24029,24046,24460,24501,24579,24594,24689,24740,24745,24765,24874,24912,24940,24977,
24981,25017,25021,25080,25298,25332,25413,25479,25662,25691,25753,25788,25792,25813,25849,25912,
25943,25955,26146,26156,26160,26199,26289,26301,26394,26403,26406,26446,26455,26456,26494,26503,
26508,26543,26546,26574,26583,26584,26606,26618,26623,26651,26660,26661,26693,26702,26736,26745,
26778,26787,26869,26897,26906,26907,26928,26940,27095,27122,27128,27239,27245,27300,27306,27362,
27451,27495,27502,27554,27559,27601,27643,27685,27694,27696,27705,27707,27716,27718,27724,27755,
27761,27796,27825,27834,27841,27860,27866,27901,27910,27930,27939,27977,28306,28348,28566,28628,
28637,28639,28648,28650,28659,28661,28762,28771,28778,28809,28823,28857,29123,29156,29161,29209,
29214,29267,29774,29813,29893,29925,29938,29964,29978,30048,30217,30375,30398,30457,30462,30520,
30523,30558,30567,30568,30595,30607,30702,30764,30854,30866,30897,30906,30937,30946,30948,30957,
30988,30997,31022,31032,31034,31044,31071,31081,31147,31168,31176,31213,31223,31224,31252,31265,
31599,31612,31788,31823,31859,31872,31925,31935,31962,31972,32013,32023,32084,32094,32168,32190,
32200,32211,32237,32250,32272,32282,32343,32353,32358,32378,32388,32431,32623,32654,32664,32673,
32706,32716,32738,32748,32753,32778,32788,32795,32940,33000,33010,33012,33022,33024,33034,33036,
33082,33092,33116,33126,33146,33157,33181,33182,33186,33200,33328,33341,33358,33371,33382,33395,
33489,33516,33520,33582,33631,33658,33663,33677,33752,33779,33954,33964,33980,33993,34043,34136,
34140,34171,34175,34198,34202,34261,34265,34296,34474,34484,34507,34517,34553,34594,34629,34656,
34666,34667,34691,34701,34705,34748,34787,34835,34840,34890,34967,35018,35028,35030,35040,35042,
35052,35054,35058,35109,35119,35121,35131,35164,35168,35219,35229,35231,35241,35243,35253,35255,
35356,35407,35417,35419,35429,35447,35460,35462,35506,35587,35597,35599,35609,35611,35614,35669,
35851,35878,35882,35916,36136,36149,36153,36260,36264,36381,36498,36533,36537,36611,36646,36659,
36678,36691,36694,36828,36961,36971,37020,37064,37067,37097,37100,37128,37682,37712,37722,37723,
37726,37749,37759,37760,37841,37854,37857,37875,38226,38239,38260,38273,38684,38706,38965,38998,
39026,39080,39546,39721,39825,39841,39846,39861,40556,40581,40590,40627,40632,40671,40683,40716,
40726,40727,40730,40766,40776,40777,40798,40811,41090,41100,41106,41250,41414,41581,41588,41630,
41687,41838,41937,42081,42159,42312,42436,42449,42767,42787,42799,42825,42828,42858,42868,42869,
42910,42920,42960,42973,43008,43162,43191,43225,43233,43272,43279,43309,43568,43587,43676,43786,
43887,43916,43921,43950,43955,43990,43995,44021,44114,44271,44276,44390,44395,44537,44542,44542,
44587,44587,44592,44592,44637,44637,44667,44680,44684,44723,45019,45077,45219,45255,45259,45296,
45530,45578,45878,45930,46156,46169,46191,46204,46269,46312,46316,46494,46511,46524,46866,46882,
46929,46985,47396,47409,47412,47442,47473,47486,47508,47518,47522,47626,47630,47735,47892,47905,
48002,48015,48262,48297,48301,48423,48432,48477,48482,48525,48530,48556,50092,50138,50265,50306,
50603,50665,50940,50989,51110,51154,51306,51360,51513,51555,51636,51699,51719,51732,52016,52040,
52147,52179,52261,52288,52681,52691,53097,53107,53606,53616,55379,55392,55424,55437,56414,56427,
56950,56963,57218,57240,57571,57595,57623,57636,57945,57968,58267,58280,58585,58598,59531,59544,
59861,59877,59917,59930,59946,59959,60412,60422,60454,60464,60665,60682,60686,60742,60836,60849,
61044,61056,61066,61067,61337,61361,61371,61373,61615,61634,62114,62125,62204,62215,62425,62435,
62794,62855,62946,62978,63050,63082,63099,63131,63706,63719,63866,63876,64401,64411,65632,65664,
65702,65744,66002,66015,66064,66112,66118,66189,66323,66358,66401,66414,66551,66590,66633,66646,
66754,66804,66847,66860,66969,67021,67064,67077,67185,67226,67268,67281,67643,67696,67835,67848,
67925,68001,68110,68123,68175,68205,68278,68368,69201,69214,69474,69484,69818,69828,70246,70259,
70466,70485,70490,70509,70683,70696,70701,70719,71148,71166,71171,71190,71195,71214,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1178:
global Vertex_Info vertices_info_[9] ={
{{{1, 2}, {108, 109}}, 0,1,},
{{{1, 2}, {114, 115}}, 0,1,},
{{{1, 2}, {118, 119}}, 0,},
{{{1, 2}, {130, 131}}, 0,},
{{{1, 2}, {180, 181}}, 99,},
{{{1, 2}, {202, 203}}, 0,1,},
{{{1, 2}, {630, 631}}, 0,},
{{{1, 2}, {934, 935}}, 0,1,},
{{{1, 2}, {936, 937}}, 0,1,},};
//-

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1091:
global Slider global_sliders[207];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1096:
struct Slider_Values{
i1 v_0;
i1 v_1;
tvert v_2;
i1 v_3;
v1 v_4;
i1 v_5;
i1 v_6;
i1 v_7;
i1 v_8;
i1 v_9;
i1 v_10;
i1 v_11;
tvert v_12;
tvert v_13;
v3 v_14;
v1 v_15;
tvert v_16;
v3 v_17;
Reference_Placement v_18;
Reference_Mesh_Placement v_19;
Reference_Mesh_Placement v_20;
tvert v_21;
v3 v_22;
v1 v_23;
v1 v_24;
tvert v_25;
v2 v_26;
v3 v_27;
tvert v_28;
v3 v_29;
tvert v_30;
v3 v_31;
tvert v_32;
tvert v_33;
v3 v_34;
tvert v_35;
tvert v_36;
tvert v_37;
tvert v_38;
tvert v_39;
tvert v_40;
tvert v_41;
tvert v_42;
tvert v_43;
tvert v_44;
tvert v_45;
v3 v_46;
v1 v_47;
tvert v_48;
v3 v_49;
tvert v_50;
tvert v_51;
v3 v_52;
v3 v_53;
v1 v_54;
v3 v_55;
tvert v_56;
Curve v_57;
v1 v_58;
v3 v_59;
v3 v_60;
tvert v_61;
tdim v_62;
tnormal v_63;
tvert v_64;
tvert v_65;
v3 v_66;
v3 v_67;
tvert v_68;
tvert v_69;
v3 v_70;
v2 v_71;
v3 v_72;
v2 v_73;
tvert v_74;
v2 v_75;
v3 v_76;
v3 v_77;
v3 v_78;
v2 v_79;
tvert v_80;
v2 v_81;
v2 v_82;
v2 v_83;
v1 v_84;
v3 v_85;
v2 v_86;
v2 v_87;
v2 v_88;
v2 v_89;
v1 v_90;
v2 v_91;
tvert v_92;
tvert v_93;
v3 v_94;
v3 v_95;
v2 v_96;
v3 v_97;
v3 v_98;
v2 v_99;
v3 v_100;
v2 v_101;
tvert v_102;
tvert v_103;
tvert v_104;
v3 v_105;
v3 v_106;
v3 v_107;
v3 v_108;
tvert v_109;
v3 v_110;
v1 v_111;
v3 v_112;
v3 v_113;
v3 v_114;
v3 v_115;
v3 v_116;
v2 v_117;
v2 v_118;
v2 v_119;
v3 v_120;
v2 v_121;
FUI_Line_Params v_122;
tvert v_123;
tvert v_124;
tvert v_125;
v3 v_126;
tvert v_127;
v3 v_128;
v3 v_129;
v2 v_130;
v3 v_131;
v2 v_132;
v2 v_133;
v2 v_134;
v3 v_135;
v2 v_136;
v2 v_137;
v2 v_138;
v2 v_139;
v3 v_140;
v2 v_141;
tvert v_142;
v2 v_143;
v2 v_144;
tvert v_145;
tvert v_146;
tvert v_147;
v2 v_148;
v2 v_149;
tvert v_150;
tvert v_151;
tvert v_152;
v2 v_153;
v2 v_154;
tvert v_155;
v1 v_156;
tvert v_157;
v2 v_158;
v3 v_159;
tvert v_160;
Curve v_161;
Curve v_162;
tvert v_163;
tvert v_164;
tvert v_165;
tvert v_166;
tvert v_167;
tvert v_168;
v3 v_169;
tvert v_170;
tvert v_171;
i1 v_172;
v3 v_173;
v3 v_174;
v1 v_175;
tvert v_176;
tvert v_177;
tvert v_178;
tvert v_179;
tvert v_180;
tvert v_181;
tvert v_182;
tvert v_183;
tvert v_184;
tvert v_185;
v3 v_186;
v3 v_187;
tvert v_188;
v4 v_189;
i2 v_190;
i1 v_191;
i1 v_192;
v3 v_193;
tvert v_194;
tvert v_195;
tvert v_196;
tvert v_197;
tvert v_198;
tvert v_199;
tvert v_200;
tvert v_201;
i1 v_202;
v1 v_203;
v1 v_204;
i1 v_205;
tvert v_206;
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1108:
global Slider_Values slider_values ={
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1122:
function void
 init_sliders(Type_Info_Pointers &types)
{
Slider *sliders = global_sliders;
sliders[0] = { .type=types.i1, .location={{1, 1}, {0, 1}}, .options={}, .id=strlit("i1_0"), .value=&ReadSlider(0) };
sliders[1] = { .type=types.i1, .location={{1, 1}, {2, 3}}, .options={}, .id=strlit("i1_1"), .value=&ReadSlider(1) };
sliders[2] = { .type=types.tvert, .location={{1, 2}, {36, 37}}, .options={}, .id=strlit("tvert_177"), .value=&ReadSlider(2) };
sliders[3] = { .type=types.i1, .location={{1, 2}, {38, 39}}, .options={}, .id=strlit("i1_2"), .value=&ReadSlider(3) };
sliders[4] = { .type=types.v1, .location={{1, 2}, {40, 41}}, .options={}, .id=strlit("v1_3"), .value=&ReadSlider(4) };
sliders[5] = { .type=types.i1, .location={{1, 2}, {42, 43}}, .options={}, .id=strlit("i1_4"), .value=&ReadSlider(5) };
sliders[6] = { .type=types.i1, .location={{1, 2}, {44, 45}}, .options={}, .id=strlit("i1_5"), .value=&ReadSlider(6) };
sliders[7] = { .type=types.i1, .location={{1, 2}, {46, 47}}, .options={}, .id=strlit("i1_6"), .value=&ReadSlider(7) };
sliders[8] = { .type=types.i1, .location={{1, 2}, {48, 49}}, .options={}, .id=strlit("i1_7"), .value=&ReadSlider(8) };
sliders[9] = { .type=types.i1, .location={{1, 2}, {50, 51}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_8"), .value=&ReadSlider(9) };
sliders[10] = { .type=types.i1, .location={{1, 2}, {54, 55}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_9"), .value=&ReadSlider(10) };
sliders[11] = { .type=types.i1, .location={{1, 2}, {56, 57}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_10"), .value=&ReadSlider(11) };
sliders[12] = { .type=types.tvert, .location={{1, 2}, {58, 59}}, .options={}, .id=strlit("tvert_11"), .value=&ReadSlider(12) };
sliders[13] = { .type=types.tvert, .location={{1, 2}, {60, 61}}, .options={}, .id=strlit("tvert_13"), .value=&ReadSlider(13) };
sliders[14] = { .type=types.v3, .location={{1, 2}, {62, 63}}, .options={}, .id=strlit("v3_14"), .value=&ReadSlider(14) };
sliders[15] = { .type=types.v1, .location={{1, 2}, {64, 65}}, .options={}, .id=strlit("v1_15"), .value=&ReadSlider(15) };
sliders[16] = { .type=types.tvert, .location={{1, 2}, {68, 69}}, .options={}, .id=strlit("tvert_16"), .value=&ReadSlider(16) };
sliders[17] = { .type=types.v3, .location={{1, 2}, {70, 71}}, .options={}, .id=strlit("v3_17"), .value=&ReadSlider(17) };
sliders[18] = { .type=types.Reference_Placement, .location={{1, 2}, {74, 75}}, .options={}, .id=strlit("Reference_Placement_0"), .value=&ReadSlider(18) };
sliders[19] = { .type=types.Reference_Mesh_Placement, .location={{1, 2}, {76, 77}}, .options={}, .id=strlit("Reference_Mesh_Placement_0"), .value=&ReadSlider(19) };
sliders[20] = { .type=types.Reference_Mesh_Placement, .location={{1, 2}, {78, 79}}, .options={}, .id=strlit("Reference_Mesh_Placement_1"), .value=&ReadSlider(20) };
sliders[21] = { .type=types.tvert, .location={{1, 2}, {84, 85}}, .options={}, .id=strlit("tvert_18"), .value=&ReadSlider(21) };
sliders[22] = { .type=types.v3, .location={{1, 2}, {86, 87}}, .options={}, .id=strlit("v3_19"), .value=&ReadSlider(22) };
sliders[23] = { .type=types.v1, .location={{1, 2}, {88, 89}}, .options={}, .id=strlit("v1_20"), .value=&ReadSlider(23) };
sliders[24] = { .type=types.v1, .location={{1, 2}, {90, 91}}, .options={}, .id=strlit("v1_21"), .value=&ReadSlider(24) };
sliders[25] = { .type=types.tvert, .location={{1, 2}, {92, 93}}, .options={}, .id=strlit("tvert_22"), .value=&ReadSlider(25) };
sliders[26] = { .type=types.v2, .location={{1, 2}, {97, 98}}, .options={}, .id=strlit("v2_26"), .value=&ReadSlider(26) };
sliders[27] = { .type=types.v3, .location={{1, 2}, {100, 101}}, .options={}, .id=strlit("v3_27"), .value=&ReadSlider(27) };
sliders[28] = { .type=types.tvert, .location={{1, 2}, {102, 103}}, .options={}, .id=strlit("tvert_28"), .value=&ReadSlider(28) };
sliders[29] = { .type=types.v3, .location={{1, 2}, {104, 105}}, .options={}, .id=strlit("v3_29"), .value=&ReadSlider(29) };
sliders[30] = { .type=types.tvert, .location={{1, 2}, {106, 107}}, .options={}, .id=strlit("tvert_30"), .value=&ReadSlider(30) };
sliders[31] = { .type=types.v3, .location={{1, 2}, {110, 111}}, .options={}, .id=strlit("v3_31"), .value=&ReadSlider(31) };
sliders[32] = { .type=types.tvert, .location={{1, 2}, {112, 113}}, .options={}, .id=strlit("tvert_32"), .value=&ReadSlider(32) };
sliders[33] = { .type=types.tvert, .location={{1, 2}, {116, 117}}, .options={}, .id=strlit("tvert_33"), .value=&ReadSlider(33) };
sliders[34] = { .type=types.v3, .location={{1, 2}, {120, 121}}, .options={}, .id=strlit("v3_34"), .value=&ReadSlider(34) };
sliders[35] = { .type=types.tvert, .location={{1, 2}, {122, 123}}, .options={}, .id=strlit("tvert_35"), .value=&ReadSlider(35) };
sliders[36] = { .type=types.tvert, .location={{1, 2}, {124, 125}}, .options={}, .id=strlit("tvert_36"), .value=&ReadSlider(36) };
sliders[37] = { .type=types.tvert, .location={{1, 2}, {126, 127}}, .options={}, .id=strlit("tvert_37"), .value=&ReadSlider(37) };
sliders[38] = { .type=types.tvert, .location={{1, 2}, {128, 129}}, .options={}, .id=strlit("tvert_38"), .value=&ReadSlider(38) };
sliders[39] = { .type=types.tvert, .location={{1, 2}, {136, 137}}, .options={}, .id=strlit("tvert_39"), .value=&ReadSlider(39) };
sliders[40] = { .type=types.tvert, .location={{1, 2}, {140, 141}}, .options={}, .id=strlit("tvert_40"), .value=&ReadSlider(40) };
sliders[41] = { .type=types.tvert, .location={{1, 2}, {144, 145}}, .options={}, .id=strlit("tvert_41"), .value=&ReadSlider(41) };
sliders[42] = { .type=types.tvert, .location={{1, 2}, {148, 149}}, .options={}, .id=strlit("tvert_42"), .value=&ReadSlider(42) };
sliders[43] = { .type=types.tvert, .location={{1, 2}, {152, 153}}, .options={}, .id=strlit("tvert_43"), .value=&ReadSlider(43) };
sliders[44] = { .type=types.tvert, .location={{1, 2}, {154, 155}}, .options={}, .id=strlit("tvert_44"), .value=&ReadSlider(44) };
sliders[45] = { .type=types.tvert, .location={{1, 2}, {158, 159}}, .options={}, .id=strlit("tvert_45"), .value=&ReadSlider(45) };
sliders[46] = { .type=types.v3, .location={{1, 2}, {174, 175}}, .options={}, .id=strlit("v3_46"), .value=&ReadSlider(46) };
sliders[47] = { .type=types.v1, .location={{1, 2}, {198, 199}}, .options={}, .id=strlit("v1_47"), .value=&ReadSlider(47) };
sliders[48] = { .type=types.tvert, .location={{1, 2}, {200, 201}}, .options={}, .id=strlit("tvert_48"), .value=&ReadSlider(48) };
sliders[49] = { .type=types.v3, .location={{1, 2}, {205, 206}}, .options={}, .id=strlit("v3_49"), .value=&ReadSlider(49) };
sliders[50] = { .type=types.tvert, .location={{1, 2}, {208, 209}}, .options={}, .id=strlit("tvert_50"), .value=&ReadSlider(50) };
sliders[51] = { .type=types.tvert, .location={{1, 2}, {212, 213}}, .options={}, .id=strlit("tvert_51"), .value=&ReadSlider(51) };
sliders[52] = { .type=types.v3, .location={{1, 2}, {214, 215}}, .options={}, .id=strlit("v3_52"), .value=&ReadSlider(52) };
sliders[53] = { .type=types.v3, .location={{1, 2}, {217, 218}}, .options={}, .id=strlit("v3_53"), .value=&ReadSlider(53) };
sliders[54] = { .type=types.v1, .location={{1, 2}, {222, 223}}, .options={}, .id=strlit("v1_54"), .value=&ReadSlider(54) };
sliders[55] = { .type=types.v3, .location={{1, 2}, {224, 225}}, .options={}, .id=strlit("v3_55"), .value=&ReadSlider(55) };
sliders[56] = { .type=types.tvert, .location={{1, 2}, {226, 227}}, .options={}, .id=strlit("tvert_56"), .value=&ReadSlider(56) };
sliders[57] = { .type=types.Curve, .location={{1, 2}, {230, 232}}, .options={}, .id=strlit("Curve_0"), .value=&ReadSlider(57) };
sliders[58] = { .type=types.v1, .location={{1, 2}, {236, 237}}, .options={}, .id=strlit("v1_60"), .value=&ReadSlider(58) };
sliders[59] = { .type=types.v3, .location={{1, 2}, {239, 240}}, .options={}, .id=strlit("v3_61"), .value=&ReadSlider(59) };
sliders[60] = { .type=types.v3, .location={{1, 2}, {242, 243}}, .options={}, .id=strlit("v3_62"), .value=&ReadSlider(60) };
sliders[61] = { .type=types.tvert, .location={{1, 2}, {250, 251}}, .options={}, .id=strlit("tvert_63"), .value=&ReadSlider(61) };
sliders[62] = { .type=types.tdim, .location={{1, 2}, {252, 253}}, .options={}, .id=strlit("tdim_64"), .value=&ReadSlider(62) };
sliders[63] = { .type=types.tnormal, .location={{1, 2}, {255, 256}}, .options={}, .id=strlit("tnormal_65"), .value=&ReadSlider(63) };
sliders[64] = { .type=types.tvert, .location={{1, 2}, {262, 263}}, .options={}, .id=strlit("tvert_66"), .value=&ReadSlider(64) };
sliders[65] = { .type=types.tvert, .location={{1, 2}, {264, 265}}, .options={}, .id=strlit("tvert_67"), .value=&ReadSlider(65) };
sliders[66] = { .type=types.v3, .location={{1, 2}, {266, 267}}, .options={}, .id=strlit("v3_68"), .value=&ReadSlider(66) };
sliders[67] = { .type=types.v3, .location={{1, 2}, {268, 269}}, .options={}, .id=strlit("v3_69"), .value=&ReadSlider(67) };
sliders[68] = { .type=types.tvert, .location={{1, 2}, {304, 305}}, .options={}, .id=strlit("tvert_70"), .value=&ReadSlider(68) };
sliders[69] = { .type=types.tvert, .location={{1, 2}, {310, 311}}, .options={}, .id=strlit("tvert_71"), .value=&ReadSlider(69) };
sliders[70] = { .type=types.v3, .location={{1, 2}, {312, 313}}, .options={}, .id=strlit("v3_72"), .value=&ReadSlider(70) };
sliders[71] = { .type=types.v2, .location={{1, 2}, {315, 316}}, .options={}, .id=strlit("v2_73"), .value=&ReadSlider(71) };
sliders[72] = { .type=types.v3, .location={{1, 2}, {318, 319}}, .options={}, .id=strlit("v3_74"), .value=&ReadSlider(72) };
sliders[73] = { .type=types.v2, .location={{1, 2}, {323, 324}}, .options={}, .id=strlit("v2_75"), .value=&ReadSlider(73) };
sliders[74] = { .type=types.tvert, .location={{1, 2}, {326, 327}}, .options={}, .id=strlit("tvert_76"), .value=&ReadSlider(74) };
sliders[75] = { .type=types.v2, .location={{1, 2}, {329, 330}}, .options={}, .id=strlit("v2_77"), .value=&ReadSlider(75) };
sliders[76] = { .type=types.v3, .location={{1, 2}, {332, 333}}, .options={}, .id=strlit("v3_78"), .value=&ReadSlider(76) };
sliders[77] = { .type=types.v3, .location={{1, 2}, {334, 335}}, .options={}, .id=strlit("v3_79"), .value=&ReadSlider(77) };
sliders[78] = { .type=types.v3, .location={{1, 2}, {336, 337}}, .options={}, .id=strlit("v3_80"), .value=&ReadSlider(78) };
sliders[79] = { .type=types.v2, .location={{1, 2}, {339, 340}}, .options={}, .id=strlit("v2_81"), .value=&ReadSlider(79) };
sliders[80] = { .type=types.tvert, .location={{1, 2}, {342, 343}}, .options={}, .id=strlit("tvert_82"), .value=&ReadSlider(80) };
sliders[81] = { .type=types.v2, .location={{1, 2}, {359, 360}}, .options={}, .id=strlit("v2_83"), .value=&ReadSlider(81) };
sliders[82] = { .type=types.v2, .location={{1, 2}, {361, 362}}, .options={}, .id=strlit("v2_84"), .value=&ReadSlider(82) };
sliders[83] = { .type=types.v2, .location={{1, 2}, {363, 364}}, .options={}, .id=strlit("v2_85"), .value=&ReadSlider(83) };
sliders[84] = { .type=types.v1, .location={{1, 2}, {370, 371}}, .options={}, .id=strlit("v1_86"), .value=&ReadSlider(84) };
sliders[85] = { .type=types.v3, .location={{1, 2}, {375, 376}}, .options={}, .id=strlit("v3_87"), .value=&ReadSlider(85) };
sliders[86] = { .type=types.v2, .location={{1, 2}, {377, 378}}, .options={}, .id=strlit("v2_88"), .value=&ReadSlider(86) };
sliders[87] = { .type=types.v2, .location={{1, 2}, {383, 384}}, .options={}, .id=strlit("v2_89"), .value=&ReadSlider(87) };
sliders[88] = { .type=types.v2, .location={{1, 2}, {385, 386}}, .options={}, .id=strlit("v2_90"), .value=&ReadSlider(88) };
sliders[89] = { .type=types.v2, .location={{1, 2}, {387, 388}}, .options={}, .id=strlit("v2_91"), .value=&ReadSlider(89) };
sliders[90] = { .type=types.v1, .location={{1, 2}, {390, 391}}, .options={}, .id=strlit("v1_92"), .value=&ReadSlider(90) };
sliders[91] = { .type=types.v2, .location={{1, 2}, {417, 418}}, .options={}, .id=strlit("v2_93"), .value=&ReadSlider(91) };
sliders[92] = { .type=types.tvert, .location={{1, 2}, {420, 421}}, .options={}, .id=strlit("tvert_94"), .value=&ReadSlider(92) };
sliders[93] = { .type=types.tvert, .location={{1, 2}, {424, 425}}, .options={}, .id=strlit("tvert_95"), .value=&ReadSlider(93) };
sliders[94] = { .type=types.v3, .location={{1, 2}, {426, 427}}, .options={}, .id=strlit("v3_96"), .value=&ReadSlider(94) };
sliders[95] = { .type=types.v3, .location={{1, 2}, {428, 429}}, .options={}, .id=strlit("v3_97"), .value=&ReadSlider(95) };
sliders[96] = { .type=types.v2, .location={{1, 2}, {430, 431}}, .options={}, .id=strlit("v2_98"), .value=&ReadSlider(96) };
sliders[97] = { .type=types.v3, .location={{1, 2}, {432, 433}}, .options={}, .id=strlit("v3_99"), .value=&ReadSlider(97) };
sliders[98] = { .type=types.v3, .location={{1, 2}, {434, 435}}, .options={}, .id=strlit("v3_100"), .value=&ReadSlider(98) };
sliders[99] = { .type=types.v2, .location={{1, 2}, {436, 437}}, .options={}, .id=strlit("v2_101"), .value=&ReadSlider(99) };
sliders[100] = { .type=types.v3, .location={{1, 2}, {438, 439}}, .options={}, .id=strlit("v3_102"), .value=&ReadSlider(100) };
sliders[101] = { .type=types.v2, .location={{1, 2}, {443, 444}}, .options={}, .id=strlit("v2_103"), .value=&ReadSlider(101) };
sliders[102] = { .type=types.tvert, .location={{1, 2}, {446, 447}}, .options={}, .id=strlit("tvert_104"), .value=&ReadSlider(102) };
sliders[103] = { .type=types.tvert, .location={{1, 2}, {448, 449}}, .options={}, .id=strlit("tvert_105"), .value=&ReadSlider(103) };
sliders[104] = { .type=types.tvert, .location={{1, 2}, {452, 453}}, .options={}, .id=strlit("tvert_106"), .value=&ReadSlider(104) };
sliders[105] = { .type=types.v3, .location={{1, 2}, {454, 455}}, .options={}, .id=strlit("v3_107"), .value=&ReadSlider(105) };
sliders[106] = { .type=types.v3, .location={{1, 2}, {456, 457}}, .options={}, .id=strlit("v3_108"), .value=&ReadSlider(106) };
sliders[107] = { .type=types.v3, .location={{1, 2}, {458, 459}}, .options={}, .id=strlit("v3_109"), .value=&ReadSlider(107) };
sliders[108] = { .type=types.v3, .location={{1, 2}, {463, 464}}, .options={}, .id=strlit("v3_110"), .value=&ReadSlider(108) };
sliders[109] = { .type=types.tvert, .location={{1, 2}, {466, 467}}, .options={}, .id=strlit("tvert_111"), .value=&ReadSlider(109) };
sliders[110] = { .type=types.v3, .location={{1, 2}, {468, 469}}, .options={}, .id=strlit("v3_112"), .value=&ReadSlider(110) };
sliders[111] = { .type=types.v1, .location={{1, 2}, {470, 471}}, .options={}, .id=strlit("v1_113"), .value=&ReadSlider(111) };
sliders[112] = { .type=types.v3, .location={{1, 2}, {473, 474}}, .options={}, .id=strlit("v3_114"), .value=&ReadSlider(112) };
sliders[113] = { .type=types.v3, .location={{1, 2}, {477, 478}}, .options={}, .id=strlit("v3_115"), .value=&ReadSlider(113) };
sliders[114] = { .type=types.v3, .location={{1, 2}, {480, 481}}, .options={}, .id=strlit("v3_116"), .value=&ReadSlider(114) };
sliders[115] = { .type=types.v3, .location={{1, 2}, {482, 483}}, .options={}, .id=strlit("v3_117"), .value=&ReadSlider(115) };
sliders[116] = { .type=types.v3, .location={{1, 2}, {485, 486}}, .options={}, .id=strlit("v3_118"), .value=&ReadSlider(116) };
sliders[117] = { .type=types.v2, .location={{1, 2}, {489, 490}}, .options={}, .id=strlit("v2_119"), .value=&ReadSlider(117) };
sliders[118] = { .type=types.v2, .location={{1, 2}, {491, 492}}, .options={}, .id=strlit("v2_120"), .value=&ReadSlider(118) };
sliders[119] = { .type=types.v2, .location={{1, 2}, {493, 494}}, .options={}, .id=strlit("v2_121"), .value=&ReadSlider(119) };
sliders[120] = { .type=types.v3, .location={{1, 2}, {496, 497}}, .options={}, .id=strlit("v3_122"), .value=&ReadSlider(120) };
sliders[121] = { .type=types.v2, .location={{1, 2}, {498, 499}}, .options={}, .id=strlit("v2_123"), .value=&ReadSlider(121) };
sliders[122] = { .type=types.FUI_Line_Params, .location={{1, 2}, {501, 502}}, .options={}, .id=strlit("FUI_Line_Params_124"), .value=&ReadSlider(122) };
sliders[123] = { .type=types.tvert, .location={{1, 2}, {506, 507}}, .options={}, .id=strlit("tvert_125"), .value=&ReadSlider(123) };
sliders[124] = { .type=types.tvert, .location={{1, 2}, {508, 509}}, .options={}, .id=strlit("tvert_126"), .value=&ReadSlider(124) };
sliders[125] = { .type=types.tvert, .location={{1, 2}, {510, 511}}, .options={}, .id=strlit("tvert_127"), .value=&ReadSlider(125) };
sliders[126] = { .type=types.v3, .location={{1, 2}, {522, 523}}, .options={}, .id=strlit("v3_128"), .value=&ReadSlider(126) };
sliders[127] = { .type=types.tvert, .location={{1, 2}, {524, 525}}, .options={}, .id=strlit("tvert_129"), .value=&ReadSlider(127) };
sliders[128] = { .type=types.v3, .location={{1, 2}, {536, 537}}, .options={}, .id=strlit("v3_130"), .value=&ReadSlider(128) };
sliders[129] = { .type=types.v3, .location={{1, 2}, {538, 539}}, .options={}, .id=strlit("v3_131"), .value=&ReadSlider(129) };
sliders[130] = { .type=types.v2, .location={{1, 2}, {543, 544}}, .options={}, .id=strlit("v2_132"), .value=&ReadSlider(130) };
sliders[131] = { .type=types.v3, .location={{1, 2}, {546, 547}}, .options={}, .id=strlit("v3_133"), .value=&ReadSlider(131) };
sliders[132] = { .type=types.v2, .location={{1, 2}, {555, 556}}, .options={}, .id=strlit("v2_134"), .value=&ReadSlider(132) };
sliders[133] = { .type=types.v2, .location={{1, 2}, {557, 558}}, .options={}, .id=strlit("v2_135"), .value=&ReadSlider(133) };
sliders[134] = { .type=types.v2, .location={{1, 2}, {559, 560}}, .options={}, .id=strlit("v2_136"), .value=&ReadSlider(134) };
sliders[135] = { .type=types.v3, .location={{1, 2}, {563, 564}}, .options={}, .id=strlit("v3_137"), .value=&ReadSlider(135) };
sliders[136] = { .type=types.v2, .location={{1, 2}, {565, 566}}, .options={}, .id=strlit("v2_138"), .value=&ReadSlider(136) };
sliders[137] = { .type=types.v2, .location={{1, 2}, {569, 570}}, .options={}, .id=strlit("v2_139"), .value=&ReadSlider(137) };
sliders[138] = { .type=types.v2, .location={{1, 2}, {571, 572}}, .options={}, .id=strlit("v2_140"), .value=&ReadSlider(138) };
sliders[139] = { .type=types.v2, .location={{1, 2}, {573, 574}}, .options={}, .id=strlit("v2_141"), .value=&ReadSlider(139) };
sliders[140] = { .type=types.v3, .location={{1, 2}, {577, 578}}, .options={}, .id=strlit("v3_142"), .value=&ReadSlider(140) };
sliders[141] = { .type=types.v2, .location={{1, 2}, {579, 580}}, .options={}, .id=strlit("v2_143"), .value=&ReadSlider(141) };
sliders[142] = { .type=types.tvert, .location={{1, 2}, {581, 582}}, .options={}, .id=strlit("tvert_144"), .value=&ReadSlider(142) };
sliders[143] = { .type=types.v2, .location={{1, 2}, {585, 586}}, .options={}, .id=strlit("v2_145"), .value=&ReadSlider(143) };
sliders[144] = { .type=types.v2, .location={{1, 2}, {587, 588}}, .options={}, .id=strlit("v2_146"), .value=&ReadSlider(144) };
sliders[145] = { .type=types.tvert, .location={{1, 2}, {596, 597}}, .options={}, .id=strlit("tvert_147"), .value=&ReadSlider(145) };
sliders[146] = { .type=types.tvert, .location={{1, 2}, {606, 607}}, .options={}, .id=strlit("tvert_148"), .value=&ReadSlider(146) };
sliders[147] = { .type=types.tvert, .location={{1, 2}, {608, 609}}, .options={}, .id=strlit("tvert_149"), .value=&ReadSlider(147) };
sliders[148] = { .type=types.v2, .location={{1, 2}, {621, 622}}, .options={}, .id=strlit("v2_150"), .value=&ReadSlider(148) };
sliders[149] = { .type=types.v2, .location={{1, 2}, {625, 626}}, .options={}, .id=strlit("v2_151"), .value=&ReadSlider(149) };
sliders[150] = { .type=types.tvert, .location={{1, 2}, {628, 629}}, .options={}, .id=strlit("tvert_152"), .value=&ReadSlider(150) };
sliders[151] = { .type=types.tvert, .location={{1, 2}, {632, 633}}, .options={}, .id=strlit("tvert_153"), .value=&ReadSlider(151) };
sliders[152] = { .type=types.tvert, .location={{1, 2}, {634, 635}}, .options={}, .id=strlit("tvert_154"), .value=&ReadSlider(152) };
sliders[153] = { .type=types.v2, .location={{1, 2}, {655, 656}}, .options={}, .id=strlit("v2_155"), .value=&ReadSlider(153) };
sliders[154] = { .type=types.v2, .location={{1, 2}, {659, 660}}, .options={}, .id=strlit("v2_156"), .value=&ReadSlider(154) };
sliders[155] = { .type=types.tvert, .location={{1, 2}, {662, 663}}, .options={}, .id=strlit("tvert_157"), .value=&ReadSlider(155) };
sliders[156] = { .type=types.v1, .location={{1, 2}, {664, 665}}, .options={}, .id=strlit("v1_158"), .value=&ReadSlider(156) };
sliders[157] = { .type=types.tvert, .location={{1, 2}, {678, 679}}, .options={}, .id=strlit("tvert_159"), .value=&ReadSlider(157) };
sliders[158] = { .type=types.v2, .location={{1, 2}, {685, 686}}, .options={}, .id=strlit("v2_160"), .value=&ReadSlider(158) };
sliders[159] = { .type=types.v3, .location={{1, 2}, {688, 689}}, .options={}, .id=strlit("v3_161"), .value=&ReadSlider(159) };
sliders[160] = { .type=types.tvert, .location={{1, 2}, {690, 691}}, .options={}, .id=strlit("tvert_162"), .value=&ReadSlider(160) };
sliders[161] = { .type=types.Curve, .location={{1, 2}, {718, 720}}, .options={}, .id=strlit("Curve_1"), .value=&ReadSlider(161) };
sliders[162] = { .type=types.Curve, .location={{1, 2}, {722, 724}}, .options={}, .id=strlit("Curve_2"), .value=&ReadSlider(162) };
sliders[163] = { .type=types.tvert, .location={{1, 2}, {726, 727}}, .options={}, .id=strlit("tvert_168"), .value=&ReadSlider(163) };
sliders[164] = { .type=types.tvert, .location={{1, 2}, {740, 741}}, .options={}, .id=strlit("tvert_169"), .value=&ReadSlider(164) };
sliders[165] = { .type=types.tvert, .location={{1, 2}, {742, 743}}, .options={}, .id=strlit("tvert_170"), .value=&ReadSlider(165) };
sliders[166] = { .type=types.tvert, .location={{1, 2}, {748, 749}}, .options={}, .id=strlit("tvert_171"), .value=&ReadSlider(166) };
sliders[167] = { .type=types.tvert, .location={{1, 2}, {754, 755}}, .options={}, .id=strlit("tvert_172"), .value=&ReadSlider(167) };
sliders[168] = { .type=types.tvert, .location={{1, 2}, {758, 759}}, .options={}, .id=strlit("tvert_173"), .value=&ReadSlider(168) };
sliders[169] = { .type=types.v3, .location={{1, 2}, {760, 761}}, .options={}, .id=strlit("v3_174"), .value=&ReadSlider(169) };
sliders[170] = { .type=types.tvert, .location={{1, 2}, {766, 767}}, .options={}, .id=strlit("tvert_175"), .value=&ReadSlider(170) };
sliders[171] = { .type=types.tvert, .location={{1, 2}, {768, 769}}, .options={}, .id=strlit("tvert_176"), .value=&ReadSlider(171) };
sliders[172] = { .type=types.i1, .location={{1, 2}, {796, 797}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_181"), .value=&ReadSlider(172) };
sliders[173] = { .type=types.v3, .location={{1, 2}, {804, 805}}, .options={}, .id=strlit("v3_182"), .value=&ReadSlider(173) };
sliders[174] = { .type=types.v3, .location={{1, 2}, {806, 807}}, .options={}, .id=strlit("v3_183"), .value=&ReadSlider(174) };
sliders[175] = { .type=types.v1, .location={{1, 2}, {808, 809}}, .options={}, .id=strlit("v1_184"), .value=&ReadSlider(175) };
sliders[176] = { .type=types.tvert, .location={{1, 2}, {810, 811}}, .options={}, .id=strlit("tvert_194"), .value=&ReadSlider(176) };
sliders[177] = { .type=types.tvert, .location={{1, 2}, {812, 813}}, .options={}, .id=strlit("tvert_195"), .value=&ReadSlider(177) };
sliders[178] = { .type=types.tvert, .location={{1, 2}, {814, 815}}, .options={}, .id=strlit("tvert_200"), .value=&ReadSlider(178) };
sliders[179] = { .type=types.tvert, .location={{1, 2}, {816, 817}}, .options={}, .id=strlit("tvert_201"), .value=&ReadSlider(179) };
sliders[180] = { .type=types.tvert, .location={{1, 2}, {822, 823}}, .options={}, .id=strlit("tvert_202"), .value=&ReadSlider(180) };
sliders[181] = { .type=types.tvert, .location={{1, 2}, {826, 827}}, .options={}, .id=strlit("tvert_208"), .value=&ReadSlider(181) };
sliders[182] = { .type=types.tvert, .location={{1, 2}, {828, 829}}, .options={}, .id=strlit("tvert_213"), .value=&ReadSlider(182) };
sliders[183] = { .type=types.tvert, .location={{1, 2}, {830, 831}}, .options={}, .id=strlit("tvert_214"), .value=&ReadSlider(183) };
sliders[184] = { .type=types.tvert, .location={{1, 2}, {834, 835}}, .options={}, .id=strlit("tvert_215"), .value=&ReadSlider(184) };
sliders[185] = { .type=types.tvert, .location={{1, 2}, {836, 837}}, .options={}, .id=strlit("tvert_216"), .value=&ReadSlider(185) };
sliders[186] = { .type=types.v3, .location={{1, 2}, {838, 839}}, .options={}, .id=strlit("v3_217"), .value=&ReadSlider(186) };
sliders[187] = { .type=types.v3, .location={{1, 2}, {840, 841}}, .options={}, .id=strlit("v3_218"), .value=&ReadSlider(187) };
sliders[188] = { .type=types.tvert, .location={{1, 2}, {846, 847}}, .options={}, .id=strlit("tvert_219"), .value=&ReadSlider(188) };
sliders[189] = { .type=types.v4, .location={{1, 2}, {849, 850}}, .options={}, .id=strlit("v4_220"), .value=&ReadSlider(189) };
sliders[190] = { .type=types.i2, .location={{1, 2}, {853, 854}}, .options={}, .id=strlit("i2_221"), .value=&ReadSlider(190) };
sliders[191] = { .type=types.i1, .location={{1, 2}, {872, 873}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_222"), .value=&ReadSlider(191) };
sliders[192] = { .type=types.i1, .location={{1, 2}, {874, 875}}, .options={}, .id=strlit("i1_223"), .value=&ReadSlider(192) };
sliders[193] = { .type=types.v3, .location={{1, 2}, {876, 877}}, .options={}, .id=strlit("v3_224"), .value=&ReadSlider(193) };
sliders[194] = { .type=types.tvert, .location={{1, 2}, {882, 883}}, .options={}, .id=strlit("tvert_225"), .value=&ReadSlider(194) };
sliders[195] = { .type=types.tvert, .location={{1, 2}, {890, 891}}, .options={}, .id=strlit("tvert_226"), .value=&ReadSlider(195) };
sliders[196] = { .type=types.tvert, .location={{1, 2}, {894, 895}}, .options={}, .id=strlit("tvert_227"), .value=&ReadSlider(196) };
sliders[197] = { .type=types.tvert, .location={{1, 2}, {898, 899}}, .options={}, .id=strlit("tvert_228"), .value=&ReadSlider(197) };
sliders[198] = { .type=types.tvert, .location={{1, 2}, {902, 903}}, .options={}, .id=strlit("tvert_229"), .value=&ReadSlider(198) };
sliders[199] = { .type=types.tvert, .location={{1, 2}, {906, 907}}, .options={}, .id=strlit("tvert_230"), .value=&ReadSlider(199) };
sliders[200] = { .type=types.tvert, .location={{1, 2}, {910, 911}}, .options={}, .id=strlit("tvert_231"), .value=&ReadSlider(200) };
sliders[201] = { .type=types.tvert, .location={{1, 2}, {914, 915}}, .options={}, .id=strlit("tvert_232"), .value=&ReadSlider(201) };
sliders[202] = { .type=types.i1, .location={{1, 2}, {920, 921}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_233"), .value=&ReadSlider(202) };
sliders[203] = { .type=types.v1, .location={{1, 2}, {922, 923}}, .options={}, .id=strlit("v1_234"), .value=&ReadSlider(203) };
sliders[204] = { .type=types.v1, .location={{1, 2}, {924, 925}}, .options={}, .id=strlit("v1_235"), .value=&ReadSlider(204) };
sliders[205] = { .type=types.i1, .location={{1, 2}, {926, 927}}, .options={.flags = Slider_Clamp_01}, .id=strlit("i1_236"), .value=&ReadSlider(205) };
sliders[206] = { .type=types.tvert, .location={{1, 2}, {932, 933}}, .options={}, .id=strlit("tvert_237"), .value=&ReadSlider(206) };
}
//-
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1334:
global_decl Text_Object text_objects_[257];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1339:
global FUI_File_Data fui_files_[3] ={
{},
{
 .index = 1,
 .name = strlit("driver_animate.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_1)},
 .text_objects = make_slice(text_objects_, {0,0}),
 .sliders = make_slice(global_sliders, {0,2}),
 .vertices_info = make_slice(vertices_info_, {0,0}),
 },
{
 .index = 2,
 .name = strlit("driver.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_2)},
 .text_objects = make_slice(text_objects_, {0,257}),
 .sliders = make_slice(global_sliders, {2,207}),
 .vertices_info = make_slice(vertices_info_, {0,9}),
 },
};
