// NOTE Generated by C:\Users\vodan\4ed\code\meta\meta_print.cpp:1179:
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1010:
global i32 marked_positions_file_1[4] ={
//-NOTE: driver_animate.kc 
62,67,1877,1882,
};
global i32 marked_positions_file_2[1124] ={
//-NOTE: driver.kc 
102,153,195,241,287,354,401,460,499,550,589,640,687,746,789,844,
895,958,1007,1068,1116,1176,1217,1270,1304,1350,1397,1456,1497,1550,1591,1644,
1688,1744,1782,1832,3093,3098,3185,3194,3242,3247,3288,3293,3331,3336,3375,3381,
3407,3415,3436,3456,3476,3484,3538,3546,3578,3611,3631,3657,4215,4249,4273,4287,
4354,4365,4512,4566,4590,4616,4640,4653,4738,4766,4838,4864,4888,4916,4940,4953,
4977,4988,5024,5035,5719,5748,6064,6097,6235,6265,6366,6399,7574,7601,7607,7637,
7657,7658,7678,7705,7727,7760,7825,7856,7973,8006,8333,8364,8629,8660,8739,8774,
8999,9034,9051,9084,9091,9103,9150,9180,9811,9845,10163,10197,10217,10251,12319,12354,
12357,12372,12531,12568,12611,12807,12834,12868,12871,12926,13078,13112,13116,13186,13215,13249,
13253,13364,13390,13423,13427,13495,13571,13604,13631,13665,13669,13829,13856,13892,13896,14008,
14012,14141,14145,14265,14271,14330,14345,14363,14370,14466,14778,14829,14980,15007,15012,15071,
15076,15205,15522,15545,16032,16164,16170,16308,16383,16503,16570,16698,16970,17048,17055,17134,
17357,17449,17456,17547,18021,18029,18208,18238,18418,18449,18586,18641,18664,18666,18699,18734,
18917,18952,18997,19030,19092,19118,19123,19147,19178,19207,19212,19357,19421,19428,19461,19493,
19508,19539,19544,19655,19660,19677,19703,19705,19726,19740,19785,19786,19897,19924,19956,19963,
19969,19992,20020,20027,20050,20075,20080,20168,20226,20281,20322,20351,20454,20497,20516,20534,
20539,20559,20590,20599,20604,20641,20646,20673,20703,20736,20757,20791,20965,20987,21024,21057,
21253,21288,21292,21312,21509,21526,21940,21981,22059,22074,22169,22220,22225,22245,22354,22392,
22420,22457,22461,22497,22501,22560,22778,22812,22893,22959,23142,23171,23233,23268,23272,23293,
23329,23392,23423,23455,23646,23656,23660,23699,23789,23822,23915,23945,23948,23988,24009,24010,
24048,24080,24085,24120,24123,24151,24172,24173,24195,24228,24233,24261,24282,24283,24315,24347,
24381,24412,24445,24474,24556,24584,24605,24606,24627,24661,24816,24843,24849,24960,24966,25021,
25027,25083,25172,25216,25223,25275,25280,25322,25364,25406,25427,25429,25450,25452,25470,25472,
25478,25509,25515,25550,25579,25590,25597,25617,25623,25658,25684,25704,25726,25764,26093,26135,
26353,26415,26436,26438,26460,26462,26483,26485,26586,26593,26600,26631,26645,26679,26945,26978,
26983,27031,27036,27089,27596,27635,27715,27747,27760,27786,27800,27870,28039,28197,28220,28279,
28284,28342,28345,28380,28401,28402,28429,28463,28558,28620,28710,28740,28771,28781,28812,28841,
28843,28851,28882,28909,28934,28961,28963,28971,28998,29020,29086,29107,29115,29152,29172,29173,
29201,29229,29609,29638,29814,29849,29885,29920,29973,30000,30027,30053,30094,30122,30183,30193,
30267,30289,30317,30328,30354,30388,30410,30438,30499,30506,30511,30531,30559,30602,30794,30825,
30851,30860,30893,30919,30941,30975,30980,31005,31032,31039,31184,31244,31265,31267,31290,31292,
31313,31315,31361,31386,31410,31418,31438,31449,31493,31494,31498,31512,31640,31675,31692,31725,
31736,31770,31864,31891,31895,31957,32006,32033,32038,32052,32127,32154,32329,32361,32377,32408,
32458,32551,32555,32586,32590,32613,32617,32676,32680,32711,32889,32921,32944,32977,33013,33054,
33089,33116,33137,33138,33162,33194,33198,33241,33280,33328,33333,33383,33460,33511,33531,33533,
33554,33556,33577,33579,33583,33634,33660,33662,33684,33717,33721,33772,33792,33794,33816,33818,
33839,33841,33942,33993,34019,34021,34029,34047,34076,34078,34122,34203,34225,34227,34248,34250,
34253,34308,34490,34517,34521,34555,34775,34814,34818,34925,34929,35046,35163,35198,35202,35276,
35311,35346,35365,35399,35402,35536,35669,35679,35728,35772,35775,35805,35808,35836,36539,36569,
36589,36590,36593,36616,36637,36638,36719,36752,36755,36773,37124,37158,37179,37208,37619,37641,
37900,37933,37961,38015,38481,38656,38760,38776,38781,38796,39491,39516,39525,39562,39567,39606,
39618,39651,39672,39673,39676,39712,39733,39734,39755,39789,40068,40077,40083,40227,40391,40558,
40565,40607,40664,40815,40914,41058,41136,41289,41383,41416,41734,41754,41766,41793,41796,41826,
41847,41848,41889,41921,41961,41991,42026,42180,42209,42243,42251,42290,42297,42327,42586,42605,
42694,42804,42905,42934,42939,42968,42973,43008,43013,43040,43133,43290,43295,43409,43414,43556,
43561,43594,43625,43651,43699,43700,43705,43734,43766,43768,43789,43815,43855,43856,43886,43916,
43920,43959,44255,44313,44455,44491,44495,44532,44766,44814,45114,45166,45392,45427,45449,45484,
45549,45592,45596,45774,45791,45823,46165,46181,46228,46284,46695,46710,46713,46743,46774,46807,
46829,46861,46865,46969,46973,47078,47235,47264,47361,47394,47641,47676,47680,47802,47811,47856,
47861,47904,47909,47935,48317,48350,48706,48736,48940,48974,49073,49101,49374,49411,49520,49555,
50268,50306,50371,50414,50418,50458,50462,50496,50782,50822,50911,50954,51211,51255,51287,51331,
51855,51868,51955,52023,52074,52075,52387,52412,52477,52512,52515,52557,52560,52601,52604,52638,
53276,53322,53449,53490,53787,53849,54124,54173,54294,54338,54490,54544,54697,54739,54820,54883,
54903,54911,55195,55219,55326,55358,55829,55855,56261,56275,56774,56785,57750,57774,58277,58313,
58576,58581,58613,58624,58734,58745,58866,58906,58915,58920,58957,58996,59080,59112,59228,59252,
59831,59858,59923,59948,60044,60089,60093,60149,60153,60220,60224,60277,60284,60339,60647,60667,
60720,60903,61047,61068,61076,61122,61221,61294,61577,61748,61903,61945,61968,61998,62032,62064,
62140,62169,62584,62600,63104,63129,63336,63362,63571,63617,63629,63670,63802,63838,64001,64041,
64049,64078,64112,64146,64204,64215,64277,64308,64341,64373,64389,64426,64689,64711,64757,64779,
64866,64899,65163,65186,65478,65494,65525,65560,65815,65837,65843,65903,66303,66327,66355,66389,
66774,66797,66803,66825,66929,66978,66990,67035,67038,67098,67106,67114,67255,67268,67542,67603,
67846,67854,67946,67961,68084,68112,68267,68306,68313,68369,68388,68436,68465,68509,69051,69078,
69092,69143,69148,69205,69244,69273,69327,69334,69340,69387,69395,69432,69436,69484,69615,69648,
69666,69699,69717,69748,70031,70054,70987,71015,71332,71348,71388,71421,71437,71470,71923,71955,
71987,72016,72217,72234,72238,72294,72388,72422,72617,72629,72657,72658,72928,72952,72963,72965,
73207,73226,73706,73717,73796,73807,74017,74027,74386,74447,74538,74570,74642,74674,74691,74723,
75298,75306,75453,75458,75983,76013,76645,76687,76915,76950,76999,77047,77053,77124,77258,77293,
77314,77348,77475,77514,77535,77569,77667,77717,77738,77772,77871,77923,77944,77978,78075,78116,
78136,78171,78522,78575,78714,78748,78825,78901,79010,79044,79096,79126,79259,79314,80103,80111,
80371,80382,80716,80725,81207,81215,81422,81441,81446,81465,81639,81666,81671,81689,82118,82136,
82141,82160,82165,82184,
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1033:
global Vertex_Info vertices_info_[10] ={
{{{1, 2}, {106, 107}}, 0,1,},
{{{1, 2}, {112, 113}}, 0,1,},
{{{1, 2}, {116, 117}}, 0,},
{{{1, 2}, {128, 129}}, 0,},
{{{1, 2}, {178, 179}}, 99,},
{{{1, 2}, {200, 201}}, 0,1,},
{{{1, 2}, {632, 633}}, 0,},
{{{1, 2}, {822, 823}}, 0,},
{{{1, 2}, {1116, 1117}}, 0,1,},
{{{1, 2}, {1118, 1119}}, 0,1,},};
//-

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:940:
global Slider global_sliders[238];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:945:
struct Slider_Values{
i1 v_0;
i1 v_1;
i1 v_2;
v1 v_3;
i1 v_4;
i1 v_5;
i1 v_6;
i1 v_7;
i1 v_8;
i1 v_9;
i1 v_10;
tvert v_11;
tvert v_12;
tvert v_13;
v3 v_14;
v1 v_15;
tvert v_16;
v3 v_17;
tvert v_18;
v3 v_19;
v1 v_20;
v1 v_21;
tvert v_22;
tvert v_23;
tvert v_24;
tvert v_25;
v2 v_26;
v3 v_27;
tvert v_28;
v3 v_29;
tvert v_30;
v3 v_31;
tvert v_32;
tvert v_33;
v3 v_34;
tvert v_35;
tvert v_36;
tvert v_37;
tvert v_38;
tvert v_39;
tvert v_40;
tvert v_41;
tvert v_42;
tvert v_43;
tvert v_44;
tvert v_45;
v3 v_46;
v1 v_47;
tvert v_48;
v3 v_49;
tvert v_50;
tvert v_51;
v3 v_52;
v3 v_53;
v1 v_54;
v3 v_55;
tvert v_56;
v3 v_57;
v2 v_58;
FUI_Line_Params v_59;
v1 v_60;
v3 v_61;
v3 v_62;
tvert v_63;
tdim v_64;
tnormal v_65;
tvert v_66;
tvert v_67;
v3 v_68;
v3 v_69;
tvert v_70;
tvert v_71;
v3 v_72;
v2 v_73;
v3 v_74;
v2 v_75;
tvert v_76;
v2 v_77;
v3 v_78;
v3 v_79;
v3 v_80;
v2 v_81;
tvert v_82;
v2 v_83;
v2 v_84;
v2 v_85;
v1 v_86;
v3 v_87;
v2 v_88;
v2 v_89;
v2 v_90;
v2 v_91;
v1 v_92;
v2 v_93;
tvert v_94;
tvert v_95;
v3 v_96;
v3 v_97;
v2 v_98;
v3 v_99;
v3 v_100;
v2 v_101;
v3 v_102;
v2 v_103;
tvert v_104;
tvert v_105;
tvert v_106;
v3 v_107;
v3 v_108;
v3 v_109;
v3 v_110;
tvert v_111;
v3 v_112;
v1 v_113;
v3 v_114;
v3 v_115;
v3 v_116;
v3 v_117;
v3 v_118;
v2 v_119;
v2 v_120;
v2 v_121;
v3 v_122;
v2 v_123;
FUI_Line_Params v_124;
tvert v_125;
tvert v_126;
tvert v_127;
v3 v_128;
tvert v_129;
v3 v_130;
v3 v_131;
v2 v_132;
v3 v_133;
v2 v_134;
v2 v_135;
v2 v_136;
v3 v_137;
v2 v_138;
v2 v_139;
v2 v_140;
v2 v_141;
v3 v_142;
v2 v_143;
tvert v_144;
v2 v_145;
v2 v_146;
tvert v_147;
tvert v_148;
tvert v_149;
v2 v_150;
v2 v_151;
tvert v_152;
tvert v_153;
tvert v_154;
v2 v_155;
v2 v_156;
tvert v_157;
v1 v_158;
tvert v_159;
v2 v_160;
v3 v_161;
tvert v_162;
v3 v_163;
FUI_Line_Params v_164;
v3 v_165;
v2 v_166;
FUI_Line_Params v_167;
tvert v_168;
tvert v_169;
tvert v_170;
tvert v_171;
tvert v_172;
tvert v_173;
v3 v_174;
tvert v_175;
tvert v_176;
tvert v_177;
tvert v_178;
tdim v_179;
FUI_Line_Params v_180;
i1 v_181;
v3 v_182;
v3 v_183;
v1 v_184;
v3 v_185;
i1 v_186;
v1 v_187;
v1 v_188;
v4 v_189;
i1 v_190;
v4 v_191;
v4 v_192;
v4 v_193;
tvert v_194;
tvert v_195;
v1 v_196;
v3 v_197;
v3 v_198;
v4 v_199;
tvert v_200;
tvert v_201;
tvert v_202;
i1 v_203;
tdim v_204;
i1 v_205;
v3 v_206;
v4 v_207;
tvert v_208;
v1 v_209;
tvert v_210;
tvert v_211;
tvert v_212;
tvert v_213;
tvert v_214;
tvert v_215;
tvert v_216;
v3 v_217;
v3 v_218;
tvert v_219;
v4 v_220;
i2 v_221;
i1 v_222;
i1 v_223;
v3 v_224;
tvert v_225;
tvert v_226;
tvert v_227;
tvert v_228;
tvert v_229;
tvert v_230;
tvert v_231;
tvert v_232;
i1 v_233;
v1 v_234;
v1 v_235;
i1 v_236;
tvert v_237;
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:957:
global Slider_Values slider_values ={
3,
1,
6,
0.12f,
0,
0,
1,
12,
1,
1,
0,
mkvert(88.5015f, 0.2256f, 0.4041f),
{},
mkvert(2.8062f, -4.0188f, -0.2689f),
V3(-2.4645f, 0, 0),
0.0804f,
mkvert(0, -4.983f, 0.0321f),
V3(0, 0, 0.7916f),
mkvert(1.627f, -4.8007f, 0.f),
V3(1.6584f, 0, 0),
0.2254f,
0.0367f,
mkvert(0.f, -1.1466f, 0.3598f),
mkvert(0.1953f, -0.2348f, 0.8954f),
mkvert(-0.0282f, 0.f, -0.1236f),
mkvert(0.1531f, 0.0101f, -0.3179f),
V2(0.3712f, 0.678f),
V3(-0.0974f, 0.f, 0.0867f),
mkvert(1.007f, -1.6393f, -0.0102f),
V3(0.0764f, -0.9755f, 0.2612f),
mkvert(-0.109f, 0.8153f, -0.1578f),
V3(0.3231f, -0.0051f, -0.117f),
mkvert(-0.2068f, -1.0341f, -0.0909f),
mkvert(0.0623f, -2.6757f, 0.0176f),
V3(0.0112f, 2.5863f, 0.2802f),
mkvert(0.2669f, -2.6071f, -0.2208f),
mkvert(-0.1346f, -2.987f, -0.3612f),
mkvert(0.3755f, -3.0799f, -0.3612f),
mkvert(-0.0476f, -2.6071f, -0.2208f),
mkvert(0.3704f, -3.0096f, -0.3481f),
mkvert(0.3693f, -2.6673f, -0.2208f),
mkvert(0.4589f, -2.9094f, -0.2208f),
mkvert(0.565f, -3.0125f, -0.2208f),
mkvert(0.671f, -3.0515f, -0.2208f),
mkvert(0.5068f, -2.8209f, -0.2208f),
mkvert(0.6128f, -2.9593f, -0.2208f),
V3(-0.f, 0.2527f, -0.022f),
20.f,
mkvert(-0.0802f, 0.f, -0.1673f),
V3(0.f, -3.4844f, 0.f),
mkvert(-0.0449f, -1.0756f, -0.1775f),
mkvert(-0.0675f, 0.733f, -0.2688f),
V3(0.0669f, 0.1897f, 0.f),
V3(0.0669f, -0.0149f, 0.0235f),
.7f,
V3(-0.1216f, 0.1472f, -0.0402f),
mkvert(0.13f, 0.7829f, -0.2688f),
V3(-0.0797f, 0.296f, 0.f),
V2(0.4004f, 0.0564f),
FUI_Line_Params{.radii = V4(0.5f, 0.3333f, -0.f, 0.5f)},
.7f,
V3(-0.f, -0.1087f, 0.0612f),
V3(0.f, -1.2272f, 0.03f),
mkvert(V3(-0.0188f, 0.8291f, -0.1741f)),
mkdim(0.1116f),
mk_normal(V3(0.8662f, -0.4998f, 0.f)),
mkvert(0.2142f, 0.0729f, -0.2028f),
mkvert(-0.0076f, 0.2268f, -0.4244f),
V3(0.0328f, 0.f, 0.f),
V3(-0.0109f, -0.0068f, -0.2147f),
mkvert(-0.2013f, 0.475f, 0.1047f),
mkvert(0.0079f, -0.9224f, -0.027f),
V3(-0.211f, 0.0922f, 0.0631f),
V2(0.4652f, 0.6524f),
V3(-0.0003f, -0.0145f, 0.0005f),
V2(0.6783f, 0.6561f),
mkvert(0.0644f, -0.1135f, -0.475f),
V2(0.6411f, 0.5634f),
V3(-0.0742f, -0.5093f, 0.1103f),
V3(0.0446f, -0.1341f, 0.0966f),
V3(-0.f, -0.1879f, -0.0035f),
V2(0.5336f, 0.3928f),
mkvert(0.2431f, -1.2305f, -0.0498f),
V2(0.8346f, 0.8079f),
V2(-0.03f, -0.1844f),
V2(0.66f, 0.553f),
0.9248f,
V3(-0.2236f, 0.048f, 0.f),
V2(-0.2884f, 0.0577f),
V2(0.3494f, 0.5376f),
V2(0.0504f, -0.0868f),
V2(0.4786f, 0.4232f),
.7f,
V2(0.5981f, 0.4176f),
mkvert(0.2008f, -0.5275f, -0.1857f),
mkvert(-0.f, 0.2075f, -0.3961f),
V3(0, 0, 0),
V3(-0.f, -0.0943f, -0.2772f),
V2(0, 0),
V3(0.f, -0.0972f, 0.4466f),
V3(0.f, -0.0943f, 0.0532f),
V2(0, 0),
V3(0.f, 0.f, 0.1265f),
V2(0.539f, 0.5534f),
mkvert(0.2121f, 0.0502f, 0.f),
mkvert(0.0267f, -1.9129f, 0.f),
mkvert(-0.2363f, -1.1833f, -0.1252f),
V3(0.1879f, 0.f, -0.0369f),
V3(0.1191f, 0.0489f, 0.f),
V3(-0.0036f, -0.2325f, 0.f),
V3(0.0822f, 0.1457f, 0.f),
mkvert(-0.1753f, -0.854f, -0.0817f),
V3(0.f, -0.3293f, -0.0435f),
.7f,
V3(-0.f, 0.1052f, -0.0852f),
V3(0.0871f, 0.0251f, 0.f),
V3(0.175f, -0.0472f, 0.f),
V3(0.3198f, -0.0241f, -0.019f),
V3(0.0988f, -0.2945f, 0.f),
V2(0.5488f, 0.5653f),
V2(-0.2152f, -0.1208f),
V2(0.2632f, 0.2864f),
V3(0.145f, 0.0775f, 0.f),
V2(0, 0),
FUI_Line_Params{.radii = V4(-0.f, 1.f, 0.3333f, 0.5f)},
mkvert(-0.2345f, -0.8464f, -0.0226f),
mkvert(-0.269f, -1.3024f, 0.1898f),
mkvert(-0.1582f, -1.8388f, 0.1688f),
V3(0.1483f, -0.2286f, -0.0134f),
mkvert(0.2034f, -1.85f, 0.1108f),
V3(-0.0612f, 0.1097f, -0.1467f),
V3(-0.0131f, -0.0681f, -0.1431f),
V2(0.4301f, 0.4733f),
V3(0.0913f, -0.0708f, -0.1431f),
V2(0.383f, 0.5666f),
V2(0.1002f, 0.0001f),
V2(0.5336f, 0.3928f),
V3(0.2153f, 0.0705f, 0.f),
V2(0.0904f, -0.1979f),
V2(0.383f, 0.5666f),
V2(0.2413f, -0.0736f),
V2(0.7305f, 0.2891f),
V3(0.1982f, 0.0535f, 0.f),
V2(0, 0),
mkvert(0.2437f, -1.8644f, 0.f),
V2(-0.1626f, -0.033f),
V2(0.4261f, 0.4584f),
mkvert(-0.1204f, -1.8951f, -0.0509f),
mkvert(0.0936f, -2.5386f, -0.171f),
mkvert(-0.2725f, -0.8924f, -0.251f),
V2(0.757f, 0.8308f),
V2(0.6958f, 0.6056f),
mkvert(0.9257f, -1.5541f, 0.0573f),
mkvert(0.4819f, -1.3302f, -0.4461f),
mkvert(0.f, -1.6696f, 0.2691f),
V2(0.1558f, 0.4631f),
V2(0.1719f, 0.8044f),
mkvert(0.4909f, -1.6965f, -0.5072f),
0.87f,
mkvert(-0.2595f, 0.263f, -0.0002f),
V2(0.5258f, 0.4965f),
V3(0.0098f, -0.2771f, -0.0977f),
mkvert(0.f, -3.1104f, -0.1081f),
V3(0.0074f, 0.0744f, -0.1528f),
FUI_Line_Params{.radii = V4(0.1667f, 0.6667f, 0.5f, -0.f)},
V3(-0.0239f, -0.0363f, 0.1509f),
V2(0.1876f, 0.2575f),
FUI_Line_Params{.radii = V4(0.f, 0.5f, 0.5f, 0.f)},
mkvert(0.f, -4.2845f, -0.0495f),
mkvert(0.1045f, -2.5438f, 0.8167f),
mkvert(0.6599f, -2.4822f, 0.6002f),
mkvert(0.7613f, -2.0817f, 0.039f),
mkvert(0.1f, 0, 0),
mkvert(1.0685f, 0.8105f, -0.6117f),
V3(-0.1823f, -0.0005f, 0.9832f),
mkvert(0.f, 0.951f, 0.1677f),
mkvert(0.5102f, 1.3265f, -0.7766f),
mkvert(0.1953f, -0.2348f, 0.8954f),
mkvert(-0.0282f, 0.f, -0.1236f),
mkdim(0.4934f),
FUI_Line_Params{.radii = V4(0.1667f, 0.5f, 0.1667f, 0.1667f)},
1,
V3(0.f, 0.0237f, 0.0916f),
V3(0, 0, -0.0856f),
0.5871f,
V3(0.f, 0.078f, 0.035f),
0,
2.6675f,
0.0133f,
V4(0.4876f, 0.3631f, 0.5066f, -0.2905f),
1,
V4(0.0017f, 2.3506f, 1.2313f, 2.2549f),
V4(-0.0828f, 0.5237f, 0.f, 0.f),
V4(0.f, 5.0751f, 0.f, 0.f),
mkvert(0.f, -0.0651f, -0.1755f),
mkvert(0.585f, -0.1342f, 0.5485f),
2.4829f,
V3(0.1697f, 0.0034f, -0.3328f),
V3(-0.0639f, -0.5264f, 0.1141f),
V4(0.25f, 1.9122f, 0.7259f, 0.9839f),
mkvert(0.6208f, 0.1421f, -0.4585f),
mkvert(0.2242f, 0.6295f, -1.1258f),
mkvert(0.4676f, -0.7579f, -0.1264f),
0,
mkdim(0.2448f),
0,
V3(0.f, -0.0704f, -0.0417f),
V4(0.1672f, 2.0761f, 1.3853f, 3.0361f),
mkvert(0.f, -1.1949f, 0.3195f),
.8f,
mkvert(0.2651f, -0.5154f, 0.8715f),
mkvert(0.5636f, -0.3601f, 0.5385f),
mkvert(0.5266f, -0.6385f, 0.68f),
mkvert(0.f, 1.087f, 0.f),
mkvert(0.f, -0.0929f, 1.042f),
mkvert(0.0537f, 0.1334f, -0.0695f),
mkvert(0.7418f, -0.0689f, 0.6115f),
V3(0.1302f, -0.0069f, -0.0297f),
V3(0.0001f, 0.2158f, 0.056f),
mkvert(0.7814f, -1.6599f, -0.6047f),
V4(0.5f, 1.f, 1.f, 0.0862f),
I2(0, 4),
0,
0,
V3(0.1427f, 0.1147f, -0.064f),
mkvert(-0.2112f, -4.5306f, -0.2689f),
mkvert(1.7822f, -6.9027f, -0.2689f),
mkvert(1.8527f, -6.8952f, -0.2689f),
mkvert(1.2723f, -4.8425f, -0.2689f),
mkvert(1.0471f, -6.2154f, -0.2689f),
mkvert(-0.5712f, -6.2775f, -0.2689f),
mkvert(2.1904f, -3.8928f, -0.2689f),
mkvert(-0.2112f, -3.9204f, 0.5898f),
1,
3.0044f,
0.03f,
0,
mkvert(1.019f, 0.5494f, 0.f),
};
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:978:
function void
 init_sliders(Type_Info_Pointers &types)
{
Slider *sliders = global_sliders;
sliders[0] = { .type=types.i1, .location={{1, 1}, {0, 1}}, .options={}, .value=&ReadSlider(0) };
sliders[1] = { .type=types.i1, .location={{1, 1}, {2, 3}}, .options={}, .value=&ReadSlider(1) };
sliders[2] = { .type=types.i1, .location={{1, 2}, {36, 37}}, .options={}, .value=&ReadSlider(2) };
sliders[3] = { .type=types.v1, .location={{1, 2}, {38, 39}}, .options={}, .value=&ReadSlider(3) };
sliders[4] = { .type=types.i1, .location={{1, 2}, {40, 41}}, .options={}, .value=&ReadSlider(4) };
sliders[5] = { .type=types.i1, .location={{1, 2}, {42, 43}}, .options={}, .value=&ReadSlider(5) };
sliders[6] = { .type=types.i1, .location={{1, 2}, {44, 45}}, .options={}, .value=&ReadSlider(6) };
sliders[7] = { .type=types.i1, .location={{1, 2}, {46, 47}}, .options={}, .value=&ReadSlider(7) };
sliders[8] = { .type=types.i1, .location={{1, 2}, {48, 49}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(8) };
sliders[9] = { .type=types.i1, .location={{1, 2}, {52, 53}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(9) };
sliders[10] = { .type=types.i1, .location={{1, 2}, {54, 55}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(10) };
sliders[11] = { .type=types.tvert, .location={{1, 2}, {56, 57}}, .options={}, .value=&ReadSlider(11) };
sliders[12] = { .type=types.tvert, .location={{1, 2}, {58, 59}}, .options={}, .value=&ReadSlider(12) };
sliders[13] = { .type=types.tvert, .location={{1, 2}, {60, 61}}, .options={}, .value=&ReadSlider(13) };
sliders[14] = { .type=types.v3, .location={{1, 2}, {62, 63}}, .options={}, .value=&ReadSlider(14) };
sliders[15] = { .type=types.v1, .location={{1, 2}, {64, 65}}, .options={}, .value=&ReadSlider(15) };
sliders[16] = { .type=types.tvert, .location={{1, 2}, {68, 69}}, .options={}, .value=&ReadSlider(16) };
sliders[17] = { .type=types.v3, .location={{1, 2}, {70, 71}}, .options={}, .value=&ReadSlider(17) };
sliders[18] = { .type=types.tvert, .location={{1, 2}, {76, 77}}, .options={}, .value=&ReadSlider(18) };
sliders[19] = { .type=types.v3, .location={{1, 2}, {78, 79}}, .options={}, .value=&ReadSlider(19) };
sliders[20] = { .type=types.v1, .location={{1, 2}, {80, 81}}, .options={}, .value=&ReadSlider(20) };
sliders[21] = { .type=types.v1, .location={{1, 2}, {82, 83}}, .options={}, .value=&ReadSlider(21) };
sliders[22] = { .type=types.tvert, .location={{1, 2}, {84, 85}}, .options={}, .value=&ReadSlider(22) };
sliders[23] = { .type=types.tvert, .location={{1, 2}, {86, 87}}, .options={}, .value=&ReadSlider(23) };
sliders[24] = { .type=types.tvert, .location={{1, 2}, {88, 89}}, .options={}, .value=&ReadSlider(24) };
sliders[25] = { .type=types.tvert, .location={{1, 2}, {90, 91}}, .options={}, .value=&ReadSlider(25) };
sliders[26] = { .type=types.v2, .location={{1, 2}, {95, 96}}, .options={}, .value=&ReadSlider(26) };
sliders[27] = { .type=types.v3, .location={{1, 2}, {98, 99}}, .options={}, .value=&ReadSlider(27) };
sliders[28] = { .type=types.tvert, .location={{1, 2}, {100, 101}}, .options={}, .value=&ReadSlider(28) };
sliders[29] = { .type=types.v3, .location={{1, 2}, {102, 103}}, .options={}, .value=&ReadSlider(29) };
sliders[30] = { .type=types.tvert, .location={{1, 2}, {104, 105}}, .options={}, .value=&ReadSlider(30) };
sliders[31] = { .type=types.v3, .location={{1, 2}, {108, 109}}, .options={}, .value=&ReadSlider(31) };
sliders[32] = { .type=types.tvert, .location={{1, 2}, {110, 111}}, .options={}, .value=&ReadSlider(32) };
sliders[33] = { .type=types.tvert, .location={{1, 2}, {114, 115}}, .options={}, .value=&ReadSlider(33) };
sliders[34] = { .type=types.v3, .location={{1, 2}, {118, 119}}, .options={}, .value=&ReadSlider(34) };
sliders[35] = { .type=types.tvert, .location={{1, 2}, {120, 121}}, .options={}, .value=&ReadSlider(35) };
sliders[36] = { .type=types.tvert, .location={{1, 2}, {122, 123}}, .options={}, .value=&ReadSlider(36) };
sliders[37] = { .type=types.tvert, .location={{1, 2}, {124, 125}}, .options={}, .value=&ReadSlider(37) };
sliders[38] = { .type=types.tvert, .location={{1, 2}, {126, 127}}, .options={}, .value=&ReadSlider(38) };
sliders[39] = { .type=types.tvert, .location={{1, 2}, {134, 135}}, .options={}, .value=&ReadSlider(39) };
sliders[40] = { .type=types.tvert, .location={{1, 2}, {138, 139}}, .options={}, .value=&ReadSlider(40) };
sliders[41] = { .type=types.tvert, .location={{1, 2}, {142, 143}}, .options={}, .value=&ReadSlider(41) };
sliders[42] = { .type=types.tvert, .location={{1, 2}, {146, 147}}, .options={}, .value=&ReadSlider(42) };
sliders[43] = { .type=types.tvert, .location={{1, 2}, {150, 151}}, .options={}, .value=&ReadSlider(43) };
sliders[44] = { .type=types.tvert, .location={{1, 2}, {152, 153}}, .options={}, .value=&ReadSlider(44) };
sliders[45] = { .type=types.tvert, .location={{1, 2}, {156, 157}}, .options={}, .value=&ReadSlider(45) };
sliders[46] = { .type=types.v3, .location={{1, 2}, {172, 173}}, .options={}, .value=&ReadSlider(46) };
sliders[47] = { .type=types.v1, .location={{1, 2}, {196, 197}}, .options={}, .value=&ReadSlider(47) };
sliders[48] = { .type=types.tvert, .location={{1, 2}, {198, 199}}, .options={}, .value=&ReadSlider(48) };
sliders[49] = { .type=types.v3, .location={{1, 2}, {203, 204}}, .options={}, .value=&ReadSlider(49) };
sliders[50] = { .type=types.tvert, .location={{1, 2}, {206, 207}}, .options={}, .value=&ReadSlider(50) };
sliders[51] = { .type=types.tvert, .location={{1, 2}, {210, 211}}, .options={}, .value=&ReadSlider(51) };
sliders[52] = { .type=types.v3, .location={{1, 2}, {212, 213}}, .options={}, .value=&ReadSlider(52) };
sliders[53] = { .type=types.v3, .location={{1, 2}, {215, 216}}, .options={}, .value=&ReadSlider(53) };
sliders[54] = { .type=types.v1, .location={{1, 2}, {220, 221}}, .options={}, .value=&ReadSlider(54) };
sliders[55] = { .type=types.v3, .location={{1, 2}, {222, 223}}, .options={}, .value=&ReadSlider(55) };
sliders[56] = { .type=types.tvert, .location={{1, 2}, {224, 225}}, .options={}, .value=&ReadSlider(56) };
sliders[57] = { .type=types.v3, .location={{1, 2}, {229, 230}}, .options={}, .value=&ReadSlider(57) };
sliders[58] = { .type=types.v2, .location={{1, 2}, {231, 232}}, .options={}, .value=&ReadSlider(58) };
sliders[59] = { .type=types.FUI_Line_Params, .location={{1, 2}, {233, 234}}, .options={}, .value=&ReadSlider(59) };
sliders[60] = { .type=types.v1, .location={{1, 2}, {238, 239}}, .options={}, .value=&ReadSlider(60) };
sliders[61] = { .type=types.v3, .location={{1, 2}, {241, 242}}, .options={}, .value=&ReadSlider(61) };
sliders[62] = { .type=types.v3, .location={{1, 2}, {244, 245}}, .options={}, .value=&ReadSlider(62) };
sliders[63] = { .type=types.tvert, .location={{1, 2}, {252, 253}}, .options={}, .value=&ReadSlider(63) };
sliders[64] = { .type=types.tdim, .location={{1, 2}, {254, 255}}, .options={}, .value=&ReadSlider(64) };
sliders[65] = { .type=types.tnormal, .location={{1, 2}, {257, 258}}, .options={}, .value=&ReadSlider(65) };
sliders[66] = { .type=types.tvert, .location={{1, 2}, {264, 265}}, .options={}, .value=&ReadSlider(66) };
sliders[67] = { .type=types.tvert, .location={{1, 2}, {266, 267}}, .options={}, .value=&ReadSlider(67) };
sliders[68] = { .type=types.v3, .location={{1, 2}, {268, 269}}, .options={}, .value=&ReadSlider(68) };
sliders[69] = { .type=types.v3, .location={{1, 2}, {270, 271}}, .options={}, .value=&ReadSlider(69) };
sliders[70] = { .type=types.tvert, .location={{1, 2}, {306, 307}}, .options={}, .value=&ReadSlider(70) };
sliders[71] = { .type=types.tvert, .location={{1, 2}, {312, 313}}, .options={}, .value=&ReadSlider(71) };
sliders[72] = { .type=types.v3, .location={{1, 2}, {314, 315}}, .options={}, .value=&ReadSlider(72) };
sliders[73] = { .type=types.v2, .location={{1, 2}, {317, 318}}, .options={}, .value=&ReadSlider(73) };
sliders[74] = { .type=types.v3, .location={{1, 2}, {320, 321}}, .options={}, .value=&ReadSlider(74) };
sliders[75] = { .type=types.v2, .location={{1, 2}, {325, 326}}, .options={}, .value=&ReadSlider(75) };
sliders[76] = { .type=types.tvert, .location={{1, 2}, {328, 329}}, .options={}, .value=&ReadSlider(76) };
sliders[77] = { .type=types.v2, .location={{1, 2}, {331, 332}}, .options={}, .value=&ReadSlider(77) };
sliders[78] = { .type=types.v3, .location={{1, 2}, {334, 335}}, .options={}, .value=&ReadSlider(78) };
sliders[79] = { .type=types.v3, .location={{1, 2}, {336, 337}}, .options={}, .value=&ReadSlider(79) };
sliders[80] = { .type=types.v3, .location={{1, 2}, {338, 339}}, .options={}, .value=&ReadSlider(80) };
sliders[81] = { .type=types.v2, .location={{1, 2}, {341, 342}}, .options={}, .value=&ReadSlider(81) };
sliders[82] = { .type=types.tvert, .location={{1, 2}, {344, 345}}, .options={}, .value=&ReadSlider(82) };
sliders[83] = { .type=types.v2, .location={{1, 2}, {361, 362}}, .options={}, .value=&ReadSlider(83) };
sliders[84] = { .type=types.v2, .location={{1, 2}, {363, 364}}, .options={}, .value=&ReadSlider(84) };
sliders[85] = { .type=types.v2, .location={{1, 2}, {365, 366}}, .options={}, .value=&ReadSlider(85) };
sliders[86] = { .type=types.v1, .location={{1, 2}, {372, 373}}, .options={}, .value=&ReadSlider(86) };
sliders[87] = { .type=types.v3, .location={{1, 2}, {377, 378}}, .options={}, .value=&ReadSlider(87) };
sliders[88] = { .type=types.v2, .location={{1, 2}, {379, 380}}, .options={}, .value=&ReadSlider(88) };
sliders[89] = { .type=types.v2, .location={{1, 2}, {385, 386}}, .options={}, .value=&ReadSlider(89) };
sliders[90] = { .type=types.v2, .location={{1, 2}, {387, 388}}, .options={}, .value=&ReadSlider(90) };
sliders[91] = { .type=types.v2, .location={{1, 2}, {389, 390}}, .options={}, .value=&ReadSlider(91) };
sliders[92] = { .type=types.v1, .location={{1, 2}, {392, 393}}, .options={}, .value=&ReadSlider(92) };
sliders[93] = { .type=types.v2, .location={{1, 2}, {419, 420}}, .options={}, .value=&ReadSlider(93) };
sliders[94] = { .type=types.tvert, .location={{1, 2}, {422, 423}}, .options={}, .value=&ReadSlider(94) };
sliders[95] = { .type=types.tvert, .location={{1, 2}, {426, 427}}, .options={}, .value=&ReadSlider(95) };
sliders[96] = { .type=types.v3, .location={{1, 2}, {428, 429}}, .options={}, .value=&ReadSlider(96) };
sliders[97] = { .type=types.v3, .location={{1, 2}, {430, 431}}, .options={}, .value=&ReadSlider(97) };
sliders[98] = { .type=types.v2, .location={{1, 2}, {432, 433}}, .options={}, .value=&ReadSlider(98) };
sliders[99] = { .type=types.v3, .location={{1, 2}, {434, 435}}, .options={}, .value=&ReadSlider(99) };
sliders[100] = { .type=types.v3, .location={{1, 2}, {436, 437}}, .options={}, .value=&ReadSlider(100) };
sliders[101] = { .type=types.v2, .location={{1, 2}, {438, 439}}, .options={}, .value=&ReadSlider(101) };
sliders[102] = { .type=types.v3, .location={{1, 2}, {440, 441}}, .options={}, .value=&ReadSlider(102) };
sliders[103] = { .type=types.v2, .location={{1, 2}, {445, 446}}, .options={}, .value=&ReadSlider(103) };
sliders[104] = { .type=types.tvert, .location={{1, 2}, {448, 449}}, .options={}, .value=&ReadSlider(104) };
sliders[105] = { .type=types.tvert, .location={{1, 2}, {450, 451}}, .options={}, .value=&ReadSlider(105) };
sliders[106] = { .type=types.tvert, .location={{1, 2}, {454, 455}}, .options={}, .value=&ReadSlider(106) };
sliders[107] = { .type=types.v3, .location={{1, 2}, {456, 457}}, .options={}, .value=&ReadSlider(107) };
sliders[108] = { .type=types.v3, .location={{1, 2}, {458, 459}}, .options={}, .value=&ReadSlider(108) };
sliders[109] = { .type=types.v3, .location={{1, 2}, {460, 461}}, .options={}, .value=&ReadSlider(109) };
sliders[110] = { .type=types.v3, .location={{1, 2}, {465, 466}}, .options={}, .value=&ReadSlider(110) };
sliders[111] = { .type=types.tvert, .location={{1, 2}, {468, 469}}, .options={}, .value=&ReadSlider(111) };
sliders[112] = { .type=types.v3, .location={{1, 2}, {470, 471}}, .options={}, .value=&ReadSlider(112) };
sliders[113] = { .type=types.v1, .location={{1, 2}, {472, 473}}, .options={}, .value=&ReadSlider(113) };
sliders[114] = { .type=types.v3, .location={{1, 2}, {475, 476}}, .options={}, .value=&ReadSlider(114) };
sliders[115] = { .type=types.v3, .location={{1, 2}, {479, 480}}, .options={}, .value=&ReadSlider(115) };
sliders[116] = { .type=types.v3, .location={{1, 2}, {482, 483}}, .options={}, .value=&ReadSlider(116) };
sliders[117] = { .type=types.v3, .location={{1, 2}, {484, 485}}, .options={}, .value=&ReadSlider(117) };
sliders[118] = { .type=types.v3, .location={{1, 2}, {487, 488}}, .options={}, .value=&ReadSlider(118) };
sliders[119] = { .type=types.v2, .location={{1, 2}, {491, 492}}, .options={}, .value=&ReadSlider(119) };
sliders[120] = { .type=types.v2, .location={{1, 2}, {493, 494}}, .options={}, .value=&ReadSlider(120) };
sliders[121] = { .type=types.v2, .location={{1, 2}, {495, 496}}, .options={}, .value=&ReadSlider(121) };
sliders[122] = { .type=types.v3, .location={{1, 2}, {498, 499}}, .options={}, .value=&ReadSlider(122) };
sliders[123] = { .type=types.v2, .location={{1, 2}, {500, 501}}, .options={}, .value=&ReadSlider(123) };
sliders[124] = { .type=types.FUI_Line_Params, .location={{1, 2}, {503, 504}}, .options={}, .value=&ReadSlider(124) };
sliders[125] = { .type=types.tvert, .location={{1, 2}, {508, 509}}, .options={}, .value=&ReadSlider(125) };
sliders[126] = { .type=types.tvert, .location={{1, 2}, {510, 511}}, .options={}, .value=&ReadSlider(126) };
sliders[127] = { .type=types.tvert, .location={{1, 2}, {512, 513}}, .options={}, .value=&ReadSlider(127) };
sliders[128] = { .type=types.v3, .location={{1, 2}, {524, 525}}, .options={}, .value=&ReadSlider(128) };
sliders[129] = { .type=types.tvert, .location={{1, 2}, {526, 527}}, .options={}, .value=&ReadSlider(129) };
sliders[130] = { .type=types.v3, .location={{1, 2}, {538, 539}}, .options={}, .value=&ReadSlider(130) };
sliders[131] = { .type=types.v3, .location={{1, 2}, {540, 541}}, .options={}, .value=&ReadSlider(131) };
sliders[132] = { .type=types.v2, .location={{1, 2}, {545, 546}}, .options={}, .value=&ReadSlider(132) };
sliders[133] = { .type=types.v3, .location={{1, 2}, {548, 549}}, .options={}, .value=&ReadSlider(133) };
sliders[134] = { .type=types.v2, .location={{1, 2}, {557, 558}}, .options={}, .value=&ReadSlider(134) };
sliders[135] = { .type=types.v2, .location={{1, 2}, {559, 560}}, .options={}, .value=&ReadSlider(135) };
sliders[136] = { .type=types.v2, .location={{1, 2}, {561, 562}}, .options={}, .value=&ReadSlider(136) };
sliders[137] = { .type=types.v3, .location={{1, 2}, {565, 566}}, .options={}, .value=&ReadSlider(137) };
sliders[138] = { .type=types.v2, .location={{1, 2}, {567, 568}}, .options={}, .value=&ReadSlider(138) };
sliders[139] = { .type=types.v2, .location={{1, 2}, {571, 572}}, .options={}, .value=&ReadSlider(139) };
sliders[140] = { .type=types.v2, .location={{1, 2}, {573, 574}}, .options={}, .value=&ReadSlider(140) };
sliders[141] = { .type=types.v2, .location={{1, 2}, {575, 576}}, .options={}, .value=&ReadSlider(141) };
sliders[142] = { .type=types.v3, .location={{1, 2}, {579, 580}}, .options={}, .value=&ReadSlider(142) };
sliders[143] = { .type=types.v2, .location={{1, 2}, {581, 582}}, .options={}, .value=&ReadSlider(143) };
sliders[144] = { .type=types.tvert, .location={{1, 2}, {583, 584}}, .options={}, .value=&ReadSlider(144) };
sliders[145] = { .type=types.v2, .location={{1, 2}, {587, 588}}, .options={}, .value=&ReadSlider(145) };
sliders[146] = { .type=types.v2, .location={{1, 2}, {589, 590}}, .options={}, .value=&ReadSlider(146) };
sliders[147] = { .type=types.tvert, .location={{1, 2}, {598, 599}}, .options={}, .value=&ReadSlider(147) };
sliders[148] = { .type=types.tvert, .location={{1, 2}, {608, 609}}, .options={}, .value=&ReadSlider(148) };
sliders[149] = { .type=types.tvert, .location={{1, 2}, {610, 611}}, .options={}, .value=&ReadSlider(149) };
sliders[150] = { .type=types.v2, .location={{1, 2}, {623, 624}}, .options={}, .value=&ReadSlider(150) };
sliders[151] = { .type=types.v2, .location={{1, 2}, {627, 628}}, .options={}, .value=&ReadSlider(151) };
sliders[152] = { .type=types.tvert, .location={{1, 2}, {630, 631}}, .options={}, .value=&ReadSlider(152) };
sliders[153] = { .type=types.tvert, .location={{1, 2}, {634, 635}}, .options={}, .value=&ReadSlider(153) };
sliders[154] = { .type=types.tvert, .location={{1, 2}, {636, 637}}, .options={}, .value=&ReadSlider(154) };
sliders[155] = { .type=types.v2, .location={{1, 2}, {657, 658}}, .options={}, .value=&ReadSlider(155) };
sliders[156] = { .type=types.v2, .location={{1, 2}, {661, 662}}, .options={}, .value=&ReadSlider(156) };
sliders[157] = { .type=types.tvert, .location={{1, 2}, {664, 665}}, .options={}, .value=&ReadSlider(157) };
sliders[158] = { .type=types.v1, .location={{1, 2}, {666, 667}}, .options={}, .value=&ReadSlider(158) };
sliders[159] = { .type=types.tvert, .location={{1, 2}, {680, 681}}, .options={}, .value=&ReadSlider(159) };
sliders[160] = { .type=types.v2, .location={{1, 2}, {687, 688}}, .options={}, .value=&ReadSlider(160) };
sliders[161] = { .type=types.v3, .location={{1, 2}, {690, 691}}, .options={}, .value=&ReadSlider(161) };
sliders[162] = { .type=types.tvert, .location={{1, 2}, {692, 693}}, .options={}, .value=&ReadSlider(162) };
sliders[163] = { .type=types.v3, .location={{1, 2}, {721, 722}}, .options={}, .value=&ReadSlider(163) };
sliders[164] = { .type=types.FUI_Line_Params, .location={{1, 2}, {723, 724}}, .options={}, .value=&ReadSlider(164) };
sliders[165] = { .type=types.v3, .location={{1, 2}, {727, 728}}, .options={}, .value=&ReadSlider(165) };
sliders[166] = { .type=types.v2, .location={{1, 2}, {729, 730}}, .options={}, .value=&ReadSlider(166) };
sliders[167] = { .type=types.FUI_Line_Params, .location={{1, 2}, {731, 732}}, .options={}, .value=&ReadSlider(167) };
sliders[168] = { .type=types.tvert, .location={{1, 2}, {734, 735}}, .options={}, .value=&ReadSlider(168) };
sliders[169] = { .type=types.tvert, .location={{1, 2}, {748, 749}}, .options={}, .value=&ReadSlider(169) };
sliders[170] = { .type=types.tvert, .location={{1, 2}, {750, 751}}, .options={}, .value=&ReadSlider(170) };
sliders[171] = { .type=types.tvert, .location={{1, 2}, {756, 757}}, .options={}, .value=&ReadSlider(171) };
sliders[172] = { .type=types.tvert, .location={{1, 2}, {762, 763}}, .options={}, .value=&ReadSlider(172) };
sliders[173] = { .type=types.tvert, .location={{1, 2}, {766, 767}}, .options={}, .value=&ReadSlider(173) };
sliders[174] = { .type=types.v3, .location={{1, 2}, {768, 769}}, .options={}, .value=&ReadSlider(174) };
sliders[175] = { .type=types.tvert, .location={{1, 2}, {774, 775}}, .options={}, .value=&ReadSlider(175) };
sliders[176] = { .type=types.tvert, .location={{1, 2}, {776, 777}}, .options={}, .value=&ReadSlider(176) };
sliders[177] = { .type=types.tvert, .location={{1, 2}, {788, 789}}, .options={}, .value=&ReadSlider(177) };
sliders[178] = { .type=types.tvert, .location={{1, 2}, {790, 791}}, .options={}, .value=&ReadSlider(178) };
sliders[179] = { .type=types.tdim, .location={{1, 2}, {816, 817}}, .options={}, .value=&ReadSlider(179) };
sliders[180] = { .type=types.FUI_Line_Params, .location={{1, 2}, {819, 820}}, .options={}, .value=&ReadSlider(180) };
sliders[181] = { .type=types.i1, .location={{1, 2}, {848, 849}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(181) };
sliders[182] = { .type=types.v3, .location={{1, 2}, {854, 855}}, .options={}, .value=&ReadSlider(182) };
sliders[183] = { .type=types.v3, .location={{1, 2}, {856, 857}}, .options={}, .value=&ReadSlider(183) };
sliders[184] = { .type=types.v1, .location={{1, 2}, {858, 859}}, .options={}, .value=&ReadSlider(184) };
sliders[185] = { .type=types.v3, .location={{1, 2}, {860, 861}}, .options={}, .value=&ReadSlider(185) };
sliders[186] = { .type=types.i1, .location={{1, 2}, {864, 865}}, .options={}, .value=&ReadSlider(186) };
sliders[187] = { .type=types.v1, .location={{1, 2}, {866, 867}}, .options={}, .value=&ReadSlider(187) };
sliders[188] = { .type=types.v1, .location={{1, 2}, {868, 869}}, .options={}, .value=&ReadSlider(188) };
sliders[189] = { .type=types.v4, .location={{1, 2}, {870, 871}}, .options={}, .value=&ReadSlider(189) };
sliders[190] = { .type=types.i1, .location={{1, 2}, {872, 873}}, .options={}, .value=&ReadSlider(190) };
sliders[191] = { .type=types.v4, .location={{1, 2}, {874, 875}}, .options={}, .value=&ReadSlider(191) };
sliders[192] = { .type=types.v4, .location={{1, 2}, {876, 877}}, .options={}, .value=&ReadSlider(192) };
sliders[193] = { .type=types.v4, .location={{1, 2}, {880, 881}}, .options={}, .value=&ReadSlider(193) };
sliders[194] = { .type=types.tvert, .location={{1, 2}, {908, 909}}, .options={}, .value=&ReadSlider(194) };
sliders[195] = { .type=types.tvert, .location={{1, 2}, {910, 911}}, .options={}, .value=&ReadSlider(195) };
sliders[196] = { .type=types.v1, .location={{1, 2}, {932, 933}}, .options={}, .value=&ReadSlider(196) };
sliders[197] = { .type=types.v3, .location={{1, 2}, {934, 935}}, .options={}, .value=&ReadSlider(197) };
sliders[198] = { .type=types.v3, .location={{1, 2}, {936, 937}}, .options={}, .value=&ReadSlider(198) };
sliders[199] = { .type=types.v4, .location={{1, 2}, {938, 939}}, .options={}, .value=&ReadSlider(199) };
sliders[200] = { .type=types.tvert, .location={{1, 2}, {944, 945}}, .options={}, .value=&ReadSlider(200) };
sliders[201] = { .type=types.tvert, .location={{1, 2}, {950, 951}}, .options={}, .value=&ReadSlider(201) };
sliders[202] = { .type=types.tvert, .location={{1, 2}, {958, 959}}, .options={}, .value=&ReadSlider(202) };
sliders[203] = { .type=types.i1, .location={{1, 2}, {970, 971}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(203) };
sliders[204] = { .type=types.tdim, .location={{1, 2}, {972, 973}}, .options={}, .value=&ReadSlider(204) };
sliders[205] = { .type=types.i1, .location={{1, 2}, {976, 977}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(205) };
sliders[206] = { .type=types.v3, .location={{1, 2}, {980, 981}}, .options={}, .value=&ReadSlider(206) };
sliders[207] = { .type=types.v4, .location={{1, 2}, {982, 983}}, .options={}, .value=&ReadSlider(207) };
sliders[208] = { .type=types.tvert, .location={{1, 2}, {996, 997}}, .options={}, .value=&ReadSlider(208) };
sliders[209] = { .type=types.v1, .location={{1, 2}, {998, 999}}, .options={}, .value=&ReadSlider(209) };
sliders[210] = { .type=types.tvert, .location={{1, 2}, {1006, 1007}}, .options={}, .value=&ReadSlider(210) };
sliders[211] = { .type=types.tvert, .location={{1, 2}, {1008, 1009}}, .options={}, .value=&ReadSlider(211) };
sliders[212] = { .type=types.tvert, .location={{1, 2}, {1010, 1011}}, .options={}, .value=&ReadSlider(212) };
sliders[213] = { .type=types.tvert, .location={{1, 2}, {1012, 1013}}, .options={}, .value=&ReadSlider(213) };
sliders[214] = { .type=types.tvert, .location={{1, 2}, {1014, 1015}}, .options={}, .value=&ReadSlider(214) };
sliders[215] = { .type=types.tvert, .location={{1, 2}, {1018, 1019}}, .options={}, .value=&ReadSlider(215) };
sliders[216] = { .type=types.tvert, .location={{1, 2}, {1020, 1021}}, .options={}, .value=&ReadSlider(216) };
sliders[217] = { .type=types.v3, .location={{1, 2}, {1022, 1023}}, .options={}, .value=&ReadSlider(217) };
sliders[218] = { .type=types.v3, .location={{1, 2}, {1024, 1025}}, .options={}, .value=&ReadSlider(218) };
sliders[219] = { .type=types.tvert, .location={{1, 2}, {1030, 1031}}, .options={}, .value=&ReadSlider(219) };
sliders[220] = { .type=types.v4, .location={{1, 2}, {1033, 1034}}, .options={}, .value=&ReadSlider(220) };
sliders[221] = { .type=types.i2, .location={{1, 2}, {1037, 1038}}, .options={}, .value=&ReadSlider(221) };
sliders[222] = { .type=types.i1, .location={{1, 2}, {1056, 1057}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(222) };
sliders[223] = { .type=types.i1, .location={{1, 2}, {1058, 1059}}, .options={}, .value=&ReadSlider(223) };
sliders[224] = { .type=types.v3, .location={{1, 2}, {1060, 1061}}, .options={}, .value=&ReadSlider(224) };
sliders[225] = { .type=types.tvert, .location={{1, 2}, {1064, 1065}}, .options={}, .value=&ReadSlider(225) };
sliders[226] = { .type=types.tvert, .location={{1, 2}, {1072, 1073}}, .options={}, .value=&ReadSlider(226) };
sliders[227] = { .type=types.tvert, .location={{1, 2}, {1076, 1077}}, .options={}, .value=&ReadSlider(227) };
sliders[228] = { .type=types.tvert, .location={{1, 2}, {1080, 1081}}, .options={}, .value=&ReadSlider(228) };
sliders[229] = { .type=types.tvert, .location={{1, 2}, {1084, 1085}}, .options={}, .value=&ReadSlider(229) };
sliders[230] = { .type=types.tvert, .location={{1, 2}, {1088, 1089}}, .options={}, .value=&ReadSlider(230) };
sliders[231] = { .type=types.tvert, .location={{1, 2}, {1092, 1093}}, .options={}, .value=&ReadSlider(231) };
sliders[232] = { .type=types.tvert, .location={{1, 2}, {1096, 1097}}, .options={}, .value=&ReadSlider(232) };
sliders[233] = { .type=types.i1, .location={{1, 2}, {1102, 1103}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(233) };
sliders[234] = { .type=types.v1, .location={{1, 2}, {1104, 1105}}, .options={}, .value=&ReadSlider(234) };
sliders[235] = { .type=types.v1, .location={{1, 2}, {1106, 1107}}, .options={}, .value=&ReadSlider(235) };
sliders[236] = { .type=types.i1, .location={{1, 2}, {1108, 1109}}, .options={.flags = Slider_Clamp_01}, .value=&ReadSlider(236) };
sliders[237] = { .type=types.tvert, .location={{1, 2}, {1114, 1115}}, .options={}, .value=&ReadSlider(237) };
}
//-
// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1189:
global_decl Text_Object text_objects_[316];

// C:\Users\vodan\4ed\code\meta\meta_print.cpp:1194:
global FUI_File_Data fui_files_[3] ={
{},
{
 .index = 1,
 .name = strlit("driver_animate.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_1)},
 .text_objects = make_slice(text_objects_, {0,0}),
 .sliders = make_slice(global_sliders, {0,2}),
 .vertices_info = make_slice(vertices_info_, {0,0}),
 },
{
 .index = 2,
 .name = strlit("driver.kc"),
 .marked_positions = {ArrayAndCount(marked_positions_file_2)},
 .text_objects = make_slice(text_objects_, {0,316}),
 .sliders = make_slice(global_sliders, {2,238}),
 .vertices_info = make_slice(vertices_info_, {0,10}),
 },
};
